package diagrams

import (
	"time"

	"github.com/fullstack-lang/gongdoc/go/models"

	// injection point for ident package import declaration
	ref_models "github.com/thomaspeugeot/gongreqif/go/models"
)

// generated in order to avoid error in the package import
// if there are no elements in the stage to marshall
var _ time.Time

// Injection point for meta package dummy declaration
var _ ref_models.StageStruct

// When parsed, those maps will help with the renaming process
var _ map[string]any = map[string]any{
	// injection point for docLink to identifiers

	"ref_models.ALTERNATIVEID": &(ref_models.ALTERNATIVEID{}),

	"ref_models.ALTERNATIVEID.IDENTIFIERAttr": (ref_models.ALTERNATIVEID{}).IDENTIFIERAttr,

	"ref_models.ALTERNATIVEID.Name": (ref_models.ALTERNATIVEID{}).Name,

	"ref_models.ATTRIBUTEDEFINITIONBOOLEAN": &(ref_models.ATTRIBUTEDEFINITIONBOOLEAN{}),

	"ref_models.ATTRIBUTEDEFINITIONBOOLEAN.ALTERNATIVEID": (ref_models.ATTRIBUTEDEFINITIONBOOLEAN{}).ALTERNATIVEID,

	"ref_models.ATTRIBUTEDEFINITIONBOOLEAN.DEFAULTVALUE": (ref_models.ATTRIBUTEDEFINITIONBOOLEAN{}).DEFAULTVALUE,

	"ref_models.ATTRIBUTEDEFINITIONBOOLEAN.DESCAttr": (ref_models.ATTRIBUTEDEFINITIONBOOLEAN{}).DESCAttr,

	"ref_models.ATTRIBUTEDEFINITIONBOOLEAN.IDENTIFIERAttr": (ref_models.ATTRIBUTEDEFINITIONBOOLEAN{}).IDENTIFIERAttr,

	"ref_models.ATTRIBUTEDEFINITIONBOOLEAN.ISEDITABLEAttr": (ref_models.ATTRIBUTEDEFINITIONBOOLEAN{}).ISEDITABLEAttr,

	"ref_models.ATTRIBUTEDEFINITIONBOOLEAN.LASTCHANGEAttr": (ref_models.ATTRIBUTEDEFINITIONBOOLEAN{}).LASTCHANGEAttr,

	"ref_models.ATTRIBUTEDEFINITIONBOOLEAN.LONGNAMEAttr": (ref_models.ATTRIBUTEDEFINITIONBOOLEAN{}).LONGNAMEAttr,

	"ref_models.ATTRIBUTEDEFINITIONBOOLEAN.Name": (ref_models.ATTRIBUTEDEFINITIONBOOLEAN{}).Name,

	"ref_models.ATTRIBUTEDEFINITIONBOOLEAN.TYPE": (ref_models.ATTRIBUTEDEFINITIONBOOLEAN{}).TYPE,

	"ref_models.ATTRIBUTEDEFINITIONDATE": &(ref_models.ATTRIBUTEDEFINITIONDATE{}),

	"ref_models.ATTRIBUTEDEFINITIONDATE.ALTERNATIVEID": (ref_models.ATTRIBUTEDEFINITIONDATE{}).ALTERNATIVEID,

	"ref_models.ATTRIBUTEDEFINITIONDATE.DEFAULTVALUE": (ref_models.ATTRIBUTEDEFINITIONDATE{}).DEFAULTVALUE,

	"ref_models.ATTRIBUTEDEFINITIONDATE.DESCAttr": (ref_models.ATTRIBUTEDEFINITIONDATE{}).DESCAttr,

	"ref_models.ATTRIBUTEDEFINITIONDATE.IDENTIFIERAttr": (ref_models.ATTRIBUTEDEFINITIONDATE{}).IDENTIFIERAttr,

	"ref_models.ATTRIBUTEDEFINITIONDATE.ISEDITABLEAttr": (ref_models.ATTRIBUTEDEFINITIONDATE{}).ISEDITABLEAttr,

	"ref_models.ATTRIBUTEDEFINITIONDATE.LASTCHANGEAttr": (ref_models.ATTRIBUTEDEFINITIONDATE{}).LASTCHANGEAttr,

	"ref_models.ATTRIBUTEDEFINITIONDATE.LONGNAMEAttr": (ref_models.ATTRIBUTEDEFINITIONDATE{}).LONGNAMEAttr,

	"ref_models.ATTRIBUTEDEFINITIONDATE.Name": (ref_models.ATTRIBUTEDEFINITIONDATE{}).Name,

	"ref_models.ATTRIBUTEDEFINITIONDATE.TYPE": (ref_models.ATTRIBUTEDEFINITIONDATE{}).TYPE,

	"ref_models.ATTRIBUTEDEFINITIONENUMERATION": &(ref_models.ATTRIBUTEDEFINITIONENUMERATION{}),

	"ref_models.ATTRIBUTEDEFINITIONENUMERATION.ALTERNATIVEID": (ref_models.ATTRIBUTEDEFINITIONENUMERATION{}).ALTERNATIVEID,

	"ref_models.ATTRIBUTEDEFINITIONENUMERATION.DEFAULTVALUE": (ref_models.ATTRIBUTEDEFINITIONENUMERATION{}).DEFAULTVALUE,

	"ref_models.ATTRIBUTEDEFINITIONENUMERATION.DESCAttr": (ref_models.ATTRIBUTEDEFINITIONENUMERATION{}).DESCAttr,

	"ref_models.ATTRIBUTEDEFINITIONENUMERATION.IDENTIFIERAttr": (ref_models.ATTRIBUTEDEFINITIONENUMERATION{}).IDENTIFIERAttr,

	"ref_models.ATTRIBUTEDEFINITIONENUMERATION.ISEDITABLEAttr": (ref_models.ATTRIBUTEDEFINITIONENUMERATION{}).ISEDITABLEAttr,

	"ref_models.ATTRIBUTEDEFINITIONENUMERATION.LASTCHANGEAttr": (ref_models.ATTRIBUTEDEFINITIONENUMERATION{}).LASTCHANGEAttr,

	"ref_models.ATTRIBUTEDEFINITIONENUMERATION.LONGNAMEAttr": (ref_models.ATTRIBUTEDEFINITIONENUMERATION{}).LONGNAMEAttr,

	"ref_models.ATTRIBUTEDEFINITIONENUMERATION.MULTIVALUEDAttr": (ref_models.ATTRIBUTEDEFINITIONENUMERATION{}).MULTIVALUEDAttr,

	"ref_models.ATTRIBUTEDEFINITIONENUMERATION.Name": (ref_models.ATTRIBUTEDEFINITIONENUMERATION{}).Name,

	"ref_models.ATTRIBUTEDEFINITIONENUMERATION.TYPE": (ref_models.ATTRIBUTEDEFINITIONENUMERATION{}).TYPE,

	"ref_models.ATTRIBUTEDEFINITIONINTEGER": &(ref_models.ATTRIBUTEDEFINITIONINTEGER{}),

	"ref_models.ATTRIBUTEDEFINITIONINTEGER.ALTERNATIVEID": (ref_models.ATTRIBUTEDEFINITIONINTEGER{}).ALTERNATIVEID,

	"ref_models.ATTRIBUTEDEFINITIONINTEGER.DEFAULTVALUE": (ref_models.ATTRIBUTEDEFINITIONINTEGER{}).DEFAULTVALUE,

	"ref_models.ATTRIBUTEDEFINITIONINTEGER.DESCAttr": (ref_models.ATTRIBUTEDEFINITIONINTEGER{}).DESCAttr,

	"ref_models.ATTRIBUTEDEFINITIONINTEGER.IDENTIFIERAttr": (ref_models.ATTRIBUTEDEFINITIONINTEGER{}).IDENTIFIERAttr,

	"ref_models.ATTRIBUTEDEFINITIONINTEGER.ISEDITABLEAttr": (ref_models.ATTRIBUTEDEFINITIONINTEGER{}).ISEDITABLEAttr,

	"ref_models.ATTRIBUTEDEFINITIONINTEGER.LASTCHANGEAttr": (ref_models.ATTRIBUTEDEFINITIONINTEGER{}).LASTCHANGEAttr,

	"ref_models.ATTRIBUTEDEFINITIONINTEGER.LONGNAMEAttr": (ref_models.ATTRIBUTEDEFINITIONINTEGER{}).LONGNAMEAttr,

	"ref_models.ATTRIBUTEDEFINITIONINTEGER.Name": (ref_models.ATTRIBUTEDEFINITIONINTEGER{}).Name,

	"ref_models.ATTRIBUTEDEFINITIONINTEGER.TYPE": (ref_models.ATTRIBUTEDEFINITIONINTEGER{}).TYPE,

	"ref_models.ATTRIBUTEDEFINITIONREAL": &(ref_models.ATTRIBUTEDEFINITIONREAL{}),

	"ref_models.ATTRIBUTEDEFINITIONREAL.ALTERNATIVEID": (ref_models.ATTRIBUTEDEFINITIONREAL{}).ALTERNATIVEID,

	"ref_models.ATTRIBUTEDEFINITIONREAL.DEFAULTVALUE": (ref_models.ATTRIBUTEDEFINITIONREAL{}).DEFAULTVALUE,

	"ref_models.ATTRIBUTEDEFINITIONREAL.DESCAttr": (ref_models.ATTRIBUTEDEFINITIONREAL{}).DESCAttr,

	"ref_models.ATTRIBUTEDEFINITIONREAL.IDENTIFIERAttr": (ref_models.ATTRIBUTEDEFINITIONREAL{}).IDENTIFIERAttr,

	"ref_models.ATTRIBUTEDEFINITIONREAL.ISEDITABLEAttr": (ref_models.ATTRIBUTEDEFINITIONREAL{}).ISEDITABLEAttr,

	"ref_models.ATTRIBUTEDEFINITIONREAL.LASTCHANGEAttr": (ref_models.ATTRIBUTEDEFINITIONREAL{}).LASTCHANGEAttr,

	"ref_models.ATTRIBUTEDEFINITIONREAL.LONGNAMEAttr": (ref_models.ATTRIBUTEDEFINITIONREAL{}).LONGNAMEAttr,

	"ref_models.ATTRIBUTEDEFINITIONREAL.Name": (ref_models.ATTRIBUTEDEFINITIONREAL{}).Name,

	"ref_models.ATTRIBUTEDEFINITIONREAL.TYPE": (ref_models.ATTRIBUTEDEFINITIONREAL{}).TYPE,

	"ref_models.ATTRIBUTEDEFINITIONSTRING": &(ref_models.ATTRIBUTEDEFINITIONSTRING{}),

	"ref_models.ATTRIBUTEDEFINITIONSTRING.ALTERNATIVEID": (ref_models.ATTRIBUTEDEFINITIONSTRING{}).ALTERNATIVEID,

	"ref_models.ATTRIBUTEDEFINITIONSTRING.DEFAULTVALUE": (ref_models.ATTRIBUTEDEFINITIONSTRING{}).DEFAULTVALUE,

	"ref_models.ATTRIBUTEDEFINITIONSTRING.DESCAttr": (ref_models.ATTRIBUTEDEFINITIONSTRING{}).DESCAttr,

	"ref_models.ATTRIBUTEDEFINITIONSTRING.IDENTIFIERAttr": (ref_models.ATTRIBUTEDEFINITIONSTRING{}).IDENTIFIERAttr,

	"ref_models.ATTRIBUTEDEFINITIONSTRING.ISEDITABLEAttr": (ref_models.ATTRIBUTEDEFINITIONSTRING{}).ISEDITABLEAttr,

	"ref_models.ATTRIBUTEDEFINITIONSTRING.LASTCHANGEAttr": (ref_models.ATTRIBUTEDEFINITIONSTRING{}).LASTCHANGEAttr,

	"ref_models.ATTRIBUTEDEFINITIONSTRING.LONGNAMEAttr": (ref_models.ATTRIBUTEDEFINITIONSTRING{}).LONGNAMEAttr,

	"ref_models.ATTRIBUTEDEFINITIONSTRING.Name": (ref_models.ATTRIBUTEDEFINITIONSTRING{}).Name,

	"ref_models.ATTRIBUTEDEFINITIONSTRING.TYPE": (ref_models.ATTRIBUTEDEFINITIONSTRING{}).TYPE,

	"ref_models.ATTRIBUTEDEFINITIONXHTML": &(ref_models.ATTRIBUTEDEFINITIONXHTML{}),

	"ref_models.ATTRIBUTEDEFINITIONXHTML.ALTERNATIVEID": (ref_models.ATTRIBUTEDEFINITIONXHTML{}).ALTERNATIVEID,

	"ref_models.ATTRIBUTEDEFINITIONXHTML.DEFAULTVALUE": (ref_models.ATTRIBUTEDEFINITIONXHTML{}).DEFAULTVALUE,

	"ref_models.ATTRIBUTEDEFINITIONXHTML.DESCAttr": (ref_models.ATTRIBUTEDEFINITIONXHTML{}).DESCAttr,

	"ref_models.ATTRIBUTEDEFINITIONXHTML.IDENTIFIERAttr": (ref_models.ATTRIBUTEDEFINITIONXHTML{}).IDENTIFIERAttr,

	"ref_models.ATTRIBUTEDEFINITIONXHTML.ISEDITABLEAttr": (ref_models.ATTRIBUTEDEFINITIONXHTML{}).ISEDITABLEAttr,

	"ref_models.ATTRIBUTEDEFINITIONXHTML.LASTCHANGEAttr": (ref_models.ATTRIBUTEDEFINITIONXHTML{}).LASTCHANGEAttr,

	"ref_models.ATTRIBUTEDEFINITIONXHTML.LONGNAMEAttr": (ref_models.ATTRIBUTEDEFINITIONXHTML{}).LONGNAMEAttr,

	"ref_models.ATTRIBUTEDEFINITIONXHTML.Name": (ref_models.ATTRIBUTEDEFINITIONXHTML{}).Name,

	"ref_models.ATTRIBUTEDEFINITIONXHTML.TYPE": (ref_models.ATTRIBUTEDEFINITIONXHTML{}).TYPE,

	"ref_models.ATTRIBUTEVALUEBOOLEAN": &(ref_models.ATTRIBUTEVALUEBOOLEAN{}),

	"ref_models.ATTRIBUTEVALUEBOOLEAN.DEFINITION": (ref_models.ATTRIBUTEVALUEBOOLEAN{}).DEFINITION,

	"ref_models.ATTRIBUTEVALUEBOOLEAN.Name": (ref_models.ATTRIBUTEVALUEBOOLEAN{}).Name,

	"ref_models.ATTRIBUTEVALUEBOOLEAN.THEVALUEAttr": (ref_models.ATTRIBUTEVALUEBOOLEAN{}).THEVALUEAttr,

	"ref_models.ATTRIBUTEVALUEDATE": &(ref_models.ATTRIBUTEVALUEDATE{}),

	"ref_models.ATTRIBUTEVALUEDATE.DEFINITION": (ref_models.ATTRIBUTEVALUEDATE{}).DEFINITION,

	"ref_models.ATTRIBUTEVALUEDATE.Name": (ref_models.ATTRIBUTEVALUEDATE{}).Name,

	"ref_models.ATTRIBUTEVALUEDATE.THEVALUEAttr": (ref_models.ATTRIBUTEVALUEDATE{}).THEVALUEAttr,

	"ref_models.ATTRIBUTEVALUEENUMERATION": &(ref_models.ATTRIBUTEVALUEENUMERATION{}),

	"ref_models.ATTRIBUTEVALUEENUMERATION.DEFINITION": (ref_models.ATTRIBUTEVALUEENUMERATION{}).DEFINITION,

	"ref_models.ATTRIBUTEVALUEENUMERATION.Name": (ref_models.ATTRIBUTEVALUEENUMERATION{}).Name,

	"ref_models.ATTRIBUTEVALUEENUMERATION.VALUES": (ref_models.ATTRIBUTEVALUEENUMERATION{}).VALUES,

	"ref_models.ATTRIBUTEVALUEINTEGER": &(ref_models.ATTRIBUTEVALUEINTEGER{}),

	"ref_models.ATTRIBUTEVALUEINTEGER.DEFINITION": (ref_models.ATTRIBUTEVALUEINTEGER{}).DEFINITION,

	"ref_models.ATTRIBUTEVALUEINTEGER.Name": (ref_models.ATTRIBUTEVALUEINTEGER{}).Name,

	"ref_models.ATTRIBUTEVALUEINTEGER.THEVALUEAttr": (ref_models.ATTRIBUTEVALUEINTEGER{}).THEVALUEAttr,

	"ref_models.ATTRIBUTEVALUEREAL": &(ref_models.ATTRIBUTEVALUEREAL{}),

	"ref_models.ATTRIBUTEVALUEREAL.DEFINITION": (ref_models.ATTRIBUTEVALUEREAL{}).DEFINITION,

	"ref_models.ATTRIBUTEVALUEREAL.Name": (ref_models.ATTRIBUTEVALUEREAL{}).Name,

	"ref_models.ATTRIBUTEVALUEREAL.THEVALUEAttr": (ref_models.ATTRIBUTEVALUEREAL{}).THEVALUEAttr,

	"ref_models.ATTRIBUTEVALUESTRING": &(ref_models.ATTRIBUTEVALUESTRING{}),

	"ref_models.ATTRIBUTEVALUESTRING.DEFINITION": (ref_models.ATTRIBUTEVALUESTRING{}).DEFINITION,

	"ref_models.ATTRIBUTEVALUESTRING.Name": (ref_models.ATTRIBUTEVALUESTRING{}).Name,

	"ref_models.ATTRIBUTEVALUESTRING.THEVALUEAttr": (ref_models.ATTRIBUTEVALUESTRING{}).THEVALUEAttr,

	"ref_models.ATTRIBUTEVALUEXHTML": &(ref_models.ATTRIBUTEVALUEXHTML{}),

	"ref_models.ATTRIBUTEVALUEXHTML.DEFINITION": (ref_models.ATTRIBUTEVALUEXHTML{}).DEFINITION,

	"ref_models.ATTRIBUTEVALUEXHTML.ISSIMPLIFIEDAttr": (ref_models.ATTRIBUTEVALUEXHTML{}).ISSIMPLIFIEDAttr,

	"ref_models.ATTRIBUTEVALUEXHTML.Name": (ref_models.ATTRIBUTEVALUEXHTML{}).Name,

	"ref_models.ATTRIBUTEVALUEXHTML.THEORIGINALVALUE": (ref_models.ATTRIBUTEVALUEXHTML{}).THEORIGINALVALUE,

	"ref_models.ATTRIBUTEVALUEXHTML.THEVALUE": (ref_models.ATTRIBUTEVALUEXHTML{}).THEVALUE,

	"ref_models.CHILDREN": &(ref_models.CHILDREN{}),

	"ref_models.CHILDREN.Name": (ref_models.CHILDREN{}).Name,

	"ref_models.CHILDREN.SPECHIERARCHY": (ref_models.CHILDREN{}).SPECHIERARCHY,

	"ref_models.CORECONTENT": &(ref_models.CORECONTENT{}),

	"ref_models.CORECONTENT.Name": (ref_models.CORECONTENT{}).Name,

	"ref_models.CORECONTENT.REQIFCONTENT": (ref_models.CORECONTENT{}).REQIFCONTENT,

	"ref_models.DATATYPEDEFINITIONBOOLEAN": &(ref_models.DATATYPEDEFINITIONBOOLEAN{}),

	"ref_models.DATATYPEDEFINITIONBOOLEAN.ALTERNATIVEID": (ref_models.DATATYPEDEFINITIONBOOLEAN{}).ALTERNATIVEID,

	"ref_models.DATATYPEDEFINITIONBOOLEAN.DESCAttr": (ref_models.DATATYPEDEFINITIONBOOLEAN{}).DESCAttr,

	"ref_models.DATATYPEDEFINITIONBOOLEAN.IDENTIFIERAttr": (ref_models.DATATYPEDEFINITIONBOOLEAN{}).IDENTIFIERAttr,

	"ref_models.DATATYPEDEFINITIONBOOLEAN.LASTCHANGEAttr": (ref_models.DATATYPEDEFINITIONBOOLEAN{}).LASTCHANGEAttr,

	"ref_models.DATATYPEDEFINITIONBOOLEAN.LONGNAMEAttr": (ref_models.DATATYPEDEFINITIONBOOLEAN{}).LONGNAMEAttr,

	"ref_models.DATATYPEDEFINITIONBOOLEAN.Name": (ref_models.DATATYPEDEFINITIONBOOLEAN{}).Name,

	"ref_models.DATATYPEDEFINITIONDATE": &(ref_models.DATATYPEDEFINITIONDATE{}),

	"ref_models.DATATYPEDEFINITIONDATE.ALTERNATIVEID": (ref_models.DATATYPEDEFINITIONDATE{}).ALTERNATIVEID,

	"ref_models.DATATYPEDEFINITIONDATE.DESCAttr": (ref_models.DATATYPEDEFINITIONDATE{}).DESCAttr,

	"ref_models.DATATYPEDEFINITIONDATE.IDENTIFIERAttr": (ref_models.DATATYPEDEFINITIONDATE{}).IDENTIFIERAttr,

	"ref_models.DATATYPEDEFINITIONDATE.LASTCHANGEAttr": (ref_models.DATATYPEDEFINITIONDATE{}).LASTCHANGEAttr,

	"ref_models.DATATYPEDEFINITIONDATE.LONGNAMEAttr": (ref_models.DATATYPEDEFINITIONDATE{}).LONGNAMEAttr,

	"ref_models.DATATYPEDEFINITIONDATE.Name": (ref_models.DATATYPEDEFINITIONDATE{}).Name,

	"ref_models.DATATYPEDEFINITIONENUMERATION": &(ref_models.DATATYPEDEFINITIONENUMERATION{}),

	"ref_models.DATATYPEDEFINITIONENUMERATION.ALTERNATIVEID": (ref_models.DATATYPEDEFINITIONENUMERATION{}).ALTERNATIVEID,

	"ref_models.DATATYPEDEFINITIONENUMERATION.DESCAttr": (ref_models.DATATYPEDEFINITIONENUMERATION{}).DESCAttr,

	"ref_models.DATATYPEDEFINITIONENUMERATION.IDENTIFIERAttr": (ref_models.DATATYPEDEFINITIONENUMERATION{}).IDENTIFIERAttr,

	"ref_models.DATATYPEDEFINITIONENUMERATION.LASTCHANGEAttr": (ref_models.DATATYPEDEFINITIONENUMERATION{}).LASTCHANGEAttr,

	"ref_models.DATATYPEDEFINITIONENUMERATION.LONGNAMEAttr": (ref_models.DATATYPEDEFINITIONENUMERATION{}).LONGNAMEAttr,

	"ref_models.DATATYPEDEFINITIONENUMERATION.Name": (ref_models.DATATYPEDEFINITIONENUMERATION{}).Name,

	"ref_models.DATATYPEDEFINITIONENUMERATION.SPECIFIEDVALUES": (ref_models.DATATYPEDEFINITIONENUMERATION{}).SPECIFIEDVALUES,

	"ref_models.DATATYPEDEFINITIONINTEGER": &(ref_models.DATATYPEDEFINITIONINTEGER{}),

	"ref_models.DATATYPEDEFINITIONINTEGER.ALTERNATIVEID": (ref_models.DATATYPEDEFINITIONINTEGER{}).ALTERNATIVEID,

	"ref_models.DATATYPEDEFINITIONINTEGER.DESCAttr": (ref_models.DATATYPEDEFINITIONINTEGER{}).DESCAttr,

	"ref_models.DATATYPEDEFINITIONINTEGER.IDENTIFIERAttr": (ref_models.DATATYPEDEFINITIONINTEGER{}).IDENTIFIERAttr,

	"ref_models.DATATYPEDEFINITIONINTEGER.LASTCHANGEAttr": (ref_models.DATATYPEDEFINITIONINTEGER{}).LASTCHANGEAttr,

	"ref_models.DATATYPEDEFINITIONINTEGER.LONGNAMEAttr": (ref_models.DATATYPEDEFINITIONINTEGER{}).LONGNAMEAttr,

	"ref_models.DATATYPEDEFINITIONINTEGER.MAXAttr": (ref_models.DATATYPEDEFINITIONINTEGER{}).MAXAttr,

	"ref_models.DATATYPEDEFINITIONINTEGER.MINAttr": (ref_models.DATATYPEDEFINITIONINTEGER{}).MINAttr,

	"ref_models.DATATYPEDEFINITIONINTEGER.Name": (ref_models.DATATYPEDEFINITIONINTEGER{}).Name,

	"ref_models.DATATYPEDEFINITIONREAL": &(ref_models.DATATYPEDEFINITIONREAL{}),

	"ref_models.DATATYPEDEFINITIONREAL.ACCURACYAttr": (ref_models.DATATYPEDEFINITIONREAL{}).ACCURACYAttr,

	"ref_models.DATATYPEDEFINITIONREAL.ALTERNATIVEID": (ref_models.DATATYPEDEFINITIONREAL{}).ALTERNATIVEID,

	"ref_models.DATATYPEDEFINITIONREAL.DESCAttr": (ref_models.DATATYPEDEFINITIONREAL{}).DESCAttr,

	"ref_models.DATATYPEDEFINITIONREAL.IDENTIFIERAttr": (ref_models.DATATYPEDEFINITIONREAL{}).IDENTIFIERAttr,

	"ref_models.DATATYPEDEFINITIONREAL.LASTCHANGEAttr": (ref_models.DATATYPEDEFINITIONREAL{}).LASTCHANGEAttr,

	"ref_models.DATATYPEDEFINITIONREAL.LONGNAMEAttr": (ref_models.DATATYPEDEFINITIONREAL{}).LONGNAMEAttr,

	"ref_models.DATATYPEDEFINITIONREAL.MAXAttr": (ref_models.DATATYPEDEFINITIONREAL{}).MAXAttr,

	"ref_models.DATATYPEDEFINITIONREAL.MINAttr": (ref_models.DATATYPEDEFINITIONREAL{}).MINAttr,

	"ref_models.DATATYPEDEFINITIONREAL.Name": (ref_models.DATATYPEDEFINITIONREAL{}).Name,

	"ref_models.DATATYPEDEFINITIONSTRING": &(ref_models.DATATYPEDEFINITIONSTRING{}),

	"ref_models.DATATYPEDEFINITIONSTRING.ALTERNATIVEID": (ref_models.DATATYPEDEFINITIONSTRING{}).ALTERNATIVEID,

	"ref_models.DATATYPEDEFINITIONSTRING.DESCAttr": (ref_models.DATATYPEDEFINITIONSTRING{}).DESCAttr,

	"ref_models.DATATYPEDEFINITIONSTRING.IDENTIFIERAttr": (ref_models.DATATYPEDEFINITIONSTRING{}).IDENTIFIERAttr,

	"ref_models.DATATYPEDEFINITIONSTRING.LASTCHANGEAttr": (ref_models.DATATYPEDEFINITIONSTRING{}).LASTCHANGEAttr,

	"ref_models.DATATYPEDEFINITIONSTRING.LONGNAMEAttr": (ref_models.DATATYPEDEFINITIONSTRING{}).LONGNAMEAttr,

	"ref_models.DATATYPEDEFINITIONSTRING.MAXLENGTHAttr": (ref_models.DATATYPEDEFINITIONSTRING{}).MAXLENGTHAttr,

	"ref_models.DATATYPEDEFINITIONSTRING.Name": (ref_models.DATATYPEDEFINITIONSTRING{}).Name,

	"ref_models.DATATYPEDEFINITIONXHTML": &(ref_models.DATATYPEDEFINITIONXHTML{}),

	"ref_models.DATATYPEDEFINITIONXHTML.ALTERNATIVEID": (ref_models.DATATYPEDEFINITIONXHTML{}).ALTERNATIVEID,

	"ref_models.DATATYPEDEFINITIONXHTML.DESCAttr": (ref_models.DATATYPEDEFINITIONXHTML{}).DESCAttr,

	"ref_models.DATATYPEDEFINITIONXHTML.IDENTIFIERAttr": (ref_models.DATATYPEDEFINITIONXHTML{}).IDENTIFIERAttr,

	"ref_models.DATATYPEDEFINITIONXHTML.LASTCHANGEAttr": (ref_models.DATATYPEDEFINITIONXHTML{}).LASTCHANGEAttr,

	"ref_models.DATATYPEDEFINITIONXHTML.LONGNAMEAttr": (ref_models.DATATYPEDEFINITIONXHTML{}).LONGNAMEAttr,

	"ref_models.DATATYPEDEFINITIONXHTML.Name": (ref_models.DATATYPEDEFINITIONXHTML{}).Name,

	"ref_models.DATATYPES": &(ref_models.DATATYPES{}),

	"ref_models.DATATYPES.DATATYPEDEFINITIONBOOLEAN": (ref_models.DATATYPES{}).DATATYPEDEFINITIONBOOLEAN,

	"ref_models.DATATYPES.DATATYPEDEFINITIONDATE": (ref_models.DATATYPES{}).DATATYPEDEFINITIONDATE,

	"ref_models.DATATYPES.DATATYPEDEFINITIONENUMERATION": (ref_models.DATATYPES{}).DATATYPEDEFINITIONENUMERATION,

	"ref_models.DATATYPES.DATATYPEDEFINITIONINTEGER": (ref_models.DATATYPES{}).DATATYPEDEFINITIONINTEGER,

	"ref_models.DATATYPES.DATATYPEDEFINITIONREAL": (ref_models.DATATYPES{}).DATATYPEDEFINITIONREAL,

	"ref_models.DATATYPES.DATATYPEDEFINITIONSTRING": (ref_models.DATATYPES{}).DATATYPEDEFINITIONSTRING,

	"ref_models.DATATYPES.DATATYPEDEFINITIONXHTML": (ref_models.DATATYPES{}).DATATYPEDEFINITIONXHTML,

	"ref_models.DATATYPES.Name": (ref_models.DATATYPES{}).Name,

	"ref_models.DEFAULTVALUE": &(ref_models.DEFAULTVALUE{}),

	"ref_models.DEFAULTVALUE.ATTRIBUTEVALUEBOOLEAN": (ref_models.DEFAULTVALUE{}).ATTRIBUTEVALUEBOOLEAN,

	"ref_models.DEFAULTVALUE.Name": (ref_models.DEFAULTVALUE{}).Name,

	"ref_models.DEFINITION": &(ref_models.DEFINITION{}),

	"ref_models.DEFINITION.ATTRIBUTEDEFINITIONBOOLEANREF": (ref_models.DEFINITION{}).ATTRIBUTEDEFINITIONBOOLEANREF,

	"ref_models.DEFINITION.Name": (ref_models.DEFINITION{}).Name,

	"ref_models.EDITABLEATTS": &(ref_models.EDITABLEATTS{}),

	"ref_models.EDITABLEATTS.Name": (ref_models.EDITABLEATTS{}).Name,

	"ref_models.EMBEDDEDVALUE": &(ref_models.EMBEDDEDVALUE{}),

	"ref_models.EMBEDDEDVALUE.KEYAttr": (ref_models.EMBEDDEDVALUE{}).KEYAttr,

	"ref_models.EMBEDDEDVALUE.Name": (ref_models.EMBEDDEDVALUE{}).Name,

	"ref_models.EMBEDDEDVALUE.OTHERCONTENTAttr": (ref_models.EMBEDDEDVALUE{}).OTHERCONTENTAttr,

	"ref_models.ENUMVALUE": &(ref_models.ENUMVALUE{}),

	"ref_models.ENUMVALUE.ALTERNATIVEID": (ref_models.ENUMVALUE{}).ALTERNATIVEID,

	"ref_models.ENUMVALUE.DESCAttr": (ref_models.ENUMVALUE{}).DESCAttr,

	"ref_models.ENUMVALUE.IDENTIFIERAttr": (ref_models.ENUMVALUE{}).IDENTIFIERAttr,

	"ref_models.ENUMVALUE.LASTCHANGEAttr": (ref_models.ENUMVALUE{}).LASTCHANGEAttr,

	"ref_models.ENUMVALUE.LONGNAMEAttr": (ref_models.ENUMVALUE{}).LONGNAMEAttr,

	"ref_models.ENUMVALUE.Name": (ref_models.ENUMVALUE{}).Name,

	"ref_models.ENUMVALUE.PROPERTIES": (ref_models.ENUMVALUE{}).PROPERTIES,

	"ref_models.GLOBALREF": ref_models.GLOBALREF(""),

	"ref_models.LOCALREF": ref_models.LOCALREF(""),

	"ref_models.OBJECT": &(ref_models.OBJECT{}),

	"ref_models.OBJECT.Name": (ref_models.OBJECT{}).Name,

	"ref_models.OBJECT.SPECOBJECTREF": (ref_models.OBJECT{}).SPECOBJECTREF,

	"ref_models.PROPERTIES": &(ref_models.PROPERTIES{}),

	"ref_models.PROPERTIES.EMBEDDEDVALUE": (ref_models.PROPERTIES{}).EMBEDDEDVALUE,

	"ref_models.PROPERTIES.Name": (ref_models.PROPERTIES{}).Name,

	"ref_models.RELATIONGROUP": &(ref_models.RELATIONGROUP{}),

	"ref_models.RELATIONGROUP.ALTERNATIVEID": (ref_models.RELATIONGROUP{}).ALTERNATIVEID,

	"ref_models.RELATIONGROUP.DESCAttr": (ref_models.RELATIONGROUP{}).DESCAttr,

	"ref_models.RELATIONGROUP.IDENTIFIERAttr": (ref_models.RELATIONGROUP{}).IDENTIFIERAttr,

	"ref_models.RELATIONGROUP.LASTCHANGEAttr": (ref_models.RELATIONGROUP{}).LASTCHANGEAttr,

	"ref_models.RELATIONGROUP.LONGNAMEAttr": (ref_models.RELATIONGROUP{}).LONGNAMEAttr,

	"ref_models.RELATIONGROUP.Name": (ref_models.RELATIONGROUP{}).Name,

	"ref_models.RELATIONGROUP.SOURCESPECIFICATION": (ref_models.RELATIONGROUP{}).SOURCESPECIFICATION,

	"ref_models.RELATIONGROUP.SPECRELATIONS": (ref_models.RELATIONGROUP{}).SPECRELATIONS,

	"ref_models.RELATIONGROUP.TARGETSPECIFICATION": (ref_models.RELATIONGROUP{}).TARGETSPECIFICATION,

	"ref_models.RELATIONGROUP.TYPE": (ref_models.RELATIONGROUP{}).TYPE,

	"ref_models.RELATIONGROUPTYPE": &(ref_models.RELATIONGROUPTYPE{}),

	"ref_models.RELATIONGROUPTYPE.ALTERNATIVEID": (ref_models.RELATIONGROUPTYPE{}).ALTERNATIVEID,

	"ref_models.RELATIONGROUPTYPE.DESCAttr": (ref_models.RELATIONGROUPTYPE{}).DESCAttr,

	"ref_models.RELATIONGROUPTYPE.IDENTIFIERAttr": (ref_models.RELATIONGROUPTYPE{}).IDENTIFIERAttr,

	"ref_models.RELATIONGROUPTYPE.LASTCHANGEAttr": (ref_models.RELATIONGROUPTYPE{}).LASTCHANGEAttr,

	"ref_models.RELATIONGROUPTYPE.LONGNAMEAttr": (ref_models.RELATIONGROUPTYPE{}).LONGNAMEAttr,

	"ref_models.RELATIONGROUPTYPE.Name": (ref_models.RELATIONGROUPTYPE{}).Name,

	"ref_models.RELATIONGROUPTYPE.SPECATTRIBUTES": (ref_models.RELATIONGROUPTYPE{}).SPECATTRIBUTES,

	"ref_models.REQIF": &(ref_models.REQIF{}),

	"ref_models.REQIF.CORECONTENT": (ref_models.REQIF{}).CORECONTENT,

	"ref_models.REQIF.HEADER": (ref_models.REQIF{}).HEADER,

	"ref_models.REQIF.Name": (ref_models.REQIF{}).Name,

	"ref_models.REQIFCONTENT": &(ref_models.REQIFCONTENT{}),

	"ref_models.REQIFCONTENT.DATATYPES": (ref_models.REQIFCONTENT{}).DATATYPES,

	"ref_models.REQIFCONTENT.Name": (ref_models.REQIFCONTENT{}).Name,

	"ref_models.REQIFCONTENT.SPECIFICATIONS": (ref_models.REQIFCONTENT{}).SPECIFICATIONS,

	"ref_models.REQIFCONTENT.SPECOBJECTS": (ref_models.REQIFCONTENT{}).SPECOBJECTS,

	"ref_models.REQIFCONTENT.SPECRELATIONGROUPS": (ref_models.REQIFCONTENT{}).SPECRELATIONGROUPS,

	"ref_models.REQIFCONTENT.SPECRELATIONS": (ref_models.REQIFCONTENT{}).SPECRELATIONS,

	"ref_models.REQIFCONTENT.SPECTYPES": (ref_models.REQIFCONTENT{}).SPECTYPES,

	"ref_models.REQIFHEADER": &(ref_models.REQIFHEADER{}),

	"ref_models.REQIFHEADER.COMMENT": (ref_models.REQIFHEADER{}).COMMENT,

	"ref_models.REQIFHEADER.CREATIONTIME": (ref_models.REQIFHEADER{}).CREATIONTIME,

	"ref_models.REQIFHEADER.IDENTIFIERAttr": (ref_models.REQIFHEADER{}).IDENTIFIERAttr,

	"ref_models.REQIFHEADER.Name": (ref_models.REQIFHEADER{}).Name,

	"ref_models.REQIFHEADER.REPOSITORYID": (ref_models.REQIFHEADER{}).REPOSITORYID,

	"ref_models.REQIFHEADER.REQIFTOOLID": (ref_models.REQIFHEADER{}).REQIFTOOLID,

	"ref_models.REQIFHEADER.REQIFVERSION": (ref_models.REQIFHEADER{}).REQIFVERSION,

	"ref_models.REQIFHEADER.SOURCETOOLID": (ref_models.REQIFHEADER{}).SOURCETOOLID,

	"ref_models.REQIFHEADER.TITLE": (ref_models.REQIFHEADER{}).TITLE,

	"ref_models.REQIFTOOLEXTENSION": &(ref_models.REQIFTOOLEXTENSION{}),

	"ref_models.REQIFTOOLEXTENSION.Name": (ref_models.REQIFTOOLEXTENSION{}).Name,

	"ref_models.REQIFTYPE": &(ref_models.REQIFTYPE{}),

	"ref_models.REQIFTYPE.DATATYPEDEFINITIONBOOLEANREF": (ref_models.REQIFTYPE{}).DATATYPEDEFINITIONBOOLEANREF,

	"ref_models.REQIFTYPE.Name": (ref_models.REQIFTYPE{}).Name,

	"ref_models.SOURCE": &(ref_models.SOURCE{}),

	"ref_models.SOURCE.Name": (ref_models.SOURCE{}).Name,

	"ref_models.SOURCE.SPECOBJECTREF": (ref_models.SOURCE{}).SPECOBJECTREF,

	"ref_models.SOURCESPECIFICATION": &(ref_models.SOURCESPECIFICATION{}),

	"ref_models.SOURCESPECIFICATION.Name": (ref_models.SOURCESPECIFICATION{}).Name,

	"ref_models.SOURCESPECIFICATION.SPECIFICATIONREF": (ref_models.SOURCESPECIFICATION{}).SPECIFICATIONREF,

	"ref_models.SPECATTRIBUTES": &(ref_models.SPECATTRIBUTES{}),

	"ref_models.SPECATTRIBUTES.ATTRIBUTEDEFINITIONBOOLEAN": (ref_models.SPECATTRIBUTES{}).ATTRIBUTEDEFINITIONBOOLEAN,

	"ref_models.SPECATTRIBUTES.ATTRIBUTEDEFINITIONDATE": (ref_models.SPECATTRIBUTES{}).ATTRIBUTEDEFINITIONDATE,

	"ref_models.SPECATTRIBUTES.ATTRIBUTEDEFINITIONENUMERATION": (ref_models.SPECATTRIBUTES{}).ATTRIBUTEDEFINITIONENUMERATION,

	"ref_models.SPECATTRIBUTES.ATTRIBUTEDEFINITIONINTEGER": (ref_models.SPECATTRIBUTES{}).ATTRIBUTEDEFINITIONINTEGER,

	"ref_models.SPECATTRIBUTES.ATTRIBUTEDEFINITIONREAL": (ref_models.SPECATTRIBUTES{}).ATTRIBUTEDEFINITIONREAL,

	"ref_models.SPECATTRIBUTES.ATTRIBUTEDEFINITIONSTRING": (ref_models.SPECATTRIBUTES{}).ATTRIBUTEDEFINITIONSTRING,

	"ref_models.SPECATTRIBUTES.ATTRIBUTEDEFINITIONXHTML": (ref_models.SPECATTRIBUTES{}).ATTRIBUTEDEFINITIONXHTML,

	"ref_models.SPECATTRIBUTES.Name": (ref_models.SPECATTRIBUTES{}).Name,

	"ref_models.SPECHIERARCHY": &(ref_models.SPECHIERARCHY{}),

	"ref_models.SPECHIERARCHY.ALTERNATIVEID": (ref_models.SPECHIERARCHY{}).ALTERNATIVEID,

	"ref_models.SPECHIERARCHY.CHILDREN": (ref_models.SPECHIERARCHY{}).CHILDREN,

	"ref_models.SPECHIERARCHY.DESCAttr": (ref_models.SPECHIERARCHY{}).DESCAttr,

	"ref_models.SPECHIERARCHY.EDITABLEATTS": (ref_models.SPECHIERARCHY{}).EDITABLEATTS,

	"ref_models.SPECHIERARCHY.IDENTIFIERAttr": (ref_models.SPECHIERARCHY{}).IDENTIFIERAttr,

	"ref_models.SPECHIERARCHY.ISEDITABLEAttr": (ref_models.SPECHIERARCHY{}).ISEDITABLEAttr,

	"ref_models.SPECHIERARCHY.ISTABLEINTERNALAttr": (ref_models.SPECHIERARCHY{}).ISTABLEINTERNALAttr,

	"ref_models.SPECHIERARCHY.LASTCHANGEAttr": (ref_models.SPECHIERARCHY{}).LASTCHANGEAttr,

	"ref_models.SPECHIERARCHY.LONGNAMEAttr": (ref_models.SPECHIERARCHY{}).LONGNAMEAttr,

	"ref_models.SPECHIERARCHY.Name": (ref_models.SPECHIERARCHY{}).Name,

	"ref_models.SPECHIERARCHY.OBJECT": (ref_models.SPECHIERARCHY{}).OBJECT,

	"ref_models.SPECIFICATION": &(ref_models.SPECIFICATION{}),

	"ref_models.SPECIFICATION.ALTERNATIVEID": (ref_models.SPECIFICATION{}).ALTERNATIVEID,

	"ref_models.SPECIFICATION.CHILDREN": (ref_models.SPECIFICATION{}).CHILDREN,

	"ref_models.SPECIFICATION.DESCAttr": (ref_models.SPECIFICATION{}).DESCAttr,

	"ref_models.SPECIFICATION.IDENTIFIERAttr": (ref_models.SPECIFICATION{}).IDENTIFIERAttr,

	"ref_models.SPECIFICATION.LASTCHANGEAttr": (ref_models.SPECIFICATION{}).LASTCHANGEAttr,

	"ref_models.SPECIFICATION.LONGNAMEAttr": (ref_models.SPECIFICATION{}).LONGNAMEAttr,

	"ref_models.SPECIFICATION.Name": (ref_models.SPECIFICATION{}).Name,

	"ref_models.SPECIFICATION.TYPE": (ref_models.SPECIFICATION{}).TYPE,

	"ref_models.SPECIFICATION.VALUES": (ref_models.SPECIFICATION{}).VALUES,

	"ref_models.SPECIFICATIONS": &(ref_models.SPECIFICATIONS{}),

	"ref_models.SPECIFICATIONS.Name": (ref_models.SPECIFICATIONS{}).Name,

	"ref_models.SPECIFICATIONS.SPECIFICATION": (ref_models.SPECIFICATIONS{}).SPECIFICATION,

	"ref_models.SPECIFICATIONTYPE": &(ref_models.SPECIFICATIONTYPE{}),

	"ref_models.SPECIFICATIONTYPE.ALTERNATIVEID": (ref_models.SPECIFICATIONTYPE{}).ALTERNATIVEID,

	"ref_models.SPECIFICATIONTYPE.DESCAttr": (ref_models.SPECIFICATIONTYPE{}).DESCAttr,

	"ref_models.SPECIFICATIONTYPE.IDENTIFIERAttr": (ref_models.SPECIFICATIONTYPE{}).IDENTIFIERAttr,

	"ref_models.SPECIFICATIONTYPE.LASTCHANGEAttr": (ref_models.SPECIFICATIONTYPE{}).LASTCHANGEAttr,

	"ref_models.SPECIFICATIONTYPE.LONGNAMEAttr": (ref_models.SPECIFICATIONTYPE{}).LONGNAMEAttr,

	"ref_models.SPECIFICATIONTYPE.Name": (ref_models.SPECIFICATIONTYPE{}).Name,

	"ref_models.SPECIFICATIONTYPE.SPECATTRIBUTES": (ref_models.SPECIFICATIONTYPE{}).SPECATTRIBUTES,

	"ref_models.SPECIFIEDVALUES": &(ref_models.SPECIFIEDVALUES{}),

	"ref_models.SPECIFIEDVALUES.ENUMVALUE": (ref_models.SPECIFIEDVALUES{}).ENUMVALUE,

	"ref_models.SPECIFIEDVALUES.Name": (ref_models.SPECIFIEDVALUES{}).Name,

	"ref_models.SPECOBJECT": &(ref_models.SPECOBJECT{}),

	"ref_models.SPECOBJECT.ALTERNATIVEID": (ref_models.SPECOBJECT{}).ALTERNATIVEID,

	"ref_models.SPECOBJECT.DESCAttr": (ref_models.SPECOBJECT{}).DESCAttr,

	"ref_models.SPECOBJECT.IDENTIFIERAttr": (ref_models.SPECOBJECT{}).IDENTIFIERAttr,

	"ref_models.SPECOBJECT.LASTCHANGEAttr": (ref_models.SPECOBJECT{}).LASTCHANGEAttr,

	"ref_models.SPECOBJECT.LONGNAMEAttr": (ref_models.SPECOBJECT{}).LONGNAMEAttr,

	"ref_models.SPECOBJECT.Name": (ref_models.SPECOBJECT{}).Name,

	"ref_models.SPECOBJECT.TYPE": (ref_models.SPECOBJECT{}).TYPE,

	"ref_models.SPECOBJECT.VALUES": (ref_models.SPECOBJECT{}).VALUES,

	"ref_models.SPECOBJECTS": &(ref_models.SPECOBJECTS{}),

	"ref_models.SPECOBJECTS.Name": (ref_models.SPECOBJECTS{}).Name,

	"ref_models.SPECOBJECTS.SPECOBJECT": (ref_models.SPECOBJECTS{}).SPECOBJECT,

	"ref_models.SPECOBJECTTYPE": &(ref_models.SPECOBJECTTYPE{}),

	"ref_models.SPECOBJECTTYPE.ALTERNATIVEID": (ref_models.SPECOBJECTTYPE{}).ALTERNATIVEID,

	"ref_models.SPECOBJECTTYPE.DESCAttr": (ref_models.SPECOBJECTTYPE{}).DESCAttr,

	"ref_models.SPECOBJECTTYPE.IDENTIFIERAttr": (ref_models.SPECOBJECTTYPE{}).IDENTIFIERAttr,

	"ref_models.SPECOBJECTTYPE.LASTCHANGEAttr": (ref_models.SPECOBJECTTYPE{}).LASTCHANGEAttr,

	"ref_models.SPECOBJECTTYPE.LONGNAMEAttr": (ref_models.SPECOBJECTTYPE{}).LONGNAMEAttr,

	"ref_models.SPECOBJECTTYPE.Name": (ref_models.SPECOBJECTTYPE{}).Name,

	"ref_models.SPECOBJECTTYPE.SPECATTRIBUTES": (ref_models.SPECOBJECTTYPE{}).SPECATTRIBUTES,

	"ref_models.SPECRELATION": &(ref_models.SPECRELATION{}),

	"ref_models.SPECRELATION.ALTERNATIVEID": (ref_models.SPECRELATION{}).ALTERNATIVEID,

	"ref_models.SPECRELATION.DESCAttr": (ref_models.SPECRELATION{}).DESCAttr,

	"ref_models.SPECRELATION.IDENTIFIERAttr": (ref_models.SPECRELATION{}).IDENTIFIERAttr,

	"ref_models.SPECRELATION.LASTCHANGEAttr": (ref_models.SPECRELATION{}).LASTCHANGEAttr,

	"ref_models.SPECRELATION.LONGNAMEAttr": (ref_models.SPECRELATION{}).LONGNAMEAttr,

	"ref_models.SPECRELATION.Name": (ref_models.SPECRELATION{}).Name,

	"ref_models.SPECRELATION.SOURCE": (ref_models.SPECRELATION{}).SOURCE,

	"ref_models.SPECRELATION.TARGET": (ref_models.SPECRELATION{}).TARGET,

	"ref_models.SPECRELATION.TYPE": (ref_models.SPECRELATION{}).TYPE,

	"ref_models.SPECRELATION.VALUES": (ref_models.SPECRELATION{}).VALUES,

	"ref_models.SPECRELATIONGROUPS": &(ref_models.SPECRELATIONGROUPS{}),

	"ref_models.SPECRELATIONGROUPS.Name": (ref_models.SPECRELATIONGROUPS{}).Name,

	"ref_models.SPECRELATIONGROUPS.RELATIONGROUP": (ref_models.SPECRELATIONGROUPS{}).RELATIONGROUP,

	"ref_models.SPECRELATIONS": &(ref_models.SPECRELATIONS{}),

	"ref_models.SPECRELATIONS.Name": (ref_models.SPECRELATIONS{}).Name,

	"ref_models.SPECRELATIONTYPE": &(ref_models.SPECRELATIONTYPE{}),

	"ref_models.SPECRELATIONTYPE.ALTERNATIVEID": (ref_models.SPECRELATIONTYPE{}).ALTERNATIVEID,

	"ref_models.SPECRELATIONTYPE.DESCAttr": (ref_models.SPECRELATIONTYPE{}).DESCAttr,

	"ref_models.SPECRELATIONTYPE.IDENTIFIERAttr": (ref_models.SPECRELATIONTYPE{}).IDENTIFIERAttr,

	"ref_models.SPECRELATIONTYPE.LASTCHANGEAttr": (ref_models.SPECRELATIONTYPE{}).LASTCHANGEAttr,

	"ref_models.SPECRELATIONTYPE.LONGNAMEAttr": (ref_models.SPECRELATIONTYPE{}).LONGNAMEAttr,

	"ref_models.SPECRELATIONTYPE.Name": (ref_models.SPECRELATIONTYPE{}).Name,

	"ref_models.SPECRELATIONTYPE.SPECATTRIBUTES": (ref_models.SPECRELATIONTYPE{}).SPECATTRIBUTES,

	"ref_models.SPECTYPES": &(ref_models.SPECTYPES{}),

	"ref_models.SPECTYPES.Name": (ref_models.SPECTYPES{}).Name,

	"ref_models.SPECTYPES.RELATIONGROUPTYPE": (ref_models.SPECTYPES{}).RELATIONGROUPTYPE,

	"ref_models.SPECTYPES.SPECIFICATIONTYPE": (ref_models.SPECTYPES{}).SPECIFICATIONTYPE,

	"ref_models.SPECTYPES.SPECOBJECTTYPE": (ref_models.SPECTYPES{}).SPECOBJECTTYPE,

	"ref_models.SPECTYPES.SPECRELATIONTYPE": (ref_models.SPECTYPES{}).SPECRELATIONTYPE,

	"ref_models.TARGET": &(ref_models.TARGET{}),

	"ref_models.TARGET.Name": (ref_models.TARGET{}).Name,

	"ref_models.TARGET.SPECOBJECTREF": (ref_models.TARGET{}).SPECOBJECTREF,

	"ref_models.TARGETSPECIFICATION": &(ref_models.TARGETSPECIFICATION{}),

	"ref_models.TARGETSPECIFICATION.Name": (ref_models.TARGETSPECIFICATION{}).Name,

	"ref_models.TARGETSPECIFICATION.SPECIFICATIONREF": (ref_models.TARGETSPECIFICATION{}).SPECIFICATIONREF,

	"ref_models.THEHEADER": &(ref_models.THEHEADER{}),

	"ref_models.THEHEADER.Name": (ref_models.THEHEADER{}).Name,

	"ref_models.THEHEADER.REQIFHEADER": (ref_models.THEHEADER{}).REQIFHEADER,

	"ref_models.TOOLEXTENSIONS": &(ref_models.TOOLEXTENSIONS{}),

	"ref_models.TOOLEXTENSIONS.Name": (ref_models.TOOLEXTENSIONS{}).Name,

	"ref_models.TOOLEXTENSIONS.REQIFTOOLEXTENSION": (ref_models.TOOLEXTENSIONS{}).REQIFTOOLEXTENSION,

	"ref_models.VALUES": &(ref_models.VALUES{}),

	"ref_models.VALUES.Name": (ref_models.VALUES{}).Name,

	"ref_models.XHTMLCONTENT": &(ref_models.XHTMLCONTENT{}),

	"ref_models.XHTMLCONTENT.Name": (ref_models.XHTMLCONTENT{}).Name,
}

// function will stage objects
func _(stage *models.StageStruct) {

	// Declaration of instances to stage

	__Classdiagram__000000_Default_1 := (&models.Classdiagram{Name: `Default_1`}).Stage(stage)

	__Field__000000_DATATYPEDEFINITIONBOOLEANREF := (&models.Field{Name: `DATATYPEDEFINITIONBOOLEANREF`}).Stage(stage)
	__Field__000001_DESCAttr := (&models.Field{Name: `DESCAttr`}).Stage(stage)
	__Field__000002_IDENTIFIERAttr := (&models.Field{Name: `IDENTIFIERAttr`}).Stage(stage)
	__Field__000003_LASTCHANGEAttr := (&models.Field{Name: `LASTCHANGEAttr`}).Stage(stage)
	__Field__000004_LONGNAMEAttr := (&models.Field{Name: `LONGNAMEAttr`}).Stage(stage)
	__Field__000005_Name := (&models.Field{Name: `Name`}).Stage(stage)
	__Field__000006_SPECOBJECTREF := (&models.Field{Name: `SPECOBJECTREF`}).Stage(stage)

	__GongStructShape__000000_Default_1_CHILDREN := (&models.GongStructShape{Name: `Default_1-CHILDREN`}).Stage(stage)
	__GongStructShape__000001_Default_1_CORECONTENT := (&models.GongStructShape{Name: `Default_1-CORECONTENT`}).Stage(stage)
	__GongStructShape__000002_Default_1_OBJECT := (&models.GongStructShape{Name: `Default_1-OBJECT`}).Stage(stage)
	__GongStructShape__000003_Default_1_REQIF := (&models.GongStructShape{Name: `Default_1-REQIF`}).Stage(stage)
	__GongStructShape__000004_Default_1_REQIFCONTENT := (&models.GongStructShape{Name: `Default_1-REQIFCONTENT`}).Stage(stage)
	__GongStructShape__000005_Default_1_REQIFTYPE := (&models.GongStructShape{Name: `Default_1-REQIFTYPE`}).Stage(stage)
	__GongStructShape__000006_Default_1_SPECHIERARCHY := (&models.GongStructShape{Name: `Default_1-SPECHIERARCHY`}).Stage(stage)
	__GongStructShape__000007_Default_1_SPECIFICATION := (&models.GongStructShape{Name: `Default_1-SPECIFICATION`}).Stage(stage)
	__GongStructShape__000008_Default_1_SPECIFICATIONS := (&models.GongStructShape{Name: `Default_1-SPECIFICATIONS`}).Stage(stage)
	__GongStructShape__000009_Default_1_SPECOBJECT := (&models.GongStructShape{Name: `Default_1-SPECOBJECT`}).Stage(stage)
	__GongStructShape__000010_Default_1_SPECOBJECTS := (&models.GongStructShape{Name: `Default_1-SPECOBJECTS`}).Stage(stage)
	__GongStructShape__000011_Default_1_SPECOBJECTTYPE := (&models.GongStructShape{Name: `Default_1-SPECOBJECTTYPE`}).Stage(stage)
	__GongStructShape__000012_Default_1_THEHEADER := (&models.GongStructShape{Name: `Default_1-THEHEADER`}).Stage(stage)
	__GongStructShape__000013_Default_1_VALUES := (&models.GongStructShape{Name: `Default_1-VALUES`}).Stage(stage)

	__Link__000000_CHILDREN := (&models.Link{Name: `CHILDREN`}).Stage(stage)
	__Link__000001_CHILDREN := (&models.Link{Name: `CHILDREN`}).Stage(stage)
	__Link__000002_CORECONTENT := (&models.Link{Name: `CORECONTENT`}).Stage(stage)
	__Link__000003_HEADER := (&models.Link{Name: `HEADER`}).Stage(stage)
	__Link__000004_OBJECT := (&models.Link{Name: `OBJECT`}).Stage(stage)
	__Link__000005_REQIFCONTENT := (&models.Link{Name: `REQIFCONTENT`}).Stage(stage)
	__Link__000006_SPECHIERARCHY := (&models.Link{Name: `SPECHIERARCHY`}).Stage(stage)
	__Link__000007_SPECIFICATION := (&models.Link{Name: `SPECIFICATION`}).Stage(stage)
	__Link__000008_SPECIFICATIONS := (&models.Link{Name: `SPECIFICATIONS`}).Stage(stage)
	__Link__000009_SPECOBJECT := (&models.Link{Name: `SPECOBJECT`}).Stage(stage)
	__Link__000010_SPECOBJECTS := (&models.Link{Name: `SPECOBJECTS`}).Stage(stage)
	__Link__000011_TYPE := (&models.Link{Name: `TYPE`}).Stage(stage)
	__Link__000012_VALUES := (&models.Link{Name: `VALUES`}).Stage(stage)
	__Link__000013_VALUES := (&models.Link{Name: `VALUES`}).Stage(stage)

	__Position__000000_Pos_Default_1_CHILDREN := (&models.Position{Name: `Pos-Default_1-CHILDREN`}).Stage(stage)
	__Position__000001_Pos_Default_1_CORECONTENT := (&models.Position{Name: `Pos-Default_1-CORECONTENT`}).Stage(stage)
	__Position__000002_Pos_Default_1_OBJECT := (&models.Position{Name: `Pos-Default_1-OBJECT`}).Stage(stage)
	__Position__000003_Pos_Default_1_REQIF := (&models.Position{Name: `Pos-Default_1-REQIF`}).Stage(stage)
	__Position__000004_Pos_Default_1_REQIFCONTENT := (&models.Position{Name: `Pos-Default_1-REQIFCONTENT`}).Stage(stage)
	__Position__000005_Pos_Default_1_REQIFTYPE := (&models.Position{Name: `Pos-Default_1-REQIFTYPE`}).Stage(stage)
	__Position__000006_Pos_Default_1_SPECHIERARCHY := (&models.Position{Name: `Pos-Default_1-SPECHIERARCHY`}).Stage(stage)
	__Position__000007_Pos_Default_1_SPECIFICATION := (&models.Position{Name: `Pos-Default_1-SPECIFICATION`}).Stage(stage)
	__Position__000008_Pos_Default_1_SPECIFICATIONS := (&models.Position{Name: `Pos-Default_1-SPECIFICATIONS`}).Stage(stage)
	__Position__000009_Pos_Default_1_SPECOBJECT := (&models.Position{Name: `Pos-Default_1-SPECOBJECT`}).Stage(stage)
	__Position__000010_Pos_Default_1_SPECOBJECTS := (&models.Position{Name: `Pos-Default_1-SPECOBJECTS`}).Stage(stage)
	__Position__000011_Pos_Default_1_SPECOBJECTTYPE := (&models.Position{Name: `Pos-Default_1-SPECOBJECTTYPE`}).Stage(stage)
	__Position__000012_Pos_Default_1_THEHEADER := (&models.Position{Name: `Pos-Default_1-THEHEADER`}).Stage(stage)
	__Position__000013_Pos_Default_1_VALUES := (&models.Position{Name: `Pos-Default_1-VALUES`}).Stage(stage)

	__Vertice__000000_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_CHILDREN_and_Default_1_SPECHIERARCHY := (&models.Vertice{Name: `Verticle in class diagram Default_1 in middle between Default_1-CHILDREN and Default_1-SPECHIERARCHY`}).Stage(stage)
	__Vertice__000001_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_CORECONTENT_and_Default_1_REQIFCONTENT := (&models.Vertice{Name: `Verticle in class diagram Default_1 in middle between Default_1-CORECONTENT and Default_1-REQIFCONTENT`}).Stage(stage)
	__Vertice__000002_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_REQIF_and_Default_1_CORECONTENT := (&models.Vertice{Name: `Verticle in class diagram Default_1 in middle between Default_1-REQIF and Default_1-CORECONTENT`}).Stage(stage)
	__Vertice__000003_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_REQIF_and_Default_1_THEHEADER := (&models.Vertice{Name: `Verticle in class diagram Default_1 in middle between Default_1-REQIF and Default_1-THEHEADER`}).Stage(stage)
	__Vertice__000004_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_REQIFCONTENT_and_Default_1_SPECIFICATIONS := (&models.Vertice{Name: `Verticle in class diagram Default_1 in middle between Default_1-REQIFCONTENT and Default_1-SPECIFICATIONS`}).Stage(stage)
	__Vertice__000005_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_REQIFCONTENT_and_Default_1_SPECOBJECTS := (&models.Vertice{Name: `Verticle in class diagram Default_1 in middle between Default_1-REQIFCONTENT and Default_1-SPECOBJECTS`}).Stage(stage)
	__Vertice__000006_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_SPECHIERARCHY_and_Default_1_CHILDREN := (&models.Vertice{Name: `Verticle in class diagram Default_1 in middle between Default_1-SPECHIERARCHY and Default_1-CHILDREN`}).Stage(stage)
	__Vertice__000007_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_SPECHIERARCHY_and_Default_1_OBJECT := (&models.Vertice{Name: `Verticle in class diagram Default_1 in middle between Default_1-SPECHIERARCHY and Default_1-OBJECT`}).Stage(stage)
	__Vertice__000008_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_SPECIFICATION_and_Default_1_CHILDREN := (&models.Vertice{Name: `Verticle in class diagram Default_1 in middle between Default_1-SPECIFICATION and Default_1-CHILDREN`}).Stage(stage)
	__Vertice__000009_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_SPECIFICATION_and_Default_1_VALUES := (&models.Vertice{Name: `Verticle in class diagram Default_1 in middle between Default_1-SPECIFICATION and Default_1-VALUES`}).Stage(stage)
	__Vertice__000010_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_SPECIFICATIONS_and_Default_1_SPECIFICATION := (&models.Vertice{Name: `Verticle in class diagram Default_1 in middle between Default_1-SPECIFICATIONS and Default_1-SPECIFICATION`}).Stage(stage)
	__Vertice__000011_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_SPECOBJECT_and_Default_1_REQIFTYPE := (&models.Vertice{Name: `Verticle in class diagram Default_1 in middle between Default_1-SPECOBJECT and Default_1-REQIFTYPE`}).Stage(stage)
	__Vertice__000012_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_SPECOBJECT_and_Default_1_VALUES := (&models.Vertice{Name: `Verticle in class diagram Default_1 in middle between Default_1-SPECOBJECT and Default_1-VALUES`}).Stage(stage)
	__Vertice__000013_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_SPECOBJECTS_and_Default_1_SPECOBJECT := (&models.Vertice{Name: `Verticle in class diagram Default_1 in middle between Default_1-SPECOBJECTS and Default_1-SPECOBJECT`}).Stage(stage)

	// Setup of values

	__Classdiagram__000000_Default_1.Name = `Default_1`
	__Classdiagram__000000_Default_1.IsInDrawMode = false

	__Field__000000_DATATYPEDEFINITIONBOOLEANREF.Name = `DATATYPEDEFINITIONBOOLEANREF`

	//gong:ident [ref_models.REQIFTYPE.DATATYPEDEFINITIONBOOLEANREF] comment added to overcome the problem with the comment map association
	__Field__000000_DATATYPEDEFINITIONBOOLEANREF.Identifier = `ref_models.REQIFTYPE.DATATYPEDEFINITIONBOOLEANREF`
	__Field__000000_DATATYPEDEFINITIONBOOLEANREF.FieldTypeAsString = ``
	__Field__000000_DATATYPEDEFINITIONBOOLEANREF.Structname = `REQIFTYPE`
	__Field__000000_DATATYPEDEFINITIONBOOLEANREF.Fieldtypename = `string`

	__Field__000001_DESCAttr.Name = `DESCAttr`

	//gong:ident [ref_models.SPECIFICATION.DESCAttr] comment added to overcome the problem with the comment map association
	__Field__000001_DESCAttr.Identifier = `ref_models.SPECIFICATION.DESCAttr`
	__Field__000001_DESCAttr.FieldTypeAsString = ``
	__Field__000001_DESCAttr.Structname = `SPECIFICATION`
	__Field__000001_DESCAttr.Fieldtypename = `string`

	__Field__000002_IDENTIFIERAttr.Name = `IDENTIFIERAttr`

	//gong:ident [ref_models.SPECIFICATION.IDENTIFIERAttr] comment added to overcome the problem with the comment map association
	__Field__000002_IDENTIFIERAttr.Identifier = `ref_models.SPECIFICATION.IDENTIFIERAttr`
	__Field__000002_IDENTIFIERAttr.FieldTypeAsString = ``
	__Field__000002_IDENTIFIERAttr.Structname = `SPECIFICATION`
	__Field__000002_IDENTIFIERAttr.Fieldtypename = `string`

	__Field__000003_LASTCHANGEAttr.Name = `LASTCHANGEAttr`

	//gong:ident [ref_models.SPECIFICATION.LASTCHANGEAttr] comment added to overcome the problem with the comment map association
	__Field__000003_LASTCHANGEAttr.Identifier = `ref_models.SPECIFICATION.LASTCHANGEAttr`
	__Field__000003_LASTCHANGEAttr.FieldTypeAsString = ``
	__Field__000003_LASTCHANGEAttr.Structname = `SPECIFICATION`
	__Field__000003_LASTCHANGEAttr.Fieldtypename = `string`

	__Field__000004_LONGNAMEAttr.Name = `LONGNAMEAttr`

	//gong:ident [ref_models.SPECIFICATION.LONGNAMEAttr] comment added to overcome the problem with the comment map association
	__Field__000004_LONGNAMEAttr.Identifier = `ref_models.SPECIFICATION.LONGNAMEAttr`
	__Field__000004_LONGNAMEAttr.FieldTypeAsString = ``
	__Field__000004_LONGNAMEAttr.Structname = `SPECIFICATION`
	__Field__000004_LONGNAMEAttr.Fieldtypename = `string`

	__Field__000005_Name.Name = `Name`

	//gong:ident [ref_models.OBJECT.Name] comment added to overcome the problem with the comment map association
	__Field__000005_Name.Identifier = `ref_models.OBJECT.Name`
	__Field__000005_Name.FieldTypeAsString = ``
	__Field__000005_Name.Structname = `OBJECT`
	__Field__000005_Name.Fieldtypename = `string`

	__Field__000006_SPECOBJECTREF.Name = `SPECOBJECTREF`

	//gong:ident [ref_models.OBJECT.SPECOBJECTREF] comment added to overcome the problem with the comment map association
	__Field__000006_SPECOBJECTREF.Identifier = `ref_models.OBJECT.SPECOBJECTREF`
	__Field__000006_SPECOBJECTREF.FieldTypeAsString = ``
	__Field__000006_SPECOBJECTREF.Structname = `OBJECT`
	__Field__000006_SPECOBJECTREF.Fieldtypename = `string`

	__GongStructShape__000000_Default_1_CHILDREN.Name = `Default_1-CHILDREN`

	//gong:ident [ref_models.CHILDREN] comment added to overcome the problem with the comment map association
	__GongStructShape__000000_Default_1_CHILDREN.Identifier = `ref_models.CHILDREN`
	__GongStructShape__000000_Default_1_CHILDREN.ShowNbInstances = false
	__GongStructShape__000000_Default_1_CHILDREN.NbInstances = 0
	__GongStructShape__000000_Default_1_CHILDREN.Width = 240.000000
	__GongStructShape__000000_Default_1_CHILDREN.Height = 63.000000
	__GongStructShape__000000_Default_1_CHILDREN.IsSelected = false

	__GongStructShape__000001_Default_1_CORECONTENT.Name = `Default_1-CORECONTENT`

	//gong:ident [ref_models.CORECONTENT] comment added to overcome the problem with the comment map association
	__GongStructShape__000001_Default_1_CORECONTENT.Identifier = `ref_models.CORECONTENT`
	__GongStructShape__000001_Default_1_CORECONTENT.ShowNbInstances = false
	__GongStructShape__000001_Default_1_CORECONTENT.NbInstances = 0
	__GongStructShape__000001_Default_1_CORECONTENT.Width = 240.000000
	__GongStructShape__000001_Default_1_CORECONTENT.Height = 63.000000
	__GongStructShape__000001_Default_1_CORECONTENT.IsSelected = false

	__GongStructShape__000002_Default_1_OBJECT.Name = `Default_1-OBJECT`

	//gong:ident [ref_models.OBJECT] comment added to overcome the problem with the comment map association
	__GongStructShape__000002_Default_1_OBJECT.Identifier = `ref_models.OBJECT`
	__GongStructShape__000002_Default_1_OBJECT.ShowNbInstances = false
	__GongStructShape__000002_Default_1_OBJECT.NbInstances = 0
	__GongStructShape__000002_Default_1_OBJECT.Width = 240.000000
	__GongStructShape__000002_Default_1_OBJECT.Height = 93.000000
	__GongStructShape__000002_Default_1_OBJECT.IsSelected = false

	__GongStructShape__000003_Default_1_REQIF.Name = `Default_1-REQIF`

	//gong:ident [ref_models.REQIF] comment added to overcome the problem with the comment map association
	__GongStructShape__000003_Default_1_REQIF.Identifier = `ref_models.REQIF`
	__GongStructShape__000003_Default_1_REQIF.ShowNbInstances = false
	__GongStructShape__000003_Default_1_REQIF.NbInstances = 0
	__GongStructShape__000003_Default_1_REQIF.Width = 240.000000
	__GongStructShape__000003_Default_1_REQIF.Height = 63.000000
	__GongStructShape__000003_Default_1_REQIF.IsSelected = false

	__GongStructShape__000004_Default_1_REQIFCONTENT.Name = `Default_1-REQIFCONTENT`

	//gong:ident [ref_models.REQIFCONTENT] comment added to overcome the problem with the comment map association
	__GongStructShape__000004_Default_1_REQIFCONTENT.Identifier = `ref_models.REQIFCONTENT`
	__GongStructShape__000004_Default_1_REQIFCONTENT.ShowNbInstances = false
	__GongStructShape__000004_Default_1_REQIFCONTENT.NbInstances = 0
	__GongStructShape__000004_Default_1_REQIFCONTENT.Width = 240.000000
	__GongStructShape__000004_Default_1_REQIFCONTENT.Height = 63.000000
	__GongStructShape__000004_Default_1_REQIFCONTENT.IsSelected = false

	__GongStructShape__000005_Default_1_REQIFTYPE.Name = `Default_1-REQIFTYPE`

	//gong:ident [ref_models.REQIFTYPE] comment added to overcome the problem with the comment map association
	__GongStructShape__000005_Default_1_REQIFTYPE.Identifier = `ref_models.REQIFTYPE`
	__GongStructShape__000005_Default_1_REQIFTYPE.ShowNbInstances = false
	__GongStructShape__000005_Default_1_REQIFTYPE.NbInstances = 0
	__GongStructShape__000005_Default_1_REQIFTYPE.Width = 240.000000
	__GongStructShape__000005_Default_1_REQIFTYPE.Height = 78.000000
	__GongStructShape__000005_Default_1_REQIFTYPE.IsSelected = false

	__GongStructShape__000006_Default_1_SPECHIERARCHY.Name = `Default_1-SPECHIERARCHY`

	//gong:ident [ref_models.SPECHIERARCHY] comment added to overcome the problem with the comment map association
	__GongStructShape__000006_Default_1_SPECHIERARCHY.Identifier = `ref_models.SPECHIERARCHY`
	__GongStructShape__000006_Default_1_SPECHIERARCHY.ShowNbInstances = false
	__GongStructShape__000006_Default_1_SPECHIERARCHY.NbInstances = 0
	__GongStructShape__000006_Default_1_SPECHIERARCHY.Width = 240.000000
	__GongStructShape__000006_Default_1_SPECHIERARCHY.Height = 63.000000
	__GongStructShape__000006_Default_1_SPECHIERARCHY.IsSelected = false

	__GongStructShape__000007_Default_1_SPECIFICATION.Name = `Default_1-SPECIFICATION`

	//gong:ident [ref_models.SPECIFICATION] comment added to overcome the problem with the comment map association
	__GongStructShape__000007_Default_1_SPECIFICATION.Identifier = `ref_models.SPECIFICATION`
	__GongStructShape__000007_Default_1_SPECIFICATION.ShowNbInstances = false
	__GongStructShape__000007_Default_1_SPECIFICATION.NbInstances = 0
	__GongStructShape__000007_Default_1_SPECIFICATION.Width = 240.000000
	__GongStructShape__000007_Default_1_SPECIFICATION.Height = 123.000000
	__GongStructShape__000007_Default_1_SPECIFICATION.IsSelected = false

	__GongStructShape__000008_Default_1_SPECIFICATIONS.Name = `Default_1-SPECIFICATIONS`

	//gong:ident [ref_models.SPECIFICATIONS] comment added to overcome the problem with the comment map association
	__GongStructShape__000008_Default_1_SPECIFICATIONS.Identifier = `ref_models.SPECIFICATIONS`
	__GongStructShape__000008_Default_1_SPECIFICATIONS.ShowNbInstances = false
	__GongStructShape__000008_Default_1_SPECIFICATIONS.NbInstances = 0
	__GongStructShape__000008_Default_1_SPECIFICATIONS.Width = 240.000000
	__GongStructShape__000008_Default_1_SPECIFICATIONS.Height = 63.000000
	__GongStructShape__000008_Default_1_SPECIFICATIONS.IsSelected = false

	__GongStructShape__000009_Default_1_SPECOBJECT.Name = `Default_1-SPECOBJECT`

	//gong:ident [ref_models.SPECOBJECT] comment added to overcome the problem with the comment map association
	__GongStructShape__000009_Default_1_SPECOBJECT.Identifier = `ref_models.SPECOBJECT`
	__GongStructShape__000009_Default_1_SPECOBJECT.ShowNbInstances = false
	__GongStructShape__000009_Default_1_SPECOBJECT.NbInstances = 0
	__GongStructShape__000009_Default_1_SPECOBJECT.Width = 240.000000
	__GongStructShape__000009_Default_1_SPECOBJECT.Height = 63.000000
	__GongStructShape__000009_Default_1_SPECOBJECT.IsSelected = false

	__GongStructShape__000010_Default_1_SPECOBJECTS.Name = `Default_1-SPECOBJECTS`

	//gong:ident [ref_models.SPECOBJECTS] comment added to overcome the problem with the comment map association
	__GongStructShape__000010_Default_1_SPECOBJECTS.Identifier = `ref_models.SPECOBJECTS`
	__GongStructShape__000010_Default_1_SPECOBJECTS.ShowNbInstances = false
	__GongStructShape__000010_Default_1_SPECOBJECTS.NbInstances = 0
	__GongStructShape__000010_Default_1_SPECOBJECTS.Width = 240.000000
	__GongStructShape__000010_Default_1_SPECOBJECTS.Height = 63.000000
	__GongStructShape__000010_Default_1_SPECOBJECTS.IsSelected = false

	__GongStructShape__000011_Default_1_SPECOBJECTTYPE.Name = `Default_1-SPECOBJECTTYPE`

	//gong:ident [ref_models.SPECOBJECTTYPE] comment added to overcome the problem with the comment map association
	__GongStructShape__000011_Default_1_SPECOBJECTTYPE.Identifier = `ref_models.SPECOBJECTTYPE`
	__GongStructShape__000011_Default_1_SPECOBJECTTYPE.ShowNbInstances = false
	__GongStructShape__000011_Default_1_SPECOBJECTTYPE.NbInstances = 0
	__GongStructShape__000011_Default_1_SPECOBJECTTYPE.Width = 240.000000
	__GongStructShape__000011_Default_1_SPECOBJECTTYPE.Height = 63.000000
	__GongStructShape__000011_Default_1_SPECOBJECTTYPE.IsSelected = false

	__GongStructShape__000012_Default_1_THEHEADER.Name = `Default_1-THEHEADER`

	//gong:ident [ref_models.THEHEADER] comment added to overcome the problem with the comment map association
	__GongStructShape__000012_Default_1_THEHEADER.Identifier = `ref_models.THEHEADER`
	__GongStructShape__000012_Default_1_THEHEADER.ShowNbInstances = false
	__GongStructShape__000012_Default_1_THEHEADER.NbInstances = 0
	__GongStructShape__000012_Default_1_THEHEADER.Width = 240.000000
	__GongStructShape__000012_Default_1_THEHEADER.Height = 63.000000
	__GongStructShape__000012_Default_1_THEHEADER.IsSelected = false

	__GongStructShape__000013_Default_1_VALUES.Name = `Default_1-VALUES`

	//gong:ident [ref_models.VALUES] comment added to overcome the problem with the comment map association
	__GongStructShape__000013_Default_1_VALUES.Identifier = `ref_models.VALUES`
	__GongStructShape__000013_Default_1_VALUES.ShowNbInstances = false
	__GongStructShape__000013_Default_1_VALUES.NbInstances = 0
	__GongStructShape__000013_Default_1_VALUES.Width = 240.000000
	__GongStructShape__000013_Default_1_VALUES.Height = 63.000000
	__GongStructShape__000013_Default_1_VALUES.IsSelected = false

	__Link__000000_CHILDREN.Name = `CHILDREN`

	//gong:ident [ref_models.SPECHIERARCHY.CHILDREN] comment added to overcome the problem with the comment map association
	__Link__000000_CHILDREN.Identifier = `ref_models.SPECHIERARCHY.CHILDREN`

	//gong:ident [ref_models.CHILDREN] comment added to overcome the problem with the comment map association
	__Link__000000_CHILDREN.Fieldtypename = `ref_models.CHILDREN`
	__Link__000000_CHILDREN.FieldOffsetX = -50.000000
	__Link__000000_CHILDREN.FieldOffsetY = -16.000000
	__Link__000000_CHILDREN.TargetMultiplicity = models.ZERO_ONE
	__Link__000000_CHILDREN.TargetMultiplicityOffsetX = -50.000000
	__Link__000000_CHILDREN.TargetMultiplicityOffsetY = 16.000000
	__Link__000000_CHILDREN.SourceMultiplicity = models.MANY
	__Link__000000_CHILDREN.SourceMultiplicityOffsetX = 10.000000
	__Link__000000_CHILDREN.SourceMultiplicityOffsetY = -50.000000
	__Link__000000_CHILDREN.StartOrientation = models.ORIENTATION_VERTICAL
	__Link__000000_CHILDREN.StartRatio = 0.296806
	__Link__000000_CHILDREN.EndOrientation = models.ORIENTATION_HORIZONTAL
	__Link__000000_CHILDREN.EndRatio = 0.520109
	__Link__000000_CHILDREN.CornerOffsetRatio = 1.154167

	__Link__000001_CHILDREN.Name = `CHILDREN`

	//gong:ident [ref_models.SPECIFICATION.CHILDREN] comment added to overcome the problem with the comment map association
	__Link__000001_CHILDREN.Identifier = `ref_models.SPECIFICATION.CHILDREN`

	//gong:ident [ref_models.CHILDREN] comment added to overcome the problem with the comment map association
	__Link__000001_CHILDREN.Fieldtypename = `ref_models.CHILDREN`
	__Link__000001_CHILDREN.FieldOffsetX = -50.000000
	__Link__000001_CHILDREN.FieldOffsetY = -16.000000
	__Link__000001_CHILDREN.TargetMultiplicity = models.ZERO_ONE
	__Link__000001_CHILDREN.TargetMultiplicityOffsetX = -50.000000
	__Link__000001_CHILDREN.TargetMultiplicityOffsetY = 16.000000
	__Link__000001_CHILDREN.SourceMultiplicity = models.MANY
	__Link__000001_CHILDREN.SourceMultiplicityOffsetX = 10.000000
	__Link__000001_CHILDREN.SourceMultiplicityOffsetY = -50.000000
	__Link__000001_CHILDREN.StartOrientation = models.ORIENTATION_HORIZONTAL
	__Link__000001_CHILDREN.StartRatio = 0.500000
	__Link__000001_CHILDREN.EndOrientation = models.ORIENTATION_VERTICAL
	__Link__000001_CHILDREN.EndRatio = 0.605139
	__Link__000001_CHILDREN.CornerOffsetRatio = 2.274527

	__Link__000002_CORECONTENT.Name = `CORECONTENT`

	//gong:ident [ref_models.REQIF.CORECONTENT] comment added to overcome the problem with the comment map association
	__Link__000002_CORECONTENT.Identifier = `ref_models.REQIF.CORECONTENT`

	//gong:ident [ref_models.CORECONTENT] comment added to overcome the problem with the comment map association
	__Link__000002_CORECONTENT.Fieldtypename = `ref_models.CORECONTENT`
	__Link__000002_CORECONTENT.FieldOffsetX = -50.000000
	__Link__000002_CORECONTENT.FieldOffsetY = -16.000000
	__Link__000002_CORECONTENT.TargetMultiplicity = models.ZERO_ONE
	__Link__000002_CORECONTENT.TargetMultiplicityOffsetX = -50.000000
	__Link__000002_CORECONTENT.TargetMultiplicityOffsetY = 16.000000
	__Link__000002_CORECONTENT.SourceMultiplicity = models.MANY
	__Link__000002_CORECONTENT.SourceMultiplicityOffsetX = 10.000000
	__Link__000002_CORECONTENT.SourceMultiplicityOffsetY = -50.000000
	__Link__000002_CORECONTENT.StartOrientation = models.ORIENTATION_HORIZONTAL
	__Link__000002_CORECONTENT.StartRatio = 0.500000
	__Link__000002_CORECONTENT.EndOrientation = models.ORIENTATION_HORIZONTAL
	__Link__000002_CORECONTENT.EndRatio = 0.500000
	__Link__000002_CORECONTENT.CornerOffsetRatio = 1.380000

	__Link__000003_HEADER.Name = `HEADER`

	//gong:ident [ref_models.REQIF.HEADER] comment added to overcome the problem with the comment map association
	__Link__000003_HEADER.Identifier = `ref_models.REQIF.HEADER`

	//gong:ident [ref_models.THEHEADER] comment added to overcome the problem with the comment map association
	__Link__000003_HEADER.Fieldtypename = `ref_models.THEHEADER`
	__Link__000003_HEADER.FieldOffsetX = -50.000000
	__Link__000003_HEADER.FieldOffsetY = -16.000000
	__Link__000003_HEADER.TargetMultiplicity = models.ZERO_ONE
	__Link__000003_HEADER.TargetMultiplicityOffsetX = -50.000000
	__Link__000003_HEADER.TargetMultiplicityOffsetY = 16.000000
	__Link__000003_HEADER.SourceMultiplicity = models.MANY
	__Link__000003_HEADER.SourceMultiplicityOffsetX = 10.000000
	__Link__000003_HEADER.SourceMultiplicityOffsetY = -50.000000
	__Link__000003_HEADER.StartOrientation = models.ORIENTATION_HORIZONTAL
	__Link__000003_HEADER.StartRatio = 0.500000
	__Link__000003_HEADER.EndOrientation = models.ORIENTATION_HORIZONTAL
	__Link__000003_HEADER.EndRatio = 0.500000
	__Link__000003_HEADER.CornerOffsetRatio = 1.380000

	__Link__000004_OBJECT.Name = `OBJECT`

	//gong:ident [ref_models.SPECHIERARCHY.OBJECT] comment added to overcome the problem with the comment map association
	__Link__000004_OBJECT.Identifier = `ref_models.SPECHIERARCHY.OBJECT`

	//gong:ident [ref_models.OBJECT] comment added to overcome the problem with the comment map association
	__Link__000004_OBJECT.Fieldtypename = `ref_models.OBJECT`
	__Link__000004_OBJECT.FieldOffsetX = -50.000000
	__Link__000004_OBJECT.FieldOffsetY = -16.000000
	__Link__000004_OBJECT.TargetMultiplicity = models.ZERO_ONE
	__Link__000004_OBJECT.TargetMultiplicityOffsetX = -50.000000
	__Link__000004_OBJECT.TargetMultiplicityOffsetY = 16.000000
	__Link__000004_OBJECT.SourceMultiplicity = models.MANY
	__Link__000004_OBJECT.SourceMultiplicityOffsetX = 10.000000
	__Link__000004_OBJECT.SourceMultiplicityOffsetY = -50.000000
	__Link__000004_OBJECT.StartOrientation = models.ORIENTATION_HORIZONTAL
	__Link__000004_OBJECT.StartRatio = 0.500000
	__Link__000004_OBJECT.EndOrientation = models.ORIENTATION_HORIZONTAL
	__Link__000004_OBJECT.EndRatio = 0.390145
	__Link__000004_OBJECT.CornerOffsetRatio = -0.390694

	__Link__000005_REQIFCONTENT.Name = `REQIFCONTENT`

	//gong:ident [ref_models.CORECONTENT.REQIFCONTENT] comment added to overcome the problem with the comment map association
	__Link__000005_REQIFCONTENT.Identifier = `ref_models.CORECONTENT.REQIFCONTENT`

	//gong:ident [ref_models.REQIFCONTENT] comment added to overcome the problem with the comment map association
	__Link__000005_REQIFCONTENT.Fieldtypename = `ref_models.REQIFCONTENT`
	__Link__000005_REQIFCONTENT.FieldOffsetX = -50.000000
	__Link__000005_REQIFCONTENT.FieldOffsetY = -16.000000
	__Link__000005_REQIFCONTENT.TargetMultiplicity = models.ZERO_ONE
	__Link__000005_REQIFCONTENT.TargetMultiplicityOffsetX = -50.000000
	__Link__000005_REQIFCONTENT.TargetMultiplicityOffsetY = 16.000000
	__Link__000005_REQIFCONTENT.SourceMultiplicity = models.MANY
	__Link__000005_REQIFCONTENT.SourceMultiplicityOffsetX = 10.000000
	__Link__000005_REQIFCONTENT.SourceMultiplicityOffsetY = -50.000000
	__Link__000005_REQIFCONTENT.StartOrientation = models.ORIENTATION_HORIZONTAL
	__Link__000005_REQIFCONTENT.StartRatio = 0.500000
	__Link__000005_REQIFCONTENT.EndOrientation = models.ORIENTATION_HORIZONTAL
	__Link__000005_REQIFCONTENT.EndRatio = 0.500000
	__Link__000005_REQIFCONTENT.CornerOffsetRatio = 1.380000

	__Link__000006_SPECHIERARCHY.Name = `SPECHIERARCHY`

	//gong:ident [ref_models.CHILDREN.SPECHIERARCHY] comment added to overcome the problem with the comment map association
	__Link__000006_SPECHIERARCHY.Identifier = `ref_models.CHILDREN.SPECHIERARCHY`

	//gong:ident [ref_models.SPECHIERARCHY] comment added to overcome the problem with the comment map association
	__Link__000006_SPECHIERARCHY.Fieldtypename = `ref_models.SPECHIERARCHY`
	__Link__000006_SPECHIERARCHY.FieldOffsetX = -50.000000
	__Link__000006_SPECHIERARCHY.FieldOffsetY = -16.000000
	__Link__000006_SPECHIERARCHY.TargetMultiplicity = models.MANY
	__Link__000006_SPECHIERARCHY.TargetMultiplicityOffsetX = -50.000000
	__Link__000006_SPECHIERARCHY.TargetMultiplicityOffsetY = 16.000000
	__Link__000006_SPECHIERARCHY.SourceMultiplicity = models.MANY
	__Link__000006_SPECHIERARCHY.SourceMultiplicityOffsetX = 10.000000
	__Link__000006_SPECHIERARCHY.SourceMultiplicityOffsetY = -50.000000
	__Link__000006_SPECHIERARCHY.StartOrientation = models.ORIENTATION_HORIZONTAL
	__Link__000006_SPECHIERARCHY.StartRatio = 0.500000
	__Link__000006_SPECHIERARCHY.EndOrientation = models.ORIENTATION_HORIZONTAL
	__Link__000006_SPECHIERARCHY.EndRatio = 0.500000
	__Link__000006_SPECHIERARCHY.CornerOffsetRatio = 1.380000

	__Link__000007_SPECIFICATION.Name = `SPECIFICATION`

	//gong:ident [ref_models.SPECIFICATIONS.SPECIFICATION] comment added to overcome the problem with the comment map association
	__Link__000007_SPECIFICATION.Identifier = `ref_models.SPECIFICATIONS.SPECIFICATION`

	//gong:ident [ref_models.SPECIFICATION] comment added to overcome the problem with the comment map association
	__Link__000007_SPECIFICATION.Fieldtypename = `ref_models.SPECIFICATION`
	__Link__000007_SPECIFICATION.FieldOffsetX = -50.000000
	__Link__000007_SPECIFICATION.FieldOffsetY = -16.000000
	__Link__000007_SPECIFICATION.TargetMultiplicity = models.MANY
	__Link__000007_SPECIFICATION.TargetMultiplicityOffsetX = -50.000000
	__Link__000007_SPECIFICATION.TargetMultiplicityOffsetY = 16.000000
	__Link__000007_SPECIFICATION.SourceMultiplicity = models.MANY
	__Link__000007_SPECIFICATION.SourceMultiplicityOffsetX = 10.000000
	__Link__000007_SPECIFICATION.SourceMultiplicityOffsetY = -50.000000
	__Link__000007_SPECIFICATION.StartOrientation = models.ORIENTATION_HORIZONTAL
	__Link__000007_SPECIFICATION.StartRatio = 0.500000
	__Link__000007_SPECIFICATION.EndOrientation = models.ORIENTATION_HORIZONTAL
	__Link__000007_SPECIFICATION.EndRatio = 0.500000
	__Link__000007_SPECIFICATION.CornerOffsetRatio = 1.380000

	__Link__000008_SPECIFICATIONS.Name = `SPECIFICATIONS`

	//gong:ident [ref_models.REQIFCONTENT.SPECIFICATIONS] comment added to overcome the problem with the comment map association
	__Link__000008_SPECIFICATIONS.Identifier = `ref_models.REQIFCONTENT.SPECIFICATIONS`

	//gong:ident [ref_models.SPECIFICATIONS] comment added to overcome the problem with the comment map association
	__Link__000008_SPECIFICATIONS.Fieldtypename = `ref_models.SPECIFICATIONS`
	__Link__000008_SPECIFICATIONS.FieldOffsetX = -50.000000
	__Link__000008_SPECIFICATIONS.FieldOffsetY = -16.000000
	__Link__000008_SPECIFICATIONS.TargetMultiplicity = models.ZERO_ONE
	__Link__000008_SPECIFICATIONS.TargetMultiplicityOffsetX = -50.000000
	__Link__000008_SPECIFICATIONS.TargetMultiplicityOffsetY = 16.000000
	__Link__000008_SPECIFICATIONS.SourceMultiplicity = models.MANY
	__Link__000008_SPECIFICATIONS.SourceMultiplicityOffsetX = 10.000000
	__Link__000008_SPECIFICATIONS.SourceMultiplicityOffsetY = -50.000000
	__Link__000008_SPECIFICATIONS.StartOrientation = models.ORIENTATION_VERTICAL
	__Link__000008_SPECIFICATIONS.StartRatio = 0.571806
	__Link__000008_SPECIFICATIONS.EndOrientation = models.ORIENTATION_VERTICAL
	__Link__000008_SPECIFICATIONS.EndRatio = 0.513472
	__Link__000008_SPECIFICATIONS.CornerOffsetRatio = 2.386506

	__Link__000009_SPECOBJECT.Name = `SPECOBJECT`

	//gong:ident [ref_models.SPECOBJECTS.SPECOBJECT] comment added to overcome the problem with the comment map association
	__Link__000009_SPECOBJECT.Identifier = `ref_models.SPECOBJECTS.SPECOBJECT`

	//gong:ident [ref_models.SPECOBJECT] comment added to overcome the problem with the comment map association
	__Link__000009_SPECOBJECT.Fieldtypename = `ref_models.SPECOBJECT`
	__Link__000009_SPECOBJECT.FieldOffsetX = -50.000000
	__Link__000009_SPECOBJECT.FieldOffsetY = -16.000000
	__Link__000009_SPECOBJECT.TargetMultiplicity = models.MANY
	__Link__000009_SPECOBJECT.TargetMultiplicityOffsetX = -50.000000
	__Link__000009_SPECOBJECT.TargetMultiplicityOffsetY = 16.000000
	__Link__000009_SPECOBJECT.SourceMultiplicity = models.MANY
	__Link__000009_SPECOBJECT.SourceMultiplicityOffsetX = 10.000000
	__Link__000009_SPECOBJECT.SourceMultiplicityOffsetY = -50.000000
	__Link__000009_SPECOBJECT.StartOrientation = models.ORIENTATION_HORIZONTAL
	__Link__000009_SPECOBJECT.StartRatio = 0.500000
	__Link__000009_SPECOBJECT.EndOrientation = models.ORIENTATION_HORIZONTAL
	__Link__000009_SPECOBJECT.EndRatio = 0.500000
	__Link__000009_SPECOBJECT.CornerOffsetRatio = 1.380000

	__Link__000010_SPECOBJECTS.Name = `SPECOBJECTS`

	//gong:ident [ref_models.REQIFCONTENT.SPECOBJECTS] comment added to overcome the problem with the comment map association
	__Link__000010_SPECOBJECTS.Identifier = `ref_models.REQIFCONTENT.SPECOBJECTS`

	//gong:ident [ref_models.SPECOBJECTS] comment added to overcome the problem with the comment map association
	__Link__000010_SPECOBJECTS.Fieldtypename = `ref_models.SPECOBJECTS`
	__Link__000010_SPECOBJECTS.FieldOffsetX = -50.000000
	__Link__000010_SPECOBJECTS.FieldOffsetY = -16.000000
	__Link__000010_SPECOBJECTS.TargetMultiplicity = models.ZERO_ONE
	__Link__000010_SPECOBJECTS.TargetMultiplicityOffsetX = -50.000000
	__Link__000010_SPECOBJECTS.TargetMultiplicityOffsetY = 16.000000
	__Link__000010_SPECOBJECTS.SourceMultiplicity = models.MANY
	__Link__000010_SPECOBJECTS.SourceMultiplicityOffsetX = 10.000000
	__Link__000010_SPECOBJECTS.SourceMultiplicityOffsetY = -50.000000
	__Link__000010_SPECOBJECTS.StartOrientation = models.ORIENTATION_VERTICAL
	__Link__000010_SPECOBJECTS.StartRatio = 0.838472
	__Link__000010_SPECOBJECTS.EndOrientation = models.ORIENTATION_HORIZONTAL
	__Link__000010_SPECOBJECTS.EndRatio = 0.781750
	__Link__000010_SPECOBJECTS.CornerOffsetRatio = 1.003972

	__Link__000011_TYPE.Name = `TYPE`

	//gong:ident [ref_models.SPECOBJECT.TYPE] comment added to overcome the problem with the comment map association
	__Link__000011_TYPE.Identifier = `ref_models.SPECOBJECT.TYPE`

	//gong:ident [ref_models.REQIFTYPE] comment added to overcome the problem with the comment map association
	__Link__000011_TYPE.Fieldtypename = `ref_models.REQIFTYPE`
	__Link__000011_TYPE.FieldOffsetX = -50.000000
	__Link__000011_TYPE.FieldOffsetY = -16.000000
	__Link__000011_TYPE.TargetMultiplicity = models.ZERO_ONE
	__Link__000011_TYPE.TargetMultiplicityOffsetX = -50.000000
	__Link__000011_TYPE.TargetMultiplicityOffsetY = 16.000000
	__Link__000011_TYPE.SourceMultiplicity = models.MANY
	__Link__000011_TYPE.SourceMultiplicityOffsetX = 10.000000
	__Link__000011_TYPE.SourceMultiplicityOffsetY = -50.000000
	__Link__000011_TYPE.StartOrientation = models.ORIENTATION_VERTICAL
	__Link__000011_TYPE.StartRatio = 0.246806
	__Link__000011_TYPE.EndOrientation = models.ORIENTATION_VERTICAL
	__Link__000011_TYPE.EndRatio = 0.300972
	__Link__000011_TYPE.CornerOffsetRatio = -1.454764

	__Link__000012_VALUES.Name = `VALUES`

	//gong:ident [ref_models.SPECIFICATION.VALUES] comment added to overcome the problem with the comment map association
	__Link__000012_VALUES.Identifier = `ref_models.SPECIFICATION.VALUES`

	//gong:ident [ref_models.VALUES] comment added to overcome the problem with the comment map association
	__Link__000012_VALUES.Fieldtypename = `ref_models.VALUES`
	__Link__000012_VALUES.FieldOffsetX = -50.000000
	__Link__000012_VALUES.FieldOffsetY = -16.000000
	__Link__000012_VALUES.TargetMultiplicity = models.ZERO_ONE
	__Link__000012_VALUES.TargetMultiplicityOffsetX = -50.000000
	__Link__000012_VALUES.TargetMultiplicityOffsetY = 16.000000
	__Link__000012_VALUES.SourceMultiplicity = models.MANY
	__Link__000012_VALUES.SourceMultiplicityOffsetX = 10.000000
	__Link__000012_VALUES.SourceMultiplicityOffsetY = -50.000000
	__Link__000012_VALUES.StartOrientation = models.ORIENTATION_HORIZONTAL
	__Link__000012_VALUES.StartRatio = 0.500000
	__Link__000012_VALUES.EndOrientation = models.ORIENTATION_HORIZONTAL
	__Link__000012_VALUES.EndRatio = 0.500000
	__Link__000012_VALUES.CornerOffsetRatio = 1.380000

	__Link__000013_VALUES.Name = `VALUES`

	//gong:ident [ref_models.SPECOBJECT.VALUES] comment added to overcome the problem with the comment map association
	__Link__000013_VALUES.Identifier = `ref_models.SPECOBJECT.VALUES`

	//gong:ident [ref_models.VALUES] comment added to overcome the problem with the comment map association
	__Link__000013_VALUES.Fieldtypename = `ref_models.VALUES`
	__Link__000013_VALUES.FieldOffsetX = -50.000000
	__Link__000013_VALUES.FieldOffsetY = -16.000000
	__Link__000013_VALUES.TargetMultiplicity = models.ZERO_ONE
	__Link__000013_VALUES.TargetMultiplicityOffsetX = -50.000000
	__Link__000013_VALUES.TargetMultiplicityOffsetY = 16.000000
	__Link__000013_VALUES.SourceMultiplicity = models.MANY
	__Link__000013_VALUES.SourceMultiplicityOffsetX = 10.000000
	__Link__000013_VALUES.SourceMultiplicityOffsetY = -50.000000
	__Link__000013_VALUES.StartOrientation = models.ORIENTATION_HORIZONTAL
	__Link__000013_VALUES.StartRatio = 0.500000
	__Link__000013_VALUES.EndOrientation = models.ORIENTATION_HORIZONTAL
	__Link__000013_VALUES.EndRatio = 0.500000
	__Link__000013_VALUES.CornerOffsetRatio = 1.380000

	__Position__000000_Pos_Default_1_CHILDREN.X = 868.000061
	__Position__000000_Pos_Default_1_CHILDREN.Y = 862.000000
	__Position__000000_Pos_Default_1_CHILDREN.Name = `Pos-Default_1-CHILDREN`

	__Position__000001_Pos_Default_1_CORECONTENT.X = 602.000000
	__Position__000001_Pos_Default_1_CORECONTENT.Y = 249.000000
	__Position__000001_Pos_Default_1_CORECONTENT.Name = `Pos-Default_1-CORECONTENT`

	__Position__000002_Pos_Default_1_OBJECT.X = 97.000000
	__Position__000002_Pos_Default_1_OBJECT.Y = 846.000000
	__Position__000002_Pos_Default_1_OBJECT.Name = `Pos-Default_1-OBJECT`

	__Position__000003_Pos_Default_1_REQIF.X = 98.000000
	__Position__000003_Pos_Default_1_REQIF.Y = 108.000000
	__Position__000003_Pos_Default_1_REQIF.Name = `Pos-Default_1-REQIF`

	__Position__000004_Pos_Default_1_REQIFCONTENT.X = 84.000000
	__Position__000004_Pos_Default_1_REQIFCONTENT.Y = 395.000000
	__Position__000004_Pos_Default_1_REQIFCONTENT.Name = `Pos-Default_1-REQIFCONTENT`

	__Position__000005_Pos_Default_1_REQIFTYPE.X = 1403.000061
	__Position__000005_Pos_Default_1_REQIFTYPE.Y = 221.000000
	__Position__000005_Pos_Default_1_REQIFTYPE.Name = `Pos-Default_1-REQIFTYPE`

	__Position__000006_Pos_Default_1_SPECHIERARCHY.X = 491.000000
	__Position__000006_Pos_Default_1_SPECHIERARCHY.Y = 1032.000000
	__Position__000006_Pos_Default_1_SPECHIERARCHY.Name = `Pos-Default_1-SPECHIERARCHY`

	__Position__000007_Pos_Default_1_SPECIFICATION.X = 678.000000
	__Position__000007_Pos_Default_1_SPECIFICATION.Y = 565.000000
	__Position__000007_Pos_Default_1_SPECIFICATION.Name = `Pos-Default_1-SPECIFICATION`

	__Position__000008_Pos_Default_1_SPECIFICATIONS.X = 90.000000
	__Position__000008_Pos_Default_1_SPECIFICATIONS.Y = 594.000000
	__Position__000008_Pos_Default_1_SPECIFICATIONS.Name = `Pos-Default_1-SPECIFICATIONS`

	__Position__000009_Pos_Default_1_SPECOBJECT.X = 1424.000061
	__Position__000009_Pos_Default_1_SPECOBJECT.Y = 439.000000
	__Position__000009_Pos_Default_1_SPECOBJECT.Name = `Pos-Default_1-SPECOBJECT`

	__Position__000010_Pos_Default_1_SPECOBJECTS.X = 1010.000061
	__Position__000010_Pos_Default_1_SPECOBJECTS.Y = 448.000000
	__Position__000010_Pos_Default_1_SPECOBJECTS.Name = `Pos-Default_1-SPECOBJECTS`

	__Position__000011_Pos_Default_1_SPECOBJECTTYPE.X = 1011.000061
	__Position__000011_Pos_Default_1_SPECOBJECTTYPE.Y = 131.000000
	__Position__000011_Pos_Default_1_SPECOBJECTTYPE.Name = `Pos-Default_1-SPECOBJECTTYPE`

	__Position__000012_Pos_Default_1_THEHEADER.X = 585.000000
	__Position__000012_Pos_Default_1_THEHEADER.Y = 106.000000
	__Position__000012_Pos_Default_1_THEHEADER.Name = `Pos-Default_1-THEHEADER`

	__Position__000013_Pos_Default_1_VALUES.X = 1181.000061
	__Position__000013_Pos_Default_1_VALUES.Y = 600.000000
	__Position__000013_Pos_Default_1_VALUES.Name = `Pos-Default_1-VALUES`

	__Vertice__000000_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_CHILDREN_and_Default_1_SPECHIERARCHY.X = 1295.000031
	__Vertice__000000_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_CHILDREN_and_Default_1_SPECHIERARCHY.Y = 812.000000
	__Vertice__000000_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_CHILDREN_and_Default_1_SPECHIERARCHY.Name = `Verticle in class diagram Default_1 in middle between Default_1-CHILDREN and Default_1-SPECHIERARCHY`

	__Vertice__000001_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_CORECONTENT_and_Default_1_REQIFCONTENT.X = 710.500000
	__Vertice__000001_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_CORECONTENT_and_Default_1_REQIFCONTENT.Y = 379.500000
	__Vertice__000001_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_CORECONTENT_and_Default_1_REQIFCONTENT.Name = `Verticle in class diagram Default_1 in middle between Default_1-CORECONTENT and Default_1-REQIFCONTENT`

	__Vertice__000002_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_REQIF_and_Default_1_CORECONTENT.X = 686.000000
	__Vertice__000002_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_REQIF_and_Default_1_CORECONTENT.Y = 209.500000
	__Vertice__000002_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_REQIF_and_Default_1_CORECONTENT.Name = `Verticle in class diagram Default_1 in middle between Default_1-REQIF and Default_1-CORECONTENT`

	__Vertice__000003_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_REQIF_and_Default_1_THEHEADER.X = 683.000000
	__Vertice__000003_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_REQIF_and_Default_1_THEHEADER.Y = 137.000000
	__Vertice__000003_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_REQIF_and_Default_1_THEHEADER.Name = `Verticle in class diagram Default_1 in middle between Default_1-REQIF and Default_1-THEHEADER`

	__Vertice__000004_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_REQIFCONTENT_and_Default_1_SPECIFICATIONS.X = 446.000000
	__Vertice__000004_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_REQIFCONTENT_and_Default_1_SPECIFICATIONS.Y = 524.500000
	__Vertice__000004_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_REQIFCONTENT_and_Default_1_SPECIFICATIONS.Name = `Verticle in class diagram Default_1 in middle between Default_1-REQIFCONTENT and Default_1-SPECIFICATIONS`

	__Vertice__000005_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_REQIFCONTENT_and_Default_1_SPECOBJECTS.X = 419.500000
	__Vertice__000005_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_REQIFCONTENT_and_Default_1_SPECOBJECTS.Y = 272.000000
	__Vertice__000005_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_REQIFCONTENT_and_Default_1_SPECOBJECTS.Name = `Verticle in class diagram Default_1 in middle between Default_1-REQIFCONTENT and Default_1-SPECOBJECTS`

	__Vertice__000006_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_SPECHIERARCHY_and_Default_1_CHILDREN.X = 1295.000031
	__Vertice__000006_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_SPECHIERARCHY_and_Default_1_CHILDREN.Y = 812.000000
	__Vertice__000006_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_SPECHIERARCHY_and_Default_1_CHILDREN.Name = `Verticle in class diagram Default_1 in middle between Default_1-SPECHIERARCHY and Default_1-CHILDREN`

	__Vertice__000007_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_SPECHIERARCHY_and_Default_1_OBJECT.X = 750.500000
	__Vertice__000007_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_SPECHIERARCHY_and_Default_1_OBJECT.Y = 875.000000
	__Vertice__000007_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_SPECHIERARCHY_and_Default_1_OBJECT.Name = `Verticle in class diagram Default_1 in middle between Default_1-SPECHIERARCHY and Default_1-OBJECT`

	__Vertice__000008_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_SPECIFICATION_and_Default_1_CHILDREN.X = 1292.000031
	__Vertice__000008_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_SPECIFICATION_and_Default_1_CHILDREN.Y = 704.000000
	__Vertice__000008_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_SPECIFICATION_and_Default_1_CHILDREN.Name = `Verticle in class diagram Default_1 in middle between Default_1-SPECIFICATION and Default_1-CHILDREN`

	__Vertice__000009_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_SPECIFICATION_and_Default_1_VALUES.X = 1278.500031
	__Vertice__000009_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_SPECIFICATION_and_Default_1_VALUES.Y = 620.000000
	__Vertice__000009_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_SPECIFICATION_and_Default_1_VALUES.Name = `Verticle in class diagram Default_1 in middle between Default_1-SPECIFICATION and Default_1-VALUES`

	__Vertice__000010_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_SPECIFICATIONS_and_Default_1_SPECIFICATION.X = 694.500000
	__Vertice__000010_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_SPECIFICATIONS_and_Default_1_SPECIFICATION.Y = 625.500000
	__Vertice__000010_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_SPECIFICATIONS_and_Default_1_SPECIFICATION.Name = `Verticle in class diagram Default_1 in middle between Default_1-SPECIFICATIONS and Default_1-SPECIFICATION`

	__Vertice__000011_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_SPECOBJECT_and_Default_1_REQIFTYPE.X = 1773.500061
	__Vertice__000011_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_SPECOBJECT_and_Default_1_REQIFTYPE.Y = 361.500000
	__Vertice__000011_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_SPECOBJECT_and_Default_1_REQIFTYPE.Name = `Verticle in class diagram Default_1 in middle between Default_1-SPECOBJECT and Default_1-REQIFTYPE`

	__Vertice__000012_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_SPECOBJECT_and_Default_1_VALUES.X = 1662.500061
	__Vertice__000012_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_SPECOBJECT_and_Default_1_VALUES.Y = 551.000000
	__Vertice__000012_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_SPECOBJECT_and_Default_1_VALUES.Name = `Verticle in class diagram Default_1 in middle between Default_1-SPECOBJECT and Default_1-VALUES`

	__Vertice__000013_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_SPECOBJECTS_and_Default_1_SPECOBJECT.X = 894.500031
	__Vertice__000013_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_SPECOBJECTS_and_Default_1_SPECOBJECT.Y = 262.500000
	__Vertice__000013_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_SPECOBJECTS_and_Default_1_SPECOBJECT.Name = `Verticle in class diagram Default_1 in middle between Default_1-SPECOBJECTS and Default_1-SPECOBJECT`

	// Setup of pointers
	__Classdiagram__000000_Default_1.GongStructShapes = append(__Classdiagram__000000_Default_1.GongStructShapes, __GongStructShape__000003_Default_1_REQIF)
	__Classdiagram__000000_Default_1.GongStructShapes = append(__Classdiagram__000000_Default_1.GongStructShapes, __GongStructShape__000012_Default_1_THEHEADER)
	__Classdiagram__000000_Default_1.GongStructShapes = append(__Classdiagram__000000_Default_1.GongStructShapes, __GongStructShape__000001_Default_1_CORECONTENT)
	__Classdiagram__000000_Default_1.GongStructShapes = append(__Classdiagram__000000_Default_1.GongStructShapes, __GongStructShape__000004_Default_1_REQIFCONTENT)
	__Classdiagram__000000_Default_1.GongStructShapes = append(__Classdiagram__000000_Default_1.GongStructShapes, __GongStructShape__000008_Default_1_SPECIFICATIONS)
	__Classdiagram__000000_Default_1.GongStructShapes = append(__Classdiagram__000000_Default_1.GongStructShapes, __GongStructShape__000007_Default_1_SPECIFICATION)
	__Classdiagram__000000_Default_1.GongStructShapes = append(__Classdiagram__000000_Default_1.GongStructShapes, __GongStructShape__000013_Default_1_VALUES)
	__Classdiagram__000000_Default_1.GongStructShapes = append(__Classdiagram__000000_Default_1.GongStructShapes, __GongStructShape__000000_Default_1_CHILDREN)
	__Classdiagram__000000_Default_1.GongStructShapes = append(__Classdiagram__000000_Default_1.GongStructShapes, __GongStructShape__000006_Default_1_SPECHIERARCHY)
	__Classdiagram__000000_Default_1.GongStructShapes = append(__Classdiagram__000000_Default_1.GongStructShapes, __GongStructShape__000002_Default_1_OBJECT)
	__Classdiagram__000000_Default_1.GongStructShapes = append(__Classdiagram__000000_Default_1.GongStructShapes, __GongStructShape__000009_Default_1_SPECOBJECT)
	__Classdiagram__000000_Default_1.GongStructShapes = append(__Classdiagram__000000_Default_1.GongStructShapes, __GongStructShape__000010_Default_1_SPECOBJECTS)
	__Classdiagram__000000_Default_1.GongStructShapes = append(__Classdiagram__000000_Default_1.GongStructShapes, __GongStructShape__000011_Default_1_SPECOBJECTTYPE)
	__Classdiagram__000000_Default_1.GongStructShapes = append(__Classdiagram__000000_Default_1.GongStructShapes, __GongStructShape__000005_Default_1_REQIFTYPE)
	__GongStructShape__000000_Default_1_CHILDREN.Position = __Position__000000_Pos_Default_1_CHILDREN
	__GongStructShape__000000_Default_1_CHILDREN.Links = append(__GongStructShape__000000_Default_1_CHILDREN.Links, __Link__000006_SPECHIERARCHY)
	__GongStructShape__000001_Default_1_CORECONTENT.Position = __Position__000001_Pos_Default_1_CORECONTENT
	__GongStructShape__000001_Default_1_CORECONTENT.Links = append(__GongStructShape__000001_Default_1_CORECONTENT.Links, __Link__000005_REQIFCONTENT)
	__GongStructShape__000002_Default_1_OBJECT.Position = __Position__000002_Pos_Default_1_OBJECT
	__GongStructShape__000002_Default_1_OBJECT.Fields = append(__GongStructShape__000002_Default_1_OBJECT.Fields, __Field__000005_Name)
	__GongStructShape__000002_Default_1_OBJECT.Fields = append(__GongStructShape__000002_Default_1_OBJECT.Fields, __Field__000006_SPECOBJECTREF)
	__GongStructShape__000003_Default_1_REQIF.Position = __Position__000003_Pos_Default_1_REQIF
	__GongStructShape__000003_Default_1_REQIF.Links = append(__GongStructShape__000003_Default_1_REQIF.Links, __Link__000003_HEADER)
	__GongStructShape__000003_Default_1_REQIF.Links = append(__GongStructShape__000003_Default_1_REQIF.Links, __Link__000002_CORECONTENT)
	__GongStructShape__000004_Default_1_REQIFCONTENT.Position = __Position__000004_Pos_Default_1_REQIFCONTENT
	__GongStructShape__000004_Default_1_REQIFCONTENT.Links = append(__GongStructShape__000004_Default_1_REQIFCONTENT.Links, __Link__000008_SPECIFICATIONS)
	__GongStructShape__000004_Default_1_REQIFCONTENT.Links = append(__GongStructShape__000004_Default_1_REQIFCONTENT.Links, __Link__000010_SPECOBJECTS)
	__GongStructShape__000005_Default_1_REQIFTYPE.Position = __Position__000005_Pos_Default_1_REQIFTYPE
	__GongStructShape__000005_Default_1_REQIFTYPE.Fields = append(__GongStructShape__000005_Default_1_REQIFTYPE.Fields, __Field__000000_DATATYPEDEFINITIONBOOLEANREF)
	__GongStructShape__000006_Default_1_SPECHIERARCHY.Position = __Position__000006_Pos_Default_1_SPECHIERARCHY
	__GongStructShape__000006_Default_1_SPECHIERARCHY.Links = append(__GongStructShape__000006_Default_1_SPECHIERARCHY.Links, __Link__000000_CHILDREN)
	__GongStructShape__000006_Default_1_SPECHIERARCHY.Links = append(__GongStructShape__000006_Default_1_SPECHIERARCHY.Links, __Link__000004_OBJECT)
	__GongStructShape__000007_Default_1_SPECIFICATION.Position = __Position__000007_Pos_Default_1_SPECIFICATION
	__GongStructShape__000007_Default_1_SPECIFICATION.Fields = append(__GongStructShape__000007_Default_1_SPECIFICATION.Fields, __Field__000001_DESCAttr)
	__GongStructShape__000007_Default_1_SPECIFICATION.Fields = append(__GongStructShape__000007_Default_1_SPECIFICATION.Fields, __Field__000002_IDENTIFIERAttr)
	__GongStructShape__000007_Default_1_SPECIFICATION.Fields = append(__GongStructShape__000007_Default_1_SPECIFICATION.Fields, __Field__000003_LASTCHANGEAttr)
	__GongStructShape__000007_Default_1_SPECIFICATION.Fields = append(__GongStructShape__000007_Default_1_SPECIFICATION.Fields, __Field__000004_LONGNAMEAttr)
	__GongStructShape__000007_Default_1_SPECIFICATION.Links = append(__GongStructShape__000007_Default_1_SPECIFICATION.Links, __Link__000012_VALUES)
	__GongStructShape__000007_Default_1_SPECIFICATION.Links = append(__GongStructShape__000007_Default_1_SPECIFICATION.Links, __Link__000001_CHILDREN)
	__GongStructShape__000008_Default_1_SPECIFICATIONS.Position = __Position__000008_Pos_Default_1_SPECIFICATIONS
	__GongStructShape__000008_Default_1_SPECIFICATIONS.Links = append(__GongStructShape__000008_Default_1_SPECIFICATIONS.Links, __Link__000007_SPECIFICATION)
	__GongStructShape__000009_Default_1_SPECOBJECT.Position = __Position__000009_Pos_Default_1_SPECOBJECT
	__GongStructShape__000009_Default_1_SPECOBJECT.Links = append(__GongStructShape__000009_Default_1_SPECOBJECT.Links, __Link__000013_VALUES)
	__GongStructShape__000009_Default_1_SPECOBJECT.Links = append(__GongStructShape__000009_Default_1_SPECOBJECT.Links, __Link__000011_TYPE)
	__GongStructShape__000010_Default_1_SPECOBJECTS.Position = __Position__000010_Pos_Default_1_SPECOBJECTS
	__GongStructShape__000010_Default_1_SPECOBJECTS.Links = append(__GongStructShape__000010_Default_1_SPECOBJECTS.Links, __Link__000009_SPECOBJECT)
	__GongStructShape__000011_Default_1_SPECOBJECTTYPE.Position = __Position__000011_Pos_Default_1_SPECOBJECTTYPE
	__GongStructShape__000012_Default_1_THEHEADER.Position = __Position__000012_Pos_Default_1_THEHEADER
	__GongStructShape__000013_Default_1_VALUES.Position = __Position__000013_Pos_Default_1_VALUES
	__Link__000000_CHILDREN.Middlevertice = __Vertice__000006_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_SPECHIERARCHY_and_Default_1_CHILDREN
	__Link__000001_CHILDREN.Middlevertice = __Vertice__000008_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_SPECIFICATION_and_Default_1_CHILDREN
	__Link__000002_CORECONTENT.Middlevertice = __Vertice__000002_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_REQIF_and_Default_1_CORECONTENT
	__Link__000003_HEADER.Middlevertice = __Vertice__000003_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_REQIF_and_Default_1_THEHEADER
	__Link__000004_OBJECT.Middlevertice = __Vertice__000007_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_SPECHIERARCHY_and_Default_1_OBJECT
	__Link__000005_REQIFCONTENT.Middlevertice = __Vertice__000001_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_CORECONTENT_and_Default_1_REQIFCONTENT
	__Link__000006_SPECHIERARCHY.Middlevertice = __Vertice__000000_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_CHILDREN_and_Default_1_SPECHIERARCHY
	__Link__000007_SPECIFICATION.Middlevertice = __Vertice__000010_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_SPECIFICATIONS_and_Default_1_SPECIFICATION
	__Link__000008_SPECIFICATIONS.Middlevertice = __Vertice__000004_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_REQIFCONTENT_and_Default_1_SPECIFICATIONS
	__Link__000009_SPECOBJECT.Middlevertice = __Vertice__000013_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_SPECOBJECTS_and_Default_1_SPECOBJECT
	__Link__000010_SPECOBJECTS.Middlevertice = __Vertice__000005_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_REQIFCONTENT_and_Default_1_SPECOBJECTS
	__Link__000011_TYPE.Middlevertice = __Vertice__000011_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_SPECOBJECT_and_Default_1_REQIFTYPE
	__Link__000012_VALUES.Middlevertice = __Vertice__000009_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_SPECIFICATION_and_Default_1_VALUES
	__Link__000013_VALUES.Middlevertice = __Vertice__000012_Verticle_in_class_diagram_Default_1_in_middle_between_Default_1_SPECOBJECT_and_Default_1_VALUES
}
