package diagrams

import (
	"time"

	"github.com/fullstack-lang/gongdoc/go/models"

	// injection point for ident package import declaration
	ref_models "github.com/thomaspeugeot/gongreqif/go/models"
)

// generated in order to avoid error in the package import
// if there are no elements in the stage to marshall
var _ time.Time

// _ point for meta package dummy declaration
var _ ref_models.StageStruct

// When parsed, those maps will help with the renaming process
var _ map[string]any = map[string]any{
	// injection point for docLink to identifiers

	"ref_models.ALTERNATIVEID": &(ref_models.ALTERNATIVEID{}),

	"ref_models.ALTERNATIVEID.IDENTIFIERAttr": (ref_models.ALTERNATIVEID{}).IDENTIFIERAttr,

	"ref_models.ALTERNATIVEID.Name": (ref_models.ALTERNATIVEID{}).Name,

	"ref_models.ATTRIBUTEDEFINITIONBOOLEAN": &(ref_models.ATTRIBUTEDEFINITIONBOOLEAN{}),

	"ref_models.ATTRIBUTEDEFINITIONBOOLEAN.ALTERNATIVEID": (ref_models.ATTRIBUTEDEFINITIONBOOLEAN{}).ALTERNATIVEID,

	"ref_models.ATTRIBUTEDEFINITIONBOOLEAN.DEFAULTVALUE": (ref_models.ATTRIBUTEDEFINITIONBOOLEAN{}).DEFAULTVALUE,

	"ref_models.ATTRIBUTEDEFINITIONBOOLEAN.DESCAttr": (ref_models.ATTRIBUTEDEFINITIONBOOLEAN{}).DESCAttr,

	"ref_models.ATTRIBUTEDEFINITIONBOOLEAN.IDENTIFIERAttr": (ref_models.ATTRIBUTEDEFINITIONBOOLEAN{}).IDENTIFIERAttr,

	"ref_models.ATTRIBUTEDEFINITIONBOOLEAN.ISEDITABLEAttr": (ref_models.ATTRIBUTEDEFINITIONBOOLEAN{}).ISEDITABLEAttr,

	"ref_models.ATTRIBUTEDEFINITIONBOOLEAN.LASTCHANGEAttr": (ref_models.ATTRIBUTEDEFINITIONBOOLEAN{}).LASTCHANGEAttr,

	"ref_models.ATTRIBUTEDEFINITIONBOOLEAN.LONGNAMEAttr": (ref_models.ATTRIBUTEDEFINITIONBOOLEAN{}).LONGNAMEAttr,

	"ref_models.ATTRIBUTEDEFINITIONBOOLEAN.Name": (ref_models.ATTRIBUTEDEFINITIONBOOLEAN{}).Name,

	"ref_models.ATTRIBUTEDEFINITIONBOOLEAN.TYPE": (ref_models.ATTRIBUTEDEFINITIONBOOLEAN{}).TYPE,

	"ref_models.ATTRIBUTEDEFINITIONDATE": &(ref_models.ATTRIBUTEDEFINITIONDATE{}),

	"ref_models.ATTRIBUTEDEFINITIONDATE.ALTERNATIVEID": (ref_models.ATTRIBUTEDEFINITIONDATE{}).ALTERNATIVEID,

	"ref_models.ATTRIBUTEDEFINITIONDATE.DEFAULTVALUE": (ref_models.ATTRIBUTEDEFINITIONDATE{}).DEFAULTVALUE,

	"ref_models.ATTRIBUTEDEFINITIONDATE.DESCAttr": (ref_models.ATTRIBUTEDEFINITIONDATE{}).DESCAttr,

	"ref_models.ATTRIBUTEDEFINITIONDATE.IDENTIFIERAttr": (ref_models.ATTRIBUTEDEFINITIONDATE{}).IDENTIFIERAttr,

	"ref_models.ATTRIBUTEDEFINITIONDATE.ISEDITABLEAttr": (ref_models.ATTRIBUTEDEFINITIONDATE{}).ISEDITABLEAttr,

	"ref_models.ATTRIBUTEDEFINITIONDATE.LASTCHANGEAttr": (ref_models.ATTRIBUTEDEFINITIONDATE{}).LASTCHANGEAttr,

	"ref_models.ATTRIBUTEDEFINITIONDATE.LONGNAMEAttr": (ref_models.ATTRIBUTEDEFINITIONDATE{}).LONGNAMEAttr,

	"ref_models.ATTRIBUTEDEFINITIONDATE.Name": (ref_models.ATTRIBUTEDEFINITIONDATE{}).Name,

	"ref_models.ATTRIBUTEDEFINITIONDATE.TYPE": (ref_models.ATTRIBUTEDEFINITIONDATE{}).TYPE,

	"ref_models.ATTRIBUTEDEFINITIONENUMERATION": &(ref_models.ATTRIBUTEDEFINITIONENUMERATION{}),

	"ref_models.ATTRIBUTEDEFINITIONENUMERATION.ALTERNATIVEID": (ref_models.ATTRIBUTEDEFINITIONENUMERATION{}).ALTERNATIVEID,

	"ref_models.ATTRIBUTEDEFINITIONENUMERATION.DEFAULTVALUE": (ref_models.ATTRIBUTEDEFINITIONENUMERATION{}).DEFAULTVALUE,

	"ref_models.ATTRIBUTEDEFINITIONENUMERATION.DESCAttr": (ref_models.ATTRIBUTEDEFINITIONENUMERATION{}).DESCAttr,

	"ref_models.ATTRIBUTEDEFINITIONENUMERATION.IDENTIFIERAttr": (ref_models.ATTRIBUTEDEFINITIONENUMERATION{}).IDENTIFIERAttr,

	"ref_models.ATTRIBUTEDEFINITIONENUMERATION.ISEDITABLEAttr": (ref_models.ATTRIBUTEDEFINITIONENUMERATION{}).ISEDITABLEAttr,

	"ref_models.ATTRIBUTEDEFINITIONENUMERATION.LASTCHANGEAttr": (ref_models.ATTRIBUTEDEFINITIONENUMERATION{}).LASTCHANGEAttr,

	"ref_models.ATTRIBUTEDEFINITIONENUMERATION.LONGNAMEAttr": (ref_models.ATTRIBUTEDEFINITIONENUMERATION{}).LONGNAMEAttr,

	"ref_models.ATTRIBUTEDEFINITIONENUMERATION.MULTIVALUEDAttr": (ref_models.ATTRIBUTEDEFINITIONENUMERATION{}).MULTIVALUEDAttr,

	"ref_models.ATTRIBUTEDEFINITIONENUMERATION.Name": (ref_models.ATTRIBUTEDEFINITIONENUMERATION{}).Name,

	"ref_models.ATTRIBUTEDEFINITIONENUMERATION.TYPE": (ref_models.ATTRIBUTEDEFINITIONENUMERATION{}).TYPE,

	"ref_models.ATTRIBUTEDEFINITIONINTEGER": &(ref_models.ATTRIBUTEDEFINITIONINTEGER{}),

	"ref_models.ATTRIBUTEDEFINITIONINTEGER.ALTERNATIVEID": (ref_models.ATTRIBUTEDEFINITIONINTEGER{}).ALTERNATIVEID,

	"ref_models.ATTRIBUTEDEFINITIONINTEGER.DEFAULTVALUE": (ref_models.ATTRIBUTEDEFINITIONINTEGER{}).DEFAULTVALUE,

	"ref_models.ATTRIBUTEDEFINITIONINTEGER.DESCAttr": (ref_models.ATTRIBUTEDEFINITIONINTEGER{}).DESCAttr,

	"ref_models.ATTRIBUTEDEFINITIONINTEGER.IDENTIFIERAttr": (ref_models.ATTRIBUTEDEFINITIONINTEGER{}).IDENTIFIERAttr,

	"ref_models.ATTRIBUTEDEFINITIONINTEGER.ISEDITABLEAttr": (ref_models.ATTRIBUTEDEFINITIONINTEGER{}).ISEDITABLEAttr,

	"ref_models.ATTRIBUTEDEFINITIONINTEGER.LASTCHANGEAttr": (ref_models.ATTRIBUTEDEFINITIONINTEGER{}).LASTCHANGEAttr,

	"ref_models.ATTRIBUTEDEFINITIONINTEGER.LONGNAMEAttr": (ref_models.ATTRIBUTEDEFINITIONINTEGER{}).LONGNAMEAttr,

	"ref_models.ATTRIBUTEDEFINITIONINTEGER.Name": (ref_models.ATTRIBUTEDEFINITIONINTEGER{}).Name,

	"ref_models.ATTRIBUTEDEFINITIONINTEGER.TYPE": (ref_models.ATTRIBUTEDEFINITIONINTEGER{}).TYPE,

	"ref_models.ATTRIBUTEDEFINITIONREAL": &(ref_models.ATTRIBUTEDEFINITIONREAL{}),

	"ref_models.ATTRIBUTEDEFINITIONREAL.ALTERNATIVEID": (ref_models.ATTRIBUTEDEFINITIONREAL{}).ALTERNATIVEID,

	"ref_models.ATTRIBUTEDEFINITIONREAL.DEFAULTVALUE": (ref_models.ATTRIBUTEDEFINITIONREAL{}).DEFAULTVALUE,

	"ref_models.ATTRIBUTEDEFINITIONREAL.DESCAttr": (ref_models.ATTRIBUTEDEFINITIONREAL{}).DESCAttr,

	"ref_models.ATTRIBUTEDEFINITIONREAL.IDENTIFIERAttr": (ref_models.ATTRIBUTEDEFINITIONREAL{}).IDENTIFIERAttr,

	"ref_models.ATTRIBUTEDEFINITIONREAL.ISEDITABLEAttr": (ref_models.ATTRIBUTEDEFINITIONREAL{}).ISEDITABLEAttr,

	"ref_models.ATTRIBUTEDEFINITIONREAL.LASTCHANGEAttr": (ref_models.ATTRIBUTEDEFINITIONREAL{}).LASTCHANGEAttr,

	"ref_models.ATTRIBUTEDEFINITIONREAL.LONGNAMEAttr": (ref_models.ATTRIBUTEDEFINITIONREAL{}).LONGNAMEAttr,

	"ref_models.ATTRIBUTEDEFINITIONREAL.Name": (ref_models.ATTRIBUTEDEFINITIONREAL{}).Name,

	"ref_models.ATTRIBUTEDEFINITIONREAL.TYPE": (ref_models.ATTRIBUTEDEFINITIONREAL{}).TYPE,

	"ref_models.ATTRIBUTEDEFINITIONSTRING": &(ref_models.ATTRIBUTEDEFINITIONSTRING{}),

	"ref_models.ATTRIBUTEDEFINITIONSTRING.ALTERNATIVEID": (ref_models.ATTRIBUTEDEFINITIONSTRING{}).ALTERNATIVEID,

	"ref_models.ATTRIBUTEDEFINITIONSTRING.DEFAULTVALUE": (ref_models.ATTRIBUTEDEFINITIONSTRING{}).DEFAULTVALUE,

	"ref_models.ATTRIBUTEDEFINITIONSTRING.DESCAttr": (ref_models.ATTRIBUTEDEFINITIONSTRING{}).DESCAttr,

	"ref_models.ATTRIBUTEDEFINITIONSTRING.IDENTIFIERAttr": (ref_models.ATTRIBUTEDEFINITIONSTRING{}).IDENTIFIERAttr,

	"ref_models.ATTRIBUTEDEFINITIONSTRING.ISEDITABLEAttr": (ref_models.ATTRIBUTEDEFINITIONSTRING{}).ISEDITABLEAttr,

	"ref_models.ATTRIBUTEDEFINITIONSTRING.LASTCHANGEAttr": (ref_models.ATTRIBUTEDEFINITIONSTRING{}).LASTCHANGEAttr,

	"ref_models.ATTRIBUTEDEFINITIONSTRING.LONGNAMEAttr": (ref_models.ATTRIBUTEDEFINITIONSTRING{}).LONGNAMEAttr,

	"ref_models.ATTRIBUTEDEFINITIONSTRING.Name": (ref_models.ATTRIBUTEDEFINITIONSTRING{}).Name,

	"ref_models.ATTRIBUTEDEFINITIONSTRING.TYPE": (ref_models.ATTRIBUTEDEFINITIONSTRING{}).TYPE,

	"ref_models.ATTRIBUTEDEFINITIONXHTML": &(ref_models.ATTRIBUTEDEFINITIONXHTML{}),

	"ref_models.ATTRIBUTEDEFINITIONXHTML.ALTERNATIVEID": (ref_models.ATTRIBUTEDEFINITIONXHTML{}).ALTERNATIVEID,

	"ref_models.ATTRIBUTEDEFINITIONXHTML.DEFAULTVALUE": (ref_models.ATTRIBUTEDEFINITIONXHTML{}).DEFAULTVALUE,

	"ref_models.ATTRIBUTEDEFINITIONXHTML.DESCAttr": (ref_models.ATTRIBUTEDEFINITIONXHTML{}).DESCAttr,

	"ref_models.ATTRIBUTEDEFINITIONXHTML.IDENTIFIERAttr": (ref_models.ATTRIBUTEDEFINITIONXHTML{}).IDENTIFIERAttr,

	"ref_models.ATTRIBUTEDEFINITIONXHTML.ISEDITABLEAttr": (ref_models.ATTRIBUTEDEFINITIONXHTML{}).ISEDITABLEAttr,

	"ref_models.ATTRIBUTEDEFINITIONXHTML.LASTCHANGEAttr": (ref_models.ATTRIBUTEDEFINITIONXHTML{}).LASTCHANGEAttr,

	"ref_models.ATTRIBUTEDEFINITIONXHTML.LONGNAMEAttr": (ref_models.ATTRIBUTEDEFINITIONXHTML{}).LONGNAMEAttr,

	"ref_models.ATTRIBUTEDEFINITIONXHTML.Name": (ref_models.ATTRIBUTEDEFINITIONXHTML{}).Name,

	"ref_models.ATTRIBUTEDEFINITIONXHTML.TYPE": (ref_models.ATTRIBUTEDEFINITIONXHTML{}).TYPE,

	"ref_models.ATTRIBUTEVALUEBOOLEAN": &(ref_models.ATTRIBUTEVALUEBOOLEAN{}),

	"ref_models.ATTRIBUTEVALUEBOOLEAN.DEFINITION": (ref_models.ATTRIBUTEVALUEBOOLEAN{}).DEFINITION,

	"ref_models.ATTRIBUTEVALUEBOOLEAN.Name": (ref_models.ATTRIBUTEVALUEBOOLEAN{}).Name,

	"ref_models.ATTRIBUTEVALUEBOOLEAN.THEVALUEAttr": (ref_models.ATTRIBUTEVALUEBOOLEAN{}).THEVALUEAttr,

	"ref_models.ATTRIBUTEVALUEDATE": &(ref_models.ATTRIBUTEVALUEDATE{}),

	"ref_models.ATTRIBUTEVALUEDATE.DEFINITION": (ref_models.ATTRIBUTEVALUEDATE{}).DEFINITION,

	"ref_models.ATTRIBUTEVALUEDATE.Name": (ref_models.ATTRIBUTEVALUEDATE{}).Name,

	"ref_models.ATTRIBUTEVALUEDATE.THEVALUEAttr": (ref_models.ATTRIBUTEVALUEDATE{}).THEVALUEAttr,

	"ref_models.ATTRIBUTEVALUEENUMERATION": &(ref_models.ATTRIBUTEVALUEENUMERATION{}),

	"ref_models.ATTRIBUTEVALUEENUMERATION.DEFINITION": (ref_models.ATTRIBUTEVALUEENUMERATION{}).DEFINITION,

	"ref_models.ATTRIBUTEVALUEENUMERATION.Name": (ref_models.ATTRIBUTEVALUEENUMERATION{}).Name,

	"ref_models.ATTRIBUTEVALUEENUMERATION.VALUES": (ref_models.ATTRIBUTEVALUEENUMERATION{}).VALUES,

	"ref_models.ATTRIBUTEVALUEINTEGER": &(ref_models.ATTRIBUTEVALUEINTEGER{}),

	"ref_models.ATTRIBUTEVALUEINTEGER.DEFINITION": (ref_models.ATTRIBUTEVALUEINTEGER{}).DEFINITION,

	"ref_models.ATTRIBUTEVALUEINTEGER.Name": (ref_models.ATTRIBUTEVALUEINTEGER{}).Name,

	"ref_models.ATTRIBUTEVALUEINTEGER.THEVALUEAttr": (ref_models.ATTRIBUTEVALUEINTEGER{}).THEVALUEAttr,

	"ref_models.ATTRIBUTEVALUEREAL": &(ref_models.ATTRIBUTEVALUEREAL{}),

	"ref_models.ATTRIBUTEVALUEREAL.DEFINITION": (ref_models.ATTRIBUTEVALUEREAL{}).DEFINITION,

	"ref_models.ATTRIBUTEVALUEREAL.Name": (ref_models.ATTRIBUTEVALUEREAL{}).Name,

	"ref_models.ATTRIBUTEVALUEREAL.THEVALUEAttr": (ref_models.ATTRIBUTEVALUEREAL{}).THEVALUEAttr,

	"ref_models.ATTRIBUTEVALUESTRING": &(ref_models.ATTRIBUTEVALUESTRING{}),

	"ref_models.ATTRIBUTEVALUESTRING.DEFINITION": (ref_models.ATTRIBUTEVALUESTRING{}).DEFINITION,

	"ref_models.ATTRIBUTEVALUESTRING.Name": (ref_models.ATTRIBUTEVALUESTRING{}).Name,

	"ref_models.ATTRIBUTEVALUESTRING.THEVALUEAttr": (ref_models.ATTRIBUTEVALUESTRING{}).THEVALUEAttr,

	"ref_models.ATTRIBUTEVALUEXHTML": &(ref_models.ATTRIBUTEVALUEXHTML{}),

	"ref_models.ATTRIBUTEVALUEXHTML.DEFINITION": (ref_models.ATTRIBUTEVALUEXHTML{}).DEFINITION,

	"ref_models.ATTRIBUTEVALUEXHTML.ISSIMPLIFIEDAttr": (ref_models.ATTRIBUTEVALUEXHTML{}).ISSIMPLIFIEDAttr,

	"ref_models.ATTRIBUTEVALUEXHTML.Name": (ref_models.ATTRIBUTEVALUEXHTML{}).Name,

	"ref_models.ATTRIBUTEVALUEXHTML.THEORIGINALVALUE": (ref_models.ATTRIBUTEVALUEXHTML{}).THEORIGINALVALUE,

	"ref_models.ATTRIBUTEVALUEXHTML.THEVALUE": (ref_models.ATTRIBUTEVALUEXHTML{}).THEVALUE,

	"ref_models.CHILDREN": &(ref_models.CHILDREN{}),

	"ref_models.CHILDREN.Name": (ref_models.CHILDREN{}).Name,

	"ref_models.CHILDREN.SPECHIERARCHY": (ref_models.CHILDREN{}).SPECHIERARCHY,

	"ref_models.CORECONTENT": &(ref_models.CORECONTENT{}),

	"ref_models.CORECONTENT.Name": (ref_models.CORECONTENT{}).Name,

	"ref_models.CORECONTENT.REQIFCONTENT": (ref_models.CORECONTENT{}).REQIFCONTENT,

	"ref_models.DATATYPEDEFINITIONBOOLEAN": &(ref_models.DATATYPEDEFINITIONBOOLEAN{}),

	"ref_models.DATATYPEDEFINITIONBOOLEAN.ALTERNATIVEID": (ref_models.DATATYPEDEFINITIONBOOLEAN{}).ALTERNATIVEID,

	"ref_models.DATATYPEDEFINITIONBOOLEAN.DESCAttr": (ref_models.DATATYPEDEFINITIONBOOLEAN{}).DESCAttr,

	"ref_models.DATATYPEDEFINITIONBOOLEAN.IDENTIFIERAttr": (ref_models.DATATYPEDEFINITIONBOOLEAN{}).IDENTIFIERAttr,

	"ref_models.DATATYPEDEFINITIONBOOLEAN.LASTCHANGEAttr": (ref_models.DATATYPEDEFINITIONBOOLEAN{}).LASTCHANGEAttr,

	"ref_models.DATATYPEDEFINITIONBOOLEAN.LONGNAMEAttr": (ref_models.DATATYPEDEFINITIONBOOLEAN{}).LONGNAMEAttr,

	"ref_models.DATATYPEDEFINITIONBOOLEAN.Name": (ref_models.DATATYPEDEFINITIONBOOLEAN{}).Name,

	"ref_models.DATATYPEDEFINITIONDATE": &(ref_models.DATATYPEDEFINITIONDATE{}),

	"ref_models.DATATYPEDEFINITIONDATE.ALTERNATIVEID": (ref_models.DATATYPEDEFINITIONDATE{}).ALTERNATIVEID,

	"ref_models.DATATYPEDEFINITIONDATE.DESCAttr": (ref_models.DATATYPEDEFINITIONDATE{}).DESCAttr,

	"ref_models.DATATYPEDEFINITIONDATE.IDENTIFIERAttr": (ref_models.DATATYPEDEFINITIONDATE{}).IDENTIFIERAttr,

	"ref_models.DATATYPEDEFINITIONDATE.LASTCHANGEAttr": (ref_models.DATATYPEDEFINITIONDATE{}).LASTCHANGEAttr,

	"ref_models.DATATYPEDEFINITIONDATE.LONGNAMEAttr": (ref_models.DATATYPEDEFINITIONDATE{}).LONGNAMEAttr,

	"ref_models.DATATYPEDEFINITIONDATE.Name": (ref_models.DATATYPEDEFINITIONDATE{}).Name,

	"ref_models.DATATYPEDEFINITIONENUMERATION": &(ref_models.DATATYPEDEFINITIONENUMERATION{}),

	"ref_models.DATATYPEDEFINITIONENUMERATION.ALTERNATIVEID": (ref_models.DATATYPEDEFINITIONENUMERATION{}).ALTERNATIVEID,

	"ref_models.DATATYPEDEFINITIONENUMERATION.DESCAttr": (ref_models.DATATYPEDEFINITIONENUMERATION{}).DESCAttr,

	"ref_models.DATATYPEDEFINITIONENUMERATION.IDENTIFIERAttr": (ref_models.DATATYPEDEFINITIONENUMERATION{}).IDENTIFIERAttr,

	"ref_models.DATATYPEDEFINITIONENUMERATION.LASTCHANGEAttr": (ref_models.DATATYPEDEFINITIONENUMERATION{}).LASTCHANGEAttr,

	"ref_models.DATATYPEDEFINITIONENUMERATION.LONGNAMEAttr": (ref_models.DATATYPEDEFINITIONENUMERATION{}).LONGNAMEAttr,

	"ref_models.DATATYPEDEFINITIONENUMERATION.Name": (ref_models.DATATYPEDEFINITIONENUMERATION{}).Name,

	"ref_models.DATATYPEDEFINITIONENUMERATION.SPECIFIEDVALUES": (ref_models.DATATYPEDEFINITIONENUMERATION{}).SPECIFIEDVALUES,

	"ref_models.DATATYPEDEFINITIONINTEGER": &(ref_models.DATATYPEDEFINITIONINTEGER{}),

	"ref_models.DATATYPEDEFINITIONINTEGER.ALTERNATIVEID": (ref_models.DATATYPEDEFINITIONINTEGER{}).ALTERNATIVEID,

	"ref_models.DATATYPEDEFINITIONINTEGER.DESCAttr": (ref_models.DATATYPEDEFINITIONINTEGER{}).DESCAttr,

	"ref_models.DATATYPEDEFINITIONINTEGER.IDENTIFIERAttr": (ref_models.DATATYPEDEFINITIONINTEGER{}).IDENTIFIERAttr,

	"ref_models.DATATYPEDEFINITIONINTEGER.LASTCHANGEAttr": (ref_models.DATATYPEDEFINITIONINTEGER{}).LASTCHANGEAttr,

	"ref_models.DATATYPEDEFINITIONINTEGER.LONGNAMEAttr": (ref_models.DATATYPEDEFINITIONINTEGER{}).LONGNAMEAttr,

	"ref_models.DATATYPEDEFINITIONINTEGER.MAXAttr": (ref_models.DATATYPEDEFINITIONINTEGER{}).MAXAttr,

	"ref_models.DATATYPEDEFINITIONINTEGER.MINAttr": (ref_models.DATATYPEDEFINITIONINTEGER{}).MINAttr,

	"ref_models.DATATYPEDEFINITIONINTEGER.Name": (ref_models.DATATYPEDEFINITIONINTEGER{}).Name,

	"ref_models.DATATYPEDEFINITIONREAL": &(ref_models.DATATYPEDEFINITIONREAL{}),

	"ref_models.DATATYPEDEFINITIONREAL.ACCURACYAttr": (ref_models.DATATYPEDEFINITIONREAL{}).ACCURACYAttr,

	"ref_models.DATATYPEDEFINITIONREAL.ALTERNATIVEID": (ref_models.DATATYPEDEFINITIONREAL{}).ALTERNATIVEID,

	"ref_models.DATATYPEDEFINITIONREAL.DESCAttr": (ref_models.DATATYPEDEFINITIONREAL{}).DESCAttr,

	"ref_models.DATATYPEDEFINITIONREAL.IDENTIFIERAttr": (ref_models.DATATYPEDEFINITIONREAL{}).IDENTIFIERAttr,

	"ref_models.DATATYPEDEFINITIONREAL.LASTCHANGEAttr": (ref_models.DATATYPEDEFINITIONREAL{}).LASTCHANGEAttr,

	"ref_models.DATATYPEDEFINITIONREAL.LONGNAMEAttr": (ref_models.DATATYPEDEFINITIONREAL{}).LONGNAMEAttr,

	"ref_models.DATATYPEDEFINITIONREAL.MAXAttr": (ref_models.DATATYPEDEFINITIONREAL{}).MAXAttr,

	"ref_models.DATATYPEDEFINITIONREAL.MINAttr": (ref_models.DATATYPEDEFINITIONREAL{}).MINAttr,

	"ref_models.DATATYPEDEFINITIONREAL.Name": (ref_models.DATATYPEDEFINITIONREAL{}).Name,

	"ref_models.DATATYPEDEFINITIONSTRING": &(ref_models.DATATYPEDEFINITIONSTRING{}),

	"ref_models.DATATYPEDEFINITIONSTRING.ALTERNATIVEID": (ref_models.DATATYPEDEFINITIONSTRING{}).ALTERNATIVEID,

	"ref_models.DATATYPEDEFINITIONSTRING.DESCAttr": (ref_models.DATATYPEDEFINITIONSTRING{}).DESCAttr,

	"ref_models.DATATYPEDEFINITIONSTRING.IDENTIFIERAttr": (ref_models.DATATYPEDEFINITIONSTRING{}).IDENTIFIERAttr,

	"ref_models.DATATYPEDEFINITIONSTRING.LASTCHANGEAttr": (ref_models.DATATYPEDEFINITIONSTRING{}).LASTCHANGEAttr,

	"ref_models.DATATYPEDEFINITIONSTRING.LONGNAMEAttr": (ref_models.DATATYPEDEFINITIONSTRING{}).LONGNAMEAttr,

	"ref_models.DATATYPEDEFINITIONSTRING.MAXLENGTHAttr": (ref_models.DATATYPEDEFINITIONSTRING{}).MAXLENGTHAttr,

	"ref_models.DATATYPEDEFINITIONSTRING.Name": (ref_models.DATATYPEDEFINITIONSTRING{}).Name,

	"ref_models.DATATYPEDEFINITIONXHTML": &(ref_models.DATATYPEDEFINITIONXHTML{}),

	"ref_models.DATATYPEDEFINITIONXHTML.ALTERNATIVEID": (ref_models.DATATYPEDEFINITIONXHTML{}).ALTERNATIVEID,

	"ref_models.DATATYPEDEFINITIONXHTML.DESCAttr": (ref_models.DATATYPEDEFINITIONXHTML{}).DESCAttr,

	"ref_models.DATATYPEDEFINITIONXHTML.IDENTIFIERAttr": (ref_models.DATATYPEDEFINITIONXHTML{}).IDENTIFIERAttr,

	"ref_models.DATATYPEDEFINITIONXHTML.LASTCHANGEAttr": (ref_models.DATATYPEDEFINITIONXHTML{}).LASTCHANGEAttr,

	"ref_models.DATATYPEDEFINITIONXHTML.LONGNAMEAttr": (ref_models.DATATYPEDEFINITIONXHTML{}).LONGNAMEAttr,

	"ref_models.DATATYPEDEFINITIONXHTML.Name": (ref_models.DATATYPEDEFINITIONXHTML{}).Name,

	"ref_models.DATATYPES": &(ref_models.DATATYPES{}),

	"ref_models.DATATYPES.DATATYPEDEFINITIONBOOLEAN": (ref_models.DATATYPES{}).DATATYPEDEFINITIONBOOLEAN,

	"ref_models.DATATYPES.DATATYPEDEFINITIONDATE": (ref_models.DATATYPES{}).DATATYPEDEFINITIONDATE,

	"ref_models.DATATYPES.DATATYPEDEFINITIONENUMERATION": (ref_models.DATATYPES{}).DATATYPEDEFINITIONENUMERATION,

	"ref_models.DATATYPES.DATATYPEDEFINITIONINTEGER": (ref_models.DATATYPES{}).DATATYPEDEFINITIONINTEGER,

	"ref_models.DATATYPES.DATATYPEDEFINITIONREAL": (ref_models.DATATYPES{}).DATATYPEDEFINITIONREAL,

	"ref_models.DATATYPES.DATATYPEDEFINITIONSTRING": (ref_models.DATATYPES{}).DATATYPEDEFINITIONSTRING,

	"ref_models.DATATYPES.DATATYPEDEFINITIONXHTML": (ref_models.DATATYPES{}).DATATYPEDEFINITIONXHTML,

	"ref_models.DATATYPES.Name": (ref_models.DATATYPES{}).Name,

	"ref_models.DEFAULTVALUE": &(ref_models.DEFAULTVALUE{}),

	"ref_models.DEFAULTVALUE.ATTRIBUTEVALUEBOOLEAN": (ref_models.DEFAULTVALUE{}).ATTRIBUTEVALUEBOOLEAN,

	"ref_models.DEFAULTVALUE.Name": (ref_models.DEFAULTVALUE{}).Name,

	"ref_models.DEFINITION": &(ref_models.DEFINITION{}),

	"ref_models.DEFINITION.ATTRIBUTEDEFINITIONBOOLEANREF": (ref_models.DEFINITION{}).ATTRIBUTEDEFINITIONBOOLEANREF,

	"ref_models.DEFINITION.Name": (ref_models.DEFINITION{}).Name,

	"ref_models.EDITABLEATTS": &(ref_models.EDITABLEATTS{}),

	"ref_models.EDITABLEATTS.Name": (ref_models.EDITABLEATTS{}).Name,

	"ref_models.EMBEDDEDVALUE": &(ref_models.EMBEDDEDVALUE{}),

	"ref_models.EMBEDDEDVALUE.KEYAttr": (ref_models.EMBEDDEDVALUE{}).KEYAttr,

	"ref_models.EMBEDDEDVALUE.Name": (ref_models.EMBEDDEDVALUE{}).Name,

	"ref_models.EMBEDDEDVALUE.OTHERCONTENTAttr": (ref_models.EMBEDDEDVALUE{}).OTHERCONTENTAttr,

	"ref_models.ENUMVALUE": &(ref_models.ENUMVALUE{}),

	"ref_models.ENUMVALUE.ALTERNATIVEID": (ref_models.ENUMVALUE{}).ALTERNATIVEID,

	"ref_models.ENUMVALUE.DESCAttr": (ref_models.ENUMVALUE{}).DESCAttr,

	"ref_models.ENUMVALUE.IDENTIFIERAttr": (ref_models.ENUMVALUE{}).IDENTIFIERAttr,

	"ref_models.ENUMVALUE.LASTCHANGEAttr": (ref_models.ENUMVALUE{}).LASTCHANGEAttr,

	"ref_models.ENUMVALUE.LONGNAMEAttr": (ref_models.ENUMVALUE{}).LONGNAMEAttr,

	"ref_models.ENUMVALUE.Name": (ref_models.ENUMVALUE{}).Name,

	"ref_models.ENUMVALUE.PROPERTIES": (ref_models.ENUMVALUE{}).PROPERTIES,

	"ref_models.GLOBALREF": ref_models.GLOBALREF(""),

	"ref_models.LOCALREF": ref_models.LOCALREF(""),

	"ref_models.OBJECT": &(ref_models.OBJECT{}),

	"ref_models.OBJECT.Name": (ref_models.OBJECT{}).Name,

	"ref_models.OBJECT.SPECOBJECTREF": (ref_models.OBJECT{}).SPECOBJECTREF,

	"ref_models.PROPERTIES": &(ref_models.PROPERTIES{}),

	"ref_models.PROPERTIES.EMBEDDEDVALUE": (ref_models.PROPERTIES{}).EMBEDDEDVALUE,

	"ref_models.PROPERTIES.Name": (ref_models.PROPERTIES{}).Name,

	"ref_models.RELATIONGROUP": &(ref_models.RELATIONGROUP{}),

	"ref_models.RELATIONGROUP.ALTERNATIVEID": (ref_models.RELATIONGROUP{}).ALTERNATIVEID,

	"ref_models.RELATIONGROUP.DESCAttr": (ref_models.RELATIONGROUP{}).DESCAttr,

	"ref_models.RELATIONGROUP.IDENTIFIERAttr": (ref_models.RELATIONGROUP{}).IDENTIFIERAttr,

	"ref_models.RELATIONGROUP.LASTCHANGEAttr": (ref_models.RELATIONGROUP{}).LASTCHANGEAttr,

	"ref_models.RELATIONGROUP.LONGNAMEAttr": (ref_models.RELATIONGROUP{}).LONGNAMEAttr,

	"ref_models.RELATIONGROUP.Name": (ref_models.RELATIONGROUP{}).Name,

	"ref_models.RELATIONGROUP.SOURCESPECIFICATION": (ref_models.RELATIONGROUP{}).SOURCESPECIFICATION,

	"ref_models.RELATIONGROUP.SPECRELATIONS": (ref_models.RELATIONGROUP{}).SPECRELATIONS,

	"ref_models.RELATIONGROUP.TARGETSPECIFICATION": (ref_models.RELATIONGROUP{}).TARGETSPECIFICATION,

	"ref_models.RELATIONGROUP.TYPE": (ref_models.RELATIONGROUP{}).TYPE,

	"ref_models.RELATIONGROUPTYPE": &(ref_models.RELATIONGROUPTYPE{}),

	"ref_models.RELATIONGROUPTYPE.ALTERNATIVEID": (ref_models.RELATIONGROUPTYPE{}).ALTERNATIVEID,

	"ref_models.RELATIONGROUPTYPE.DESCAttr": (ref_models.RELATIONGROUPTYPE{}).DESCAttr,

	"ref_models.RELATIONGROUPTYPE.IDENTIFIERAttr": (ref_models.RELATIONGROUPTYPE{}).IDENTIFIERAttr,

	"ref_models.RELATIONGROUPTYPE.LASTCHANGEAttr": (ref_models.RELATIONGROUPTYPE{}).LASTCHANGEAttr,

	"ref_models.RELATIONGROUPTYPE.LONGNAMEAttr": (ref_models.RELATIONGROUPTYPE{}).LONGNAMEAttr,

	"ref_models.RELATIONGROUPTYPE.Name": (ref_models.RELATIONGROUPTYPE{}).Name,

	"ref_models.RELATIONGROUPTYPE.SPECATTRIBUTES": (ref_models.RELATIONGROUPTYPE{}).SPECATTRIBUTES,

	"ref_models.REQIF": &(ref_models.REQIF{}),

	"ref_models.REQIF.CORECONTENT": (ref_models.REQIF{}).CORECONTENT,

	"ref_models.REQIF.HEADER": (ref_models.REQIF{}).HEADER,

	"ref_models.REQIF.Name": (ref_models.REQIF{}).Name,

	"ref_models.REQIFCONTENT": &(ref_models.REQIFCONTENT{}),

	"ref_models.REQIFCONTENT.DATATYPES": (ref_models.REQIFCONTENT{}).DATATYPES,

	"ref_models.REQIFCONTENT.Name": (ref_models.REQIFCONTENT{}).Name,

	"ref_models.REQIFCONTENT.SPECIFICATIONS": (ref_models.REQIFCONTENT{}).SPECIFICATIONS,

	"ref_models.REQIFCONTENT.SPECOBJECTS": (ref_models.REQIFCONTENT{}).SPECOBJECTS,

	"ref_models.REQIFCONTENT.SPECRELATIONGROUPS": (ref_models.REQIFCONTENT{}).SPECRELATIONGROUPS,

	"ref_models.REQIFCONTENT.SPECRELATIONS": (ref_models.REQIFCONTENT{}).SPECRELATIONS,

	"ref_models.REQIFCONTENT.SPECTYPES": (ref_models.REQIFCONTENT{}).SPECTYPES,

	"ref_models.REQIFHEADER": &(ref_models.REQIFHEADER{}),

	"ref_models.REQIFHEADER.COMMENT": (ref_models.REQIFHEADER{}).COMMENT,

	"ref_models.REQIFHEADER.CREATIONTIME": (ref_models.REQIFHEADER{}).CREATIONTIME,

	"ref_models.REQIFHEADER.IDENTIFIERAttr": (ref_models.REQIFHEADER{}).IDENTIFIERAttr,

	"ref_models.REQIFHEADER.Name": (ref_models.REQIFHEADER{}).Name,

	"ref_models.REQIFHEADER.REPOSITORYID": (ref_models.REQIFHEADER{}).REPOSITORYID,

	"ref_models.REQIFHEADER.REQIFTOOLID": (ref_models.REQIFHEADER{}).REQIFTOOLID,

	"ref_models.REQIFHEADER.REQIFVERSION": (ref_models.REQIFHEADER{}).REQIFVERSION,

	"ref_models.REQIFHEADER.SOURCETOOLID": (ref_models.REQIFHEADER{}).SOURCETOOLID,

	"ref_models.REQIFHEADER.TITLE": (ref_models.REQIFHEADER{}).TITLE,

	"ref_models.REQIFTOOLEXTENSION": &(ref_models.REQIFTOOLEXTENSION{}),

	"ref_models.REQIFTOOLEXTENSION.Name": (ref_models.REQIFTOOLEXTENSION{}).Name,

	"ref_models.REQIFTYPE": &(ref_models.REQIFTYPE{}),

	"ref_models.REQIFTYPE.DATATYPEDEFINITIONBOOLEANREF": (ref_models.REQIFTYPE{}).DATATYPEDEFINITIONBOOLEANREF,

	"ref_models.REQIFTYPE.Name": (ref_models.REQIFTYPE{}).Name,

	"ref_models.SOURCE": &(ref_models.SOURCE{}),

	"ref_models.SOURCE.Name": (ref_models.SOURCE{}).Name,

	"ref_models.SOURCE.SPECOBJECTREF": (ref_models.SOURCE{}).SPECOBJECTREF,

	"ref_models.SOURCESPECIFICATION": &(ref_models.SOURCESPECIFICATION{}),

	"ref_models.SOURCESPECIFICATION.Name": (ref_models.SOURCESPECIFICATION{}).Name,

	"ref_models.SOURCESPECIFICATION.SPECIFICATIONREF": (ref_models.SOURCESPECIFICATION{}).SPECIFICATIONREF,

	"ref_models.SPECATTRIBUTES": &(ref_models.SPECATTRIBUTES{}),

	"ref_models.SPECATTRIBUTES.ATTRIBUTEDEFINITIONBOOLEAN": (ref_models.SPECATTRIBUTES{}).ATTRIBUTEDEFINITIONBOOLEAN,

	"ref_models.SPECATTRIBUTES.ATTRIBUTEDEFINITIONDATE": (ref_models.SPECATTRIBUTES{}).ATTRIBUTEDEFINITIONDATE,

	"ref_models.SPECATTRIBUTES.ATTRIBUTEDEFINITIONENUMERATION": (ref_models.SPECATTRIBUTES{}).ATTRIBUTEDEFINITIONENUMERATION,

	"ref_models.SPECATTRIBUTES.ATTRIBUTEDEFINITIONINTEGER": (ref_models.SPECATTRIBUTES{}).ATTRIBUTEDEFINITIONINTEGER,

	"ref_models.SPECATTRIBUTES.ATTRIBUTEDEFINITIONREAL": (ref_models.SPECATTRIBUTES{}).ATTRIBUTEDEFINITIONREAL,

	"ref_models.SPECATTRIBUTES.ATTRIBUTEDEFINITIONSTRING": (ref_models.SPECATTRIBUTES{}).ATTRIBUTEDEFINITIONSTRING,

	"ref_models.SPECATTRIBUTES.ATTRIBUTEDEFINITIONXHTML": (ref_models.SPECATTRIBUTES{}).ATTRIBUTEDEFINITIONXHTML,

	"ref_models.SPECATTRIBUTES.Name": (ref_models.SPECATTRIBUTES{}).Name,

	"ref_models.SPECHIERARCHY": &(ref_models.SPECHIERARCHY{}),

	"ref_models.SPECHIERARCHY.ALTERNATIVEID": (ref_models.SPECHIERARCHY{}).ALTERNATIVEID,

	"ref_models.SPECHIERARCHY.CHILDREN": (ref_models.SPECHIERARCHY{}).CHILDREN,

	"ref_models.SPECHIERARCHY.DESCAttr": (ref_models.SPECHIERARCHY{}).DESCAttr,

	"ref_models.SPECHIERARCHY.EDITABLEATTS": (ref_models.SPECHIERARCHY{}).EDITABLEATTS,

	"ref_models.SPECHIERARCHY.IDENTIFIERAttr": (ref_models.SPECHIERARCHY{}).IDENTIFIERAttr,

	"ref_models.SPECHIERARCHY.ISEDITABLEAttr": (ref_models.SPECHIERARCHY{}).ISEDITABLEAttr,

	"ref_models.SPECHIERARCHY.ISTABLEINTERNALAttr": (ref_models.SPECHIERARCHY{}).ISTABLEINTERNALAttr,

	"ref_models.SPECHIERARCHY.LASTCHANGEAttr": (ref_models.SPECHIERARCHY{}).LASTCHANGEAttr,

	"ref_models.SPECHIERARCHY.LONGNAMEAttr": (ref_models.SPECHIERARCHY{}).LONGNAMEAttr,

	"ref_models.SPECHIERARCHY.Name": (ref_models.SPECHIERARCHY{}).Name,

	"ref_models.SPECHIERARCHY.OBJECT": (ref_models.SPECHIERARCHY{}).OBJECT,

	"ref_models.SPECIFICATION": &(ref_models.SPECIFICATION{}),

	"ref_models.SPECIFICATION.ALTERNATIVEID": (ref_models.SPECIFICATION{}).ALTERNATIVEID,

	"ref_models.SPECIFICATION.CHILDREN": (ref_models.SPECIFICATION{}).CHILDREN,

	"ref_models.SPECIFICATION.DESCAttr": (ref_models.SPECIFICATION{}).DESCAttr,

	"ref_models.SPECIFICATION.IDENTIFIERAttr": (ref_models.SPECIFICATION{}).IDENTIFIERAttr,

	"ref_models.SPECIFICATION.LASTCHANGEAttr": (ref_models.SPECIFICATION{}).LASTCHANGEAttr,

	"ref_models.SPECIFICATION.LONGNAMEAttr": (ref_models.SPECIFICATION{}).LONGNAMEAttr,

	"ref_models.SPECIFICATION.Name": (ref_models.SPECIFICATION{}).Name,

	"ref_models.SPECIFICATION.TYPE": (ref_models.SPECIFICATION{}).TYPE,

	"ref_models.SPECIFICATION.VALUES": (ref_models.SPECIFICATION{}).VALUES,

	"ref_models.SPECIFICATIONS": &(ref_models.SPECIFICATIONS{}),

	"ref_models.SPECIFICATIONS.Name": (ref_models.SPECIFICATIONS{}).Name,

	"ref_models.SPECIFICATIONS.SPECIFICATION": (ref_models.SPECIFICATIONS{}).SPECIFICATION,

	"ref_models.SPECIFICATIONTYPE": &(ref_models.SPECIFICATIONTYPE{}),

	"ref_models.SPECIFICATIONTYPE.ALTERNATIVEID": (ref_models.SPECIFICATIONTYPE{}).ALTERNATIVEID,

	"ref_models.SPECIFICATIONTYPE.DESCAttr": (ref_models.SPECIFICATIONTYPE{}).DESCAttr,

	"ref_models.SPECIFICATIONTYPE.IDENTIFIERAttr": (ref_models.SPECIFICATIONTYPE{}).IDENTIFIERAttr,

	"ref_models.SPECIFICATIONTYPE.LASTCHANGEAttr": (ref_models.SPECIFICATIONTYPE{}).LASTCHANGEAttr,

	"ref_models.SPECIFICATIONTYPE.LONGNAMEAttr": (ref_models.SPECIFICATIONTYPE{}).LONGNAMEAttr,

	"ref_models.SPECIFICATIONTYPE.Name": (ref_models.SPECIFICATIONTYPE{}).Name,

	"ref_models.SPECIFICATIONTYPE.SPECATTRIBUTES": (ref_models.SPECIFICATIONTYPE{}).SPECATTRIBUTES,

	"ref_models.SPECIFIEDVALUES": &(ref_models.SPECIFIEDVALUES{}),

	"ref_models.SPECIFIEDVALUES.ENUMVALUE": (ref_models.SPECIFIEDVALUES{}).ENUMVALUE,

	"ref_models.SPECIFIEDVALUES.Name": (ref_models.SPECIFIEDVALUES{}).Name,

	"ref_models.SPECOBJECT": &(ref_models.SPECOBJECT{}),

	"ref_models.SPECOBJECT.ALTERNATIVEID": (ref_models.SPECOBJECT{}).ALTERNATIVEID,

	"ref_models.SPECOBJECT.DESCAttr": (ref_models.SPECOBJECT{}).DESCAttr,

	"ref_models.SPECOBJECT.IDENTIFIERAttr": (ref_models.SPECOBJECT{}).IDENTIFIERAttr,

	"ref_models.SPECOBJECT.LASTCHANGEAttr": (ref_models.SPECOBJECT{}).LASTCHANGEAttr,

	"ref_models.SPECOBJECT.LONGNAMEAttr": (ref_models.SPECOBJECT{}).LONGNAMEAttr,

	"ref_models.SPECOBJECT.Name": (ref_models.SPECOBJECT{}).Name,

	"ref_models.SPECOBJECT.TYPE": (ref_models.SPECOBJECT{}).TYPE,

	"ref_models.SPECOBJECT.VALUES": (ref_models.SPECOBJECT{}).VALUES,

	"ref_models.SPECOBJECTS": &(ref_models.SPECOBJECTS{}),

	"ref_models.SPECOBJECTS.Name": (ref_models.SPECOBJECTS{}).Name,

	"ref_models.SPECOBJECTS.SPECOBJECT": (ref_models.SPECOBJECTS{}).SPECOBJECT,

	"ref_models.SPECOBJECTTYPE": &(ref_models.SPECOBJECTTYPE{}),

	"ref_models.SPECOBJECTTYPE.ALTERNATIVEID": (ref_models.SPECOBJECTTYPE{}).ALTERNATIVEID,

	"ref_models.SPECOBJECTTYPE.DESCAttr": (ref_models.SPECOBJECTTYPE{}).DESCAttr,

	"ref_models.SPECOBJECTTYPE.IDENTIFIERAttr": (ref_models.SPECOBJECTTYPE{}).IDENTIFIERAttr,

	"ref_models.SPECOBJECTTYPE.LASTCHANGEAttr": (ref_models.SPECOBJECTTYPE{}).LASTCHANGEAttr,

	"ref_models.SPECOBJECTTYPE.LONGNAMEAttr": (ref_models.SPECOBJECTTYPE{}).LONGNAMEAttr,

	"ref_models.SPECOBJECTTYPE.Name": (ref_models.SPECOBJECTTYPE{}).Name,

	"ref_models.SPECOBJECTTYPE.SPECATTRIBUTES": (ref_models.SPECOBJECTTYPE{}).SPECATTRIBUTES,

	"ref_models.SPECRELATION": &(ref_models.SPECRELATION{}),

	"ref_models.SPECRELATION.ALTERNATIVEID": (ref_models.SPECRELATION{}).ALTERNATIVEID,

	"ref_models.SPECRELATION.DESCAttr": (ref_models.SPECRELATION{}).DESCAttr,

	"ref_models.SPECRELATION.IDENTIFIERAttr": (ref_models.SPECRELATION{}).IDENTIFIERAttr,

	"ref_models.SPECRELATION.LASTCHANGEAttr": (ref_models.SPECRELATION{}).LASTCHANGEAttr,

	"ref_models.SPECRELATION.LONGNAMEAttr": (ref_models.SPECRELATION{}).LONGNAMEAttr,

	"ref_models.SPECRELATION.Name": (ref_models.SPECRELATION{}).Name,

	"ref_models.SPECRELATION.SOURCE": (ref_models.SPECRELATION{}).SOURCE,

	"ref_models.SPECRELATION.TARGET": (ref_models.SPECRELATION{}).TARGET,

	"ref_models.SPECRELATION.TYPE": (ref_models.SPECRELATION{}).TYPE,

	"ref_models.SPECRELATION.VALUES": (ref_models.SPECRELATION{}).VALUES,

	"ref_models.SPECRELATIONGROUPS": &(ref_models.SPECRELATIONGROUPS{}),

	"ref_models.SPECRELATIONGROUPS.Name": (ref_models.SPECRELATIONGROUPS{}).Name,

	"ref_models.SPECRELATIONGROUPS.RELATIONGROUP": (ref_models.SPECRELATIONGROUPS{}).RELATIONGROUP,

	"ref_models.SPECRELATIONS": &(ref_models.SPECRELATIONS{}),

	"ref_models.SPECRELATIONS.Name": (ref_models.SPECRELATIONS{}).Name,

	"ref_models.SPECRELATIONTYPE": &(ref_models.SPECRELATIONTYPE{}),

	"ref_models.SPECRELATIONTYPE.ALTERNATIVEID": (ref_models.SPECRELATIONTYPE{}).ALTERNATIVEID,

	"ref_models.SPECRELATIONTYPE.DESCAttr": (ref_models.SPECRELATIONTYPE{}).DESCAttr,

	"ref_models.SPECRELATIONTYPE.IDENTIFIERAttr": (ref_models.SPECRELATIONTYPE{}).IDENTIFIERAttr,

	"ref_models.SPECRELATIONTYPE.LASTCHANGEAttr": (ref_models.SPECRELATIONTYPE{}).LASTCHANGEAttr,

	"ref_models.SPECRELATIONTYPE.LONGNAMEAttr": (ref_models.SPECRELATIONTYPE{}).LONGNAMEAttr,

	"ref_models.SPECRELATIONTYPE.Name": (ref_models.SPECRELATIONTYPE{}).Name,

	"ref_models.SPECRELATIONTYPE.SPECATTRIBUTES": (ref_models.SPECRELATIONTYPE{}).SPECATTRIBUTES,

	"ref_models.SPECTYPES": &(ref_models.SPECTYPES{}),

	"ref_models.SPECTYPES.Name": (ref_models.SPECTYPES{}).Name,

	"ref_models.SPECTYPES.RELATIONGROUPTYPE": (ref_models.SPECTYPES{}).RELATIONGROUPTYPE,

	"ref_models.SPECTYPES.SPECIFICATIONTYPE": (ref_models.SPECTYPES{}).SPECIFICATIONTYPE,

	"ref_models.SPECTYPES.SPECOBJECTTYPE": (ref_models.SPECTYPES{}).SPECOBJECTTYPE,

	"ref_models.SPECTYPES.SPECRELATIONTYPE": (ref_models.SPECTYPES{}).SPECRELATIONTYPE,

	"ref_models.TARGET": &(ref_models.TARGET{}),

	"ref_models.TARGET.Name": (ref_models.TARGET{}).Name,

	"ref_models.TARGET.SPECOBJECTREF": (ref_models.TARGET{}).SPECOBJECTREF,

	"ref_models.TARGETSPECIFICATION": &(ref_models.TARGETSPECIFICATION{}),

	"ref_models.TARGETSPECIFICATION.Name": (ref_models.TARGETSPECIFICATION{}).Name,

	"ref_models.TARGETSPECIFICATION.SPECIFICATIONREF": (ref_models.TARGETSPECIFICATION{}).SPECIFICATIONREF,

	"ref_models.THEHEADER": &(ref_models.THEHEADER{}),

	"ref_models.THEHEADER.Name": (ref_models.THEHEADER{}).Name,

	"ref_models.THEHEADER.REQIFHEADER": (ref_models.THEHEADER{}).REQIFHEADER,

	"ref_models.TOOLEXTENSIONS": &(ref_models.TOOLEXTENSIONS{}),

	"ref_models.TOOLEXTENSIONS.Name": (ref_models.TOOLEXTENSIONS{}).Name,

	"ref_models.TOOLEXTENSIONS.REQIFTOOLEXTENSION": (ref_models.TOOLEXTENSIONS{}).REQIFTOOLEXTENSION,

	"ref_models.VALUES": &(ref_models.VALUES{}),

	"ref_models.VALUES.Name": (ref_models.VALUES{}).Name,

	"ref_models.XHTMLCONTENT": &(ref_models.XHTMLCONTENT{}),

	"ref_models.XHTMLCONTENT.Name": (ref_models.XHTMLCONTENT{}).Name,
}

// function will stage objects
func _(stage *models.StageStruct) {

	// Declaration of instances to stage

	__Classdiagram__000000_Default := (&models.Classdiagram{Name: `Default`}).Stage(stage)

	__GongStructShape__000000_Default_DATATYPEDEFINITIONXHTML := (&models.GongStructShape{Name: `Default-DATATYPEDEFINITIONXHTML`}).Stage(stage)
	__GongStructShape__000001_Default_DATATYPES := (&models.GongStructShape{Name: `Default-DATATYPES`}).Stage(stage)
	__GongStructShape__000002_Default_DEFAULTVALUE := (&models.GongStructShape{Name: `Default-DEFAULTVALUE`}).Stage(stage)
	__GongStructShape__000003_Default_DEFINITION := (&models.GongStructShape{Name: `Default-DEFINITION`}).Stage(stage)
	__GongStructShape__000004_Default_EDITABLEATTS := (&models.GongStructShape{Name: `Default-EDITABLEATTS`}).Stage(stage)
	__GongStructShape__000005_Default_EMBEDDEDVALUE := (&models.GongStructShape{Name: `Default-EMBEDDEDVALUE`}).Stage(stage)
	__GongStructShape__000006_Default_ENUMVALUE := (&models.GongStructShape{Name: `Default-ENUMVALUE`}).Stage(stage)
	__GongStructShape__000007_Default_OBJECT := (&models.GongStructShape{Name: `Default-OBJECT`}).Stage(stage)
	__GongStructShape__000008_Default_PROPERTIES := (&models.GongStructShape{Name: `Default-PROPERTIES`}).Stage(stage)
	__GongStructShape__000009_Default_RELATIONGROUP := (&models.GongStructShape{Name: `Default-RELATIONGROUP`}).Stage(stage)
	__GongStructShape__000010_Default_RELATIONGROUPTYPE := (&models.GongStructShape{Name: `Default-RELATIONGROUPTYPE`}).Stage(stage)
	__GongStructShape__000011_Default_REQIF := (&models.GongStructShape{Name: `Default-REQIF`}).Stage(stage)
	__GongStructShape__000012_Default_REQIFCONTENT := (&models.GongStructShape{Name: `Default-REQIFCONTENT`}).Stage(stage)
	__GongStructShape__000013_Default_REQIFHEADER := (&models.GongStructShape{Name: `Default-REQIFHEADER`}).Stage(stage)
	__GongStructShape__000014_Default_REQIFTOOLEXTENSION := (&models.GongStructShape{Name: `Default-REQIFTOOLEXTENSION`}).Stage(stage)
	__GongStructShape__000015_Default_REQIFTYPE := (&models.GongStructShape{Name: `Default-REQIFTYPE`}).Stage(stage)
	__GongStructShape__000016_Default_SOURCE := (&models.GongStructShape{Name: `Default-SOURCE`}).Stage(stage)
	__GongStructShape__000017_Default_SOURCESPECIFICATION := (&models.GongStructShape{Name: `Default-SOURCESPECIFICATION`}).Stage(stage)
	__GongStructShape__000018_Default_SPECATTRIBUTES := (&models.GongStructShape{Name: `Default-SPECATTRIBUTES`}).Stage(stage)
	__GongStructShape__000019_Default_SPECHIERARCHY := (&models.GongStructShape{Name: `Default-SPECHIERARCHY`}).Stage(stage)
	__GongStructShape__000020_Default_SPECIFICATION := (&models.GongStructShape{Name: `Default-SPECIFICATION`}).Stage(stage)
	__GongStructShape__000021_Default_SPECIFICATIONS := (&models.GongStructShape{Name: `Default-SPECIFICATIONS`}).Stage(stage)
	__GongStructShape__000022_Default_SPECIFICATIONTYPE := (&models.GongStructShape{Name: `Default-SPECIFICATIONTYPE`}).Stage(stage)
	__GongStructShape__000023_Default_SPECIFIEDVALUES := (&models.GongStructShape{Name: `Default-SPECIFIEDVALUES`}).Stage(stage)
	__GongStructShape__000024_Default_SPECOBJECT := (&models.GongStructShape{Name: `Default-SPECOBJECT`}).Stage(stage)
	__GongStructShape__000025_Default_SPECOBJECTS := (&models.GongStructShape{Name: `Default-SPECOBJECTS`}).Stage(stage)
	__GongStructShape__000026_Default_SPECOBJECTTYPE := (&models.GongStructShape{Name: `Default-SPECOBJECTTYPE`}).Stage(stage)
	__GongStructShape__000027_Default_SPECRELATION := (&models.GongStructShape{Name: `Default-SPECRELATION`}).Stage(stage)
	__GongStructShape__000028_Default_SPECRELATIONGROUPS := (&models.GongStructShape{Name: `Default-SPECRELATIONGROUPS`}).Stage(stage)
	__GongStructShape__000029_Default_SPECRELATIONS := (&models.GongStructShape{Name: `Default-SPECRELATIONS`}).Stage(stage)
	__GongStructShape__000030_Default_SPECRELATIONTYPE := (&models.GongStructShape{Name: `Default-SPECRELATIONTYPE`}).Stage(stage)
	__GongStructShape__000031_Default_SPECTYPES := (&models.GongStructShape{Name: `Default-SPECTYPES`}).Stage(stage)
	__GongStructShape__000032_Default_TARGET := (&models.GongStructShape{Name: `Default-TARGET`}).Stage(stage)
	__GongStructShape__000033_Default_TARGETSPECIFICATION := (&models.GongStructShape{Name: `Default-TARGETSPECIFICATION`}).Stage(stage)
	__GongStructShape__000034_Default_THEHEADER := (&models.GongStructShape{Name: `Default-THEHEADER`}).Stage(stage)
	__GongStructShape__000035_Default_TOOLEXTENSIONS := (&models.GongStructShape{Name: `Default-TOOLEXTENSIONS`}).Stage(stage)
	__GongStructShape__000036_Default_VALUES := (&models.GongStructShape{Name: `Default-VALUES`}).Stage(stage)
	__GongStructShape__000037_Default_XHTMLCONTENT := (&models.GongStructShape{Name: `Default-XHTMLCONTENT`}).Stage(stage)

	__Link__000000_HEADER := (&models.Link{Name: `HEADER`}).Stage(stage)

	__Position__000000_Pos_Default_DATATYPEDEFINITIONXHTML := (&models.Position{Name: `Pos-Default-DATATYPEDEFINITIONXHTML`}).Stage(stage)
	__Position__000001_Pos_Default_DATATYPES := (&models.Position{Name: `Pos-Default-DATATYPES`}).Stage(stage)
	__Position__000002_Pos_Default_DEFAULTVALUE := (&models.Position{Name: `Pos-Default-DEFAULTVALUE`}).Stage(stage)
	__Position__000003_Pos_Default_DEFINITION := (&models.Position{Name: `Pos-Default-DEFINITION`}).Stage(stage)
	__Position__000004_Pos_Default_EDITABLEATTS := (&models.Position{Name: `Pos-Default-EDITABLEATTS`}).Stage(stage)
	__Position__000005_Pos_Default_EMBEDDEDVALUE := (&models.Position{Name: `Pos-Default-EMBEDDEDVALUE`}).Stage(stage)
	__Position__000006_Pos_Default_ENUMVALUE := (&models.Position{Name: `Pos-Default-ENUMVALUE`}).Stage(stage)
	__Position__000007_Pos_Default_OBJECT := (&models.Position{Name: `Pos-Default-OBJECT`}).Stage(stage)
	__Position__000008_Pos_Default_PROPERTIES := (&models.Position{Name: `Pos-Default-PROPERTIES`}).Stage(stage)
	__Position__000009_Pos_Default_RELATIONGROUP := (&models.Position{Name: `Pos-Default-RELATIONGROUP`}).Stage(stage)
	__Position__000010_Pos_Default_RELATIONGROUPTYPE := (&models.Position{Name: `Pos-Default-RELATIONGROUPTYPE`}).Stage(stage)
	__Position__000011_Pos_Default_REQIF := (&models.Position{Name: `Pos-Default-REQIF`}).Stage(stage)
	__Position__000012_Pos_Default_REQIFCONTENT := (&models.Position{Name: `Pos-Default-REQIFCONTENT`}).Stage(stage)
	__Position__000013_Pos_Default_REQIFHEADER := (&models.Position{Name: `Pos-Default-REQIFHEADER`}).Stage(stage)
	__Position__000014_Pos_Default_REQIFTOOLEXTENSION := (&models.Position{Name: `Pos-Default-REQIFTOOLEXTENSION`}).Stage(stage)
	__Position__000015_Pos_Default_REQIFTYPE := (&models.Position{Name: `Pos-Default-REQIFTYPE`}).Stage(stage)
	__Position__000016_Pos_Default_SOURCE := (&models.Position{Name: `Pos-Default-SOURCE`}).Stage(stage)
	__Position__000017_Pos_Default_SOURCESPECIFICATION := (&models.Position{Name: `Pos-Default-SOURCESPECIFICATION`}).Stage(stage)
	__Position__000018_Pos_Default_SPECATTRIBUTES := (&models.Position{Name: `Pos-Default-SPECATTRIBUTES`}).Stage(stage)
	__Position__000019_Pos_Default_SPECHIERARCHY := (&models.Position{Name: `Pos-Default-SPECHIERARCHY`}).Stage(stage)
	__Position__000020_Pos_Default_SPECIFICATION := (&models.Position{Name: `Pos-Default-SPECIFICATION`}).Stage(stage)
	__Position__000021_Pos_Default_SPECIFICATIONS := (&models.Position{Name: `Pos-Default-SPECIFICATIONS`}).Stage(stage)
	__Position__000022_Pos_Default_SPECIFICATIONTYPE := (&models.Position{Name: `Pos-Default-SPECIFICATIONTYPE`}).Stage(stage)
	__Position__000023_Pos_Default_SPECIFIEDVALUES := (&models.Position{Name: `Pos-Default-SPECIFIEDVALUES`}).Stage(stage)
	__Position__000024_Pos_Default_SPECOBJECT := (&models.Position{Name: `Pos-Default-SPECOBJECT`}).Stage(stage)
	__Position__000025_Pos_Default_SPECOBJECTS := (&models.Position{Name: `Pos-Default-SPECOBJECTS`}).Stage(stage)
	__Position__000026_Pos_Default_SPECOBJECTTYPE := (&models.Position{Name: `Pos-Default-SPECOBJECTTYPE`}).Stage(stage)
	__Position__000027_Pos_Default_SPECRELATION := (&models.Position{Name: `Pos-Default-SPECRELATION`}).Stage(stage)
	__Position__000028_Pos_Default_SPECRELATIONGROUPS := (&models.Position{Name: `Pos-Default-SPECRELATIONGROUPS`}).Stage(stage)
	__Position__000029_Pos_Default_SPECRELATIONS := (&models.Position{Name: `Pos-Default-SPECRELATIONS`}).Stage(stage)
	__Position__000030_Pos_Default_SPECRELATIONTYPE := (&models.Position{Name: `Pos-Default-SPECRELATIONTYPE`}).Stage(stage)
	__Position__000031_Pos_Default_SPECTYPES := (&models.Position{Name: `Pos-Default-SPECTYPES`}).Stage(stage)
	__Position__000032_Pos_Default_TARGET := (&models.Position{Name: `Pos-Default-TARGET`}).Stage(stage)
	__Position__000033_Pos_Default_TARGETSPECIFICATION := (&models.Position{Name: `Pos-Default-TARGETSPECIFICATION`}).Stage(stage)
	__Position__000034_Pos_Default_THEHEADER := (&models.Position{Name: `Pos-Default-THEHEADER`}).Stage(stage)
	__Position__000035_Pos_Default_TOOLEXTENSIONS := (&models.Position{Name: `Pos-Default-TOOLEXTENSIONS`}).Stage(stage)
	__Position__000036_Pos_Default_VALUES := (&models.Position{Name: `Pos-Default-VALUES`}).Stage(stage)
	__Position__000037_Pos_Default_XHTMLCONTENT := (&models.Position{Name: `Pos-Default-XHTMLCONTENT`}).Stage(stage)

	__Vertice__000000_Verticle_in_class_diagram_Default_in_middle_between_Default_REQIF_and_Default_THEHEADER := (&models.Vertice{Name: `Verticle in class diagram Default in middle between Default-REQIF and Default-THEHEADER`}).Stage(stage)

	// Setup of values

	__Classdiagram__000000_Default.Name = `Default`
	__Classdiagram__000000_Default.IsInDrawMode = false

	__GongStructShape__000000_Default_DATATYPEDEFINITIONXHTML.Name = `Default-DATATYPEDEFINITIONXHTML`

	//gong:ident [ref_models.DATATYPEDEFINITIONXHTML] comment added to overcome the problem with the comment map association
	__GongStructShape__000000_Default_DATATYPEDEFINITIONXHTML.Identifier = `ref_models.DATATYPEDEFINITIONXHTML`
	__GongStructShape__000000_Default_DATATYPEDEFINITIONXHTML.ShowNbInstances = false
	__GongStructShape__000000_Default_DATATYPEDEFINITIONXHTML.NbInstances = 0
	__GongStructShape__000000_Default_DATATYPEDEFINITIONXHTML.Width = 240.000000
	__GongStructShape__000000_Default_DATATYPEDEFINITIONXHTML.Height = 63.000000
	__GongStructShape__000000_Default_DATATYPEDEFINITIONXHTML.IsSelected = false

	__GongStructShape__000001_Default_DATATYPES.Name = `Default-DATATYPES`

	//gong:ident [ref_models.DATATYPES] comment added to overcome the problem with the comment map association
	__GongStructShape__000001_Default_DATATYPES.Identifier = `ref_models.DATATYPES`
	__GongStructShape__000001_Default_DATATYPES.ShowNbInstances = false
	__GongStructShape__000001_Default_DATATYPES.NbInstances = 0
	__GongStructShape__000001_Default_DATATYPES.Width = 240.000000
	__GongStructShape__000001_Default_DATATYPES.Height = 63.000000
	__GongStructShape__000001_Default_DATATYPES.IsSelected = false

	__GongStructShape__000002_Default_DEFAULTVALUE.Name = `Default-DEFAULTVALUE`

	//gong:ident [ref_models.DEFAULTVALUE] comment added to overcome the problem with the comment map association
	__GongStructShape__000002_Default_DEFAULTVALUE.Identifier = `ref_models.DEFAULTVALUE`
	__GongStructShape__000002_Default_DEFAULTVALUE.ShowNbInstances = false
	__GongStructShape__000002_Default_DEFAULTVALUE.NbInstances = 0
	__GongStructShape__000002_Default_DEFAULTVALUE.Width = 240.000000
	__GongStructShape__000002_Default_DEFAULTVALUE.Height = 63.000000
	__GongStructShape__000002_Default_DEFAULTVALUE.IsSelected = false

	__GongStructShape__000003_Default_DEFINITION.Name = `Default-DEFINITION`

	//gong:ident [ref_models.DEFINITION] comment added to overcome the problem with the comment map association
	__GongStructShape__000003_Default_DEFINITION.Identifier = `ref_models.DEFINITION`
	__GongStructShape__000003_Default_DEFINITION.ShowNbInstances = false
	__GongStructShape__000003_Default_DEFINITION.NbInstances = 0
	__GongStructShape__000003_Default_DEFINITION.Width = 240.000000
	__GongStructShape__000003_Default_DEFINITION.Height = 63.000000
	__GongStructShape__000003_Default_DEFINITION.IsSelected = false

	__GongStructShape__000004_Default_EDITABLEATTS.Name = `Default-EDITABLEATTS`

	//gong:ident [ref_models.EDITABLEATTS] comment added to overcome the problem with the comment map association
	__GongStructShape__000004_Default_EDITABLEATTS.Identifier = `ref_models.EDITABLEATTS`
	__GongStructShape__000004_Default_EDITABLEATTS.ShowNbInstances = false
	__GongStructShape__000004_Default_EDITABLEATTS.NbInstances = 0
	__GongStructShape__000004_Default_EDITABLEATTS.Width = 240.000000
	__GongStructShape__000004_Default_EDITABLEATTS.Height = 63.000000
	__GongStructShape__000004_Default_EDITABLEATTS.IsSelected = false

	__GongStructShape__000005_Default_EMBEDDEDVALUE.Name = `Default-EMBEDDEDVALUE`

	//gong:ident [ref_models.EMBEDDEDVALUE] comment added to overcome the problem with the comment map association
	__GongStructShape__000005_Default_EMBEDDEDVALUE.Identifier = `ref_models.EMBEDDEDVALUE`
	__GongStructShape__000005_Default_EMBEDDEDVALUE.ShowNbInstances = false
	__GongStructShape__000005_Default_EMBEDDEDVALUE.NbInstances = 0
	__GongStructShape__000005_Default_EMBEDDEDVALUE.Width = 240.000000
	__GongStructShape__000005_Default_EMBEDDEDVALUE.Height = 63.000000
	__GongStructShape__000005_Default_EMBEDDEDVALUE.IsSelected = false

	__GongStructShape__000006_Default_ENUMVALUE.Name = `Default-ENUMVALUE`

	//gong:ident [ref_models.ENUMVALUE] comment added to overcome the problem with the comment map association
	__GongStructShape__000006_Default_ENUMVALUE.Identifier = `ref_models.ENUMVALUE`
	__GongStructShape__000006_Default_ENUMVALUE.ShowNbInstances = false
	__GongStructShape__000006_Default_ENUMVALUE.NbInstances = 0
	__GongStructShape__000006_Default_ENUMVALUE.Width = 240.000000
	__GongStructShape__000006_Default_ENUMVALUE.Height = 63.000000
	__GongStructShape__000006_Default_ENUMVALUE.IsSelected = false

	__GongStructShape__000007_Default_OBJECT.Name = `Default-OBJECT`

	//gong:ident [ref_models.OBJECT] comment added to overcome the problem with the comment map association
	__GongStructShape__000007_Default_OBJECT.Identifier = `ref_models.OBJECT`
	__GongStructShape__000007_Default_OBJECT.ShowNbInstances = false
	__GongStructShape__000007_Default_OBJECT.NbInstances = 0
	__GongStructShape__000007_Default_OBJECT.Width = 240.000000
	__GongStructShape__000007_Default_OBJECT.Height = 63.000000
	__GongStructShape__000007_Default_OBJECT.IsSelected = false

	__GongStructShape__000008_Default_PROPERTIES.Name = `Default-PROPERTIES`

	//gong:ident [ref_models.PROPERTIES] comment added to overcome the problem with the comment map association
	__GongStructShape__000008_Default_PROPERTIES.Identifier = `ref_models.PROPERTIES`
	__GongStructShape__000008_Default_PROPERTIES.ShowNbInstances = false
	__GongStructShape__000008_Default_PROPERTIES.NbInstances = 0
	__GongStructShape__000008_Default_PROPERTIES.Width = 240.000000
	__GongStructShape__000008_Default_PROPERTIES.Height = 63.000000
	__GongStructShape__000008_Default_PROPERTIES.IsSelected = false

	__GongStructShape__000009_Default_RELATIONGROUP.Name = `Default-RELATIONGROUP`

	//gong:ident [ref_models.RELATIONGROUP] comment added to overcome the problem with the comment map association
	__GongStructShape__000009_Default_RELATIONGROUP.Identifier = `ref_models.RELATIONGROUP`
	__GongStructShape__000009_Default_RELATIONGROUP.ShowNbInstances = false
	__GongStructShape__000009_Default_RELATIONGROUP.NbInstances = 0
	__GongStructShape__000009_Default_RELATIONGROUP.Width = 240.000000
	__GongStructShape__000009_Default_RELATIONGROUP.Height = 63.000000
	__GongStructShape__000009_Default_RELATIONGROUP.IsSelected = false

	__GongStructShape__000010_Default_RELATIONGROUPTYPE.Name = `Default-RELATIONGROUPTYPE`

	//gong:ident [ref_models.RELATIONGROUPTYPE] comment added to overcome the problem with the comment map association
	__GongStructShape__000010_Default_RELATIONGROUPTYPE.Identifier = `ref_models.RELATIONGROUPTYPE`
	__GongStructShape__000010_Default_RELATIONGROUPTYPE.ShowNbInstances = false
	__GongStructShape__000010_Default_RELATIONGROUPTYPE.NbInstances = 0
	__GongStructShape__000010_Default_RELATIONGROUPTYPE.Width = 240.000000
	__GongStructShape__000010_Default_RELATIONGROUPTYPE.Height = 63.000000
	__GongStructShape__000010_Default_RELATIONGROUPTYPE.IsSelected = false

	__GongStructShape__000011_Default_REQIF.Name = `Default-REQIF`

	//gong:ident [ref_models.REQIF] comment added to overcome the problem with the comment map association
	__GongStructShape__000011_Default_REQIF.Identifier = `ref_models.REQIF`
	__GongStructShape__000011_Default_REQIF.ShowNbInstances = false
	__GongStructShape__000011_Default_REQIF.NbInstances = 0
	__GongStructShape__000011_Default_REQIF.Width = 240.000000
	__GongStructShape__000011_Default_REQIF.Height = 63.000000
	__GongStructShape__000011_Default_REQIF.IsSelected = false

	__GongStructShape__000012_Default_REQIFCONTENT.Name = `Default-REQIFCONTENT`

	//gong:ident [ref_models.REQIFCONTENT] comment added to overcome the problem with the comment map association
	__GongStructShape__000012_Default_REQIFCONTENT.Identifier = `ref_models.REQIFCONTENT`
	__GongStructShape__000012_Default_REQIFCONTENT.ShowNbInstances = false
	__GongStructShape__000012_Default_REQIFCONTENT.NbInstances = 0
	__GongStructShape__000012_Default_REQIFCONTENT.Width = 240.000000
	__GongStructShape__000012_Default_REQIFCONTENT.Height = 63.000000
	__GongStructShape__000012_Default_REQIFCONTENT.IsSelected = false

	__GongStructShape__000013_Default_REQIFHEADER.Name = `Default-REQIFHEADER`

	//gong:ident [ref_models.REQIFHEADER] comment added to overcome the problem with the comment map association
	__GongStructShape__000013_Default_REQIFHEADER.Identifier = `ref_models.REQIFHEADER`
	__GongStructShape__000013_Default_REQIFHEADER.ShowNbInstances = false
	__GongStructShape__000013_Default_REQIFHEADER.NbInstances = 0
	__GongStructShape__000013_Default_REQIFHEADER.Width = 240.000000
	__GongStructShape__000013_Default_REQIFHEADER.Height = 63.000000
	__GongStructShape__000013_Default_REQIFHEADER.IsSelected = false

	__GongStructShape__000014_Default_REQIFTOOLEXTENSION.Name = `Default-REQIFTOOLEXTENSION`

	//gong:ident [ref_models.REQIFTOOLEXTENSION] comment added to overcome the problem with the comment map association
	__GongStructShape__000014_Default_REQIFTOOLEXTENSION.Identifier = `ref_models.REQIFTOOLEXTENSION`
	__GongStructShape__000014_Default_REQIFTOOLEXTENSION.ShowNbInstances = false
	__GongStructShape__000014_Default_REQIFTOOLEXTENSION.NbInstances = 0
	__GongStructShape__000014_Default_REQIFTOOLEXTENSION.Width = 240.000000
	__GongStructShape__000014_Default_REQIFTOOLEXTENSION.Height = 63.000000
	__GongStructShape__000014_Default_REQIFTOOLEXTENSION.IsSelected = false

	__GongStructShape__000015_Default_REQIFTYPE.Name = `Default-REQIFTYPE`

	//gong:ident [ref_models.REQIFTYPE] comment added to overcome the problem with the comment map association
	__GongStructShape__000015_Default_REQIFTYPE.Identifier = `ref_models.REQIFTYPE`
	__GongStructShape__000015_Default_REQIFTYPE.ShowNbInstances = false
	__GongStructShape__000015_Default_REQIFTYPE.NbInstances = 0
	__GongStructShape__000015_Default_REQIFTYPE.Width = 240.000000
	__GongStructShape__000015_Default_REQIFTYPE.Height = 63.000000
	__GongStructShape__000015_Default_REQIFTYPE.IsSelected = false

	__GongStructShape__000016_Default_SOURCE.Name = `Default-SOURCE`

	//gong:ident [ref_models.SOURCE] comment added to overcome the problem with the comment map association
	__GongStructShape__000016_Default_SOURCE.Identifier = `ref_models.SOURCE`
	__GongStructShape__000016_Default_SOURCE.ShowNbInstances = false
	__GongStructShape__000016_Default_SOURCE.NbInstances = 0
	__GongStructShape__000016_Default_SOURCE.Width = 240.000000
	__GongStructShape__000016_Default_SOURCE.Height = 63.000000
	__GongStructShape__000016_Default_SOURCE.IsSelected = false

	__GongStructShape__000017_Default_SOURCESPECIFICATION.Name = `Default-SOURCESPECIFICATION`

	//gong:ident [ref_models.SOURCESPECIFICATION] comment added to overcome the problem with the comment map association
	__GongStructShape__000017_Default_SOURCESPECIFICATION.Identifier = `ref_models.SOURCESPECIFICATION`
	__GongStructShape__000017_Default_SOURCESPECIFICATION.ShowNbInstances = false
	__GongStructShape__000017_Default_SOURCESPECIFICATION.NbInstances = 0
	__GongStructShape__000017_Default_SOURCESPECIFICATION.Width = 240.000000
	__GongStructShape__000017_Default_SOURCESPECIFICATION.Height = 63.000000
	__GongStructShape__000017_Default_SOURCESPECIFICATION.IsSelected = false

	__GongStructShape__000018_Default_SPECATTRIBUTES.Name = `Default-SPECATTRIBUTES`

	//gong:ident [ref_models.SPECATTRIBUTES] comment added to overcome the problem with the comment map association
	__GongStructShape__000018_Default_SPECATTRIBUTES.Identifier = `ref_models.SPECATTRIBUTES`
	__GongStructShape__000018_Default_SPECATTRIBUTES.ShowNbInstances = false
	__GongStructShape__000018_Default_SPECATTRIBUTES.NbInstances = 0
	__GongStructShape__000018_Default_SPECATTRIBUTES.Width = 240.000000
	__GongStructShape__000018_Default_SPECATTRIBUTES.Height = 63.000000
	__GongStructShape__000018_Default_SPECATTRIBUTES.IsSelected = false

	__GongStructShape__000019_Default_SPECHIERARCHY.Name = `Default-SPECHIERARCHY`

	//gong:ident [ref_models.SPECHIERARCHY] comment added to overcome the problem with the comment map association
	__GongStructShape__000019_Default_SPECHIERARCHY.Identifier = `ref_models.SPECHIERARCHY`
	__GongStructShape__000019_Default_SPECHIERARCHY.ShowNbInstances = false
	__GongStructShape__000019_Default_SPECHIERARCHY.NbInstances = 0
	__GongStructShape__000019_Default_SPECHIERARCHY.Width = 240.000000
	__GongStructShape__000019_Default_SPECHIERARCHY.Height = 63.000000
	__GongStructShape__000019_Default_SPECHIERARCHY.IsSelected = false

	__GongStructShape__000020_Default_SPECIFICATION.Name = `Default-SPECIFICATION`

	//gong:ident [ref_models.SPECIFICATION] comment added to overcome the problem with the comment map association
	__GongStructShape__000020_Default_SPECIFICATION.Identifier = `ref_models.SPECIFICATION`
	__GongStructShape__000020_Default_SPECIFICATION.ShowNbInstances = false
	__GongStructShape__000020_Default_SPECIFICATION.NbInstances = 0
	__GongStructShape__000020_Default_SPECIFICATION.Width = 240.000000
	__GongStructShape__000020_Default_SPECIFICATION.Height = 63.000000
	__GongStructShape__000020_Default_SPECIFICATION.IsSelected = false

	__GongStructShape__000021_Default_SPECIFICATIONS.Name = `Default-SPECIFICATIONS`

	//gong:ident [ref_models.SPECIFICATIONS] comment added to overcome the problem with the comment map association
	__GongStructShape__000021_Default_SPECIFICATIONS.Identifier = `ref_models.SPECIFICATIONS`
	__GongStructShape__000021_Default_SPECIFICATIONS.ShowNbInstances = false
	__GongStructShape__000021_Default_SPECIFICATIONS.NbInstances = 0
	__GongStructShape__000021_Default_SPECIFICATIONS.Width = 240.000000
	__GongStructShape__000021_Default_SPECIFICATIONS.Height = 63.000000
	__GongStructShape__000021_Default_SPECIFICATIONS.IsSelected = false

	__GongStructShape__000022_Default_SPECIFICATIONTYPE.Name = `Default-SPECIFICATIONTYPE`

	//gong:ident [ref_models.SPECIFICATIONTYPE] comment added to overcome the problem with the comment map association
	__GongStructShape__000022_Default_SPECIFICATIONTYPE.Identifier = `ref_models.SPECIFICATIONTYPE`
	__GongStructShape__000022_Default_SPECIFICATIONTYPE.ShowNbInstances = false
	__GongStructShape__000022_Default_SPECIFICATIONTYPE.NbInstances = 0
	__GongStructShape__000022_Default_SPECIFICATIONTYPE.Width = 240.000000
	__GongStructShape__000022_Default_SPECIFICATIONTYPE.Height = 63.000000
	__GongStructShape__000022_Default_SPECIFICATIONTYPE.IsSelected = false

	__GongStructShape__000023_Default_SPECIFIEDVALUES.Name = `Default-SPECIFIEDVALUES`

	//gong:ident [ref_models.SPECIFIEDVALUES] comment added to overcome the problem with the comment map association
	__GongStructShape__000023_Default_SPECIFIEDVALUES.Identifier = `ref_models.SPECIFIEDVALUES`
	__GongStructShape__000023_Default_SPECIFIEDVALUES.ShowNbInstances = false
	__GongStructShape__000023_Default_SPECIFIEDVALUES.NbInstances = 0
	__GongStructShape__000023_Default_SPECIFIEDVALUES.Width = 240.000000
	__GongStructShape__000023_Default_SPECIFIEDVALUES.Height = 63.000000
	__GongStructShape__000023_Default_SPECIFIEDVALUES.IsSelected = false

	__GongStructShape__000024_Default_SPECOBJECT.Name = `Default-SPECOBJECT`

	//gong:ident [ref_models.SPECOBJECT] comment added to overcome the problem with the comment map association
	__GongStructShape__000024_Default_SPECOBJECT.Identifier = `ref_models.SPECOBJECT`
	__GongStructShape__000024_Default_SPECOBJECT.ShowNbInstances = false
	__GongStructShape__000024_Default_SPECOBJECT.NbInstances = 0
	__GongStructShape__000024_Default_SPECOBJECT.Width = 240.000000
	__GongStructShape__000024_Default_SPECOBJECT.Height = 63.000000
	__GongStructShape__000024_Default_SPECOBJECT.IsSelected = false

	__GongStructShape__000025_Default_SPECOBJECTS.Name = `Default-SPECOBJECTS`

	//gong:ident [ref_models.SPECOBJECTS] comment added to overcome the problem with the comment map association
	__GongStructShape__000025_Default_SPECOBJECTS.Identifier = `ref_models.SPECOBJECTS`
	__GongStructShape__000025_Default_SPECOBJECTS.ShowNbInstances = false
	__GongStructShape__000025_Default_SPECOBJECTS.NbInstances = 0
	__GongStructShape__000025_Default_SPECOBJECTS.Width = 240.000000
	__GongStructShape__000025_Default_SPECOBJECTS.Height = 63.000000
	__GongStructShape__000025_Default_SPECOBJECTS.IsSelected = false

	__GongStructShape__000026_Default_SPECOBJECTTYPE.Name = `Default-SPECOBJECTTYPE`

	//gong:ident [ref_models.SPECOBJECTTYPE] comment added to overcome the problem with the comment map association
	__GongStructShape__000026_Default_SPECOBJECTTYPE.Identifier = `ref_models.SPECOBJECTTYPE`
	__GongStructShape__000026_Default_SPECOBJECTTYPE.ShowNbInstances = false
	__GongStructShape__000026_Default_SPECOBJECTTYPE.NbInstances = 0
	__GongStructShape__000026_Default_SPECOBJECTTYPE.Width = 240.000000
	__GongStructShape__000026_Default_SPECOBJECTTYPE.Height = 63.000000
	__GongStructShape__000026_Default_SPECOBJECTTYPE.IsSelected = false

	__GongStructShape__000027_Default_SPECRELATION.Name = `Default-SPECRELATION`

	//gong:ident [ref_models.SPECRELATION] comment added to overcome the problem with the comment map association
	__GongStructShape__000027_Default_SPECRELATION.Identifier = `ref_models.SPECRELATION`
	__GongStructShape__000027_Default_SPECRELATION.ShowNbInstances = false
	__GongStructShape__000027_Default_SPECRELATION.NbInstances = 0
	__GongStructShape__000027_Default_SPECRELATION.Width = 240.000000
	__GongStructShape__000027_Default_SPECRELATION.Height = 63.000000
	__GongStructShape__000027_Default_SPECRELATION.IsSelected = false

	__GongStructShape__000028_Default_SPECRELATIONGROUPS.Name = `Default-SPECRELATIONGROUPS`

	//gong:ident [ref_models.SPECRELATIONGROUPS] comment added to overcome the problem with the comment map association
	__GongStructShape__000028_Default_SPECRELATIONGROUPS.Identifier = `ref_models.SPECRELATIONGROUPS`
	__GongStructShape__000028_Default_SPECRELATIONGROUPS.ShowNbInstances = false
	__GongStructShape__000028_Default_SPECRELATIONGROUPS.NbInstances = 0
	__GongStructShape__000028_Default_SPECRELATIONGROUPS.Width = 240.000000
	__GongStructShape__000028_Default_SPECRELATIONGROUPS.Height = 63.000000
	__GongStructShape__000028_Default_SPECRELATIONGROUPS.IsSelected = false

	__GongStructShape__000029_Default_SPECRELATIONS.Name = `Default-SPECRELATIONS`

	//gong:ident [ref_models.SPECRELATIONS] comment added to overcome the problem with the comment map association
	__GongStructShape__000029_Default_SPECRELATIONS.Identifier = `ref_models.SPECRELATIONS`
	__GongStructShape__000029_Default_SPECRELATIONS.ShowNbInstances = false
	__GongStructShape__000029_Default_SPECRELATIONS.NbInstances = 0
	__GongStructShape__000029_Default_SPECRELATIONS.Width = 240.000000
	__GongStructShape__000029_Default_SPECRELATIONS.Height = 63.000000
	__GongStructShape__000029_Default_SPECRELATIONS.IsSelected = false

	__GongStructShape__000030_Default_SPECRELATIONTYPE.Name = `Default-SPECRELATIONTYPE`

	//gong:ident [ref_models.SPECRELATIONTYPE] comment added to overcome the problem with the comment map association
	__GongStructShape__000030_Default_SPECRELATIONTYPE.Identifier = `ref_models.SPECRELATIONTYPE`
	__GongStructShape__000030_Default_SPECRELATIONTYPE.ShowNbInstances = false
	__GongStructShape__000030_Default_SPECRELATIONTYPE.NbInstances = 0
	__GongStructShape__000030_Default_SPECRELATIONTYPE.Width = 240.000000
	__GongStructShape__000030_Default_SPECRELATIONTYPE.Height = 63.000000
	__GongStructShape__000030_Default_SPECRELATIONTYPE.IsSelected = false

	__GongStructShape__000031_Default_SPECTYPES.Name = `Default-SPECTYPES`

	//gong:ident [ref_models.SPECTYPES] comment added to overcome the problem with the comment map association
	__GongStructShape__000031_Default_SPECTYPES.Identifier = `ref_models.SPECTYPES`
	__GongStructShape__000031_Default_SPECTYPES.ShowNbInstances = false
	__GongStructShape__000031_Default_SPECTYPES.NbInstances = 0
	__GongStructShape__000031_Default_SPECTYPES.Width = 240.000000
	__GongStructShape__000031_Default_SPECTYPES.Height = 63.000000
	__GongStructShape__000031_Default_SPECTYPES.IsSelected = false

	__GongStructShape__000032_Default_TARGET.Name = `Default-TARGET`

	//gong:ident [ref_models.TARGET] comment added to overcome the problem with the comment map association
	__GongStructShape__000032_Default_TARGET.Identifier = `ref_models.TARGET`
	__GongStructShape__000032_Default_TARGET.ShowNbInstances = false
	__GongStructShape__000032_Default_TARGET.NbInstances = 0
	__GongStructShape__000032_Default_TARGET.Width = 240.000000
	__GongStructShape__000032_Default_TARGET.Height = 63.000000
	__GongStructShape__000032_Default_TARGET.IsSelected = false

	__GongStructShape__000033_Default_TARGETSPECIFICATION.Name = `Default-TARGETSPECIFICATION`

	//gong:ident [ref_models.TARGETSPECIFICATION] comment added to overcome the problem with the comment map association
	__GongStructShape__000033_Default_TARGETSPECIFICATION.Identifier = `ref_models.TARGETSPECIFICATION`
	__GongStructShape__000033_Default_TARGETSPECIFICATION.ShowNbInstances = false
	__GongStructShape__000033_Default_TARGETSPECIFICATION.NbInstances = 0
	__GongStructShape__000033_Default_TARGETSPECIFICATION.Width = 240.000000
	__GongStructShape__000033_Default_TARGETSPECIFICATION.Height = 63.000000
	__GongStructShape__000033_Default_TARGETSPECIFICATION.IsSelected = false

	__GongStructShape__000034_Default_THEHEADER.Name = `Default-THEHEADER`

	//gong:ident [ref_models.THEHEADER] comment added to overcome the problem with the comment map association
	__GongStructShape__000034_Default_THEHEADER.Identifier = `ref_models.THEHEADER`
	__GongStructShape__000034_Default_THEHEADER.ShowNbInstances = false
	__GongStructShape__000034_Default_THEHEADER.NbInstances = 0
	__GongStructShape__000034_Default_THEHEADER.Width = 240.000000
	__GongStructShape__000034_Default_THEHEADER.Height = 63.000000
	__GongStructShape__000034_Default_THEHEADER.IsSelected = false

	__GongStructShape__000035_Default_TOOLEXTENSIONS.Name = `Default-TOOLEXTENSIONS`

	//gong:ident [ref_models.TOOLEXTENSIONS] comment added to overcome the problem with the comment map association
	__GongStructShape__000035_Default_TOOLEXTENSIONS.Identifier = `ref_models.TOOLEXTENSIONS`
	__GongStructShape__000035_Default_TOOLEXTENSIONS.ShowNbInstances = false
	__GongStructShape__000035_Default_TOOLEXTENSIONS.NbInstances = 0
	__GongStructShape__000035_Default_TOOLEXTENSIONS.Width = 240.000000
	__GongStructShape__000035_Default_TOOLEXTENSIONS.Height = 63.000000
	__GongStructShape__000035_Default_TOOLEXTENSIONS.IsSelected = false

	__GongStructShape__000036_Default_VALUES.Name = `Default-VALUES`

	//gong:ident [ref_models.VALUES] comment added to overcome the problem with the comment map association
	__GongStructShape__000036_Default_VALUES.Identifier = `ref_models.VALUES`
	__GongStructShape__000036_Default_VALUES.ShowNbInstances = false
	__GongStructShape__000036_Default_VALUES.NbInstances = 0
	__GongStructShape__000036_Default_VALUES.Width = 240.000000
	__GongStructShape__000036_Default_VALUES.Height = 63.000000
	__GongStructShape__000036_Default_VALUES.IsSelected = false

	__GongStructShape__000037_Default_XHTMLCONTENT.Name = `Default-XHTMLCONTENT`

	//gong:ident [ref_models.XHTMLCONTENT] comment added to overcome the problem with the comment map association
	__GongStructShape__000037_Default_XHTMLCONTENT.Identifier = `ref_models.XHTMLCONTENT`
	__GongStructShape__000037_Default_XHTMLCONTENT.ShowNbInstances = false
	__GongStructShape__000037_Default_XHTMLCONTENT.NbInstances = 0
	__GongStructShape__000037_Default_XHTMLCONTENT.Width = 240.000000
	__GongStructShape__000037_Default_XHTMLCONTENT.Height = 63.000000
	__GongStructShape__000037_Default_XHTMLCONTENT.IsSelected = false

	__Link__000000_HEADER.Name = `HEADER`

	//gong:ident [ref_models.REQIF.HEADER] comment added to overcome the problem with the comment map association
	__Link__000000_HEADER.Identifier = `ref_models.REQIF.HEADER`

	//gong:ident [ref_models.THEHEADER] comment added to overcome the problem with the comment map association
	__Link__000000_HEADER.Fieldtypename = `ref_models.THEHEADER`
	__Link__000000_HEADER.FieldOffsetX = -50.000000
	__Link__000000_HEADER.FieldOffsetY = -16.000000
	__Link__000000_HEADER.TargetMultiplicity = models.ZERO_ONE
	__Link__000000_HEADER.TargetMultiplicityOffsetX = -50.000000
	__Link__000000_HEADER.TargetMultiplicityOffsetY = 16.000000
	__Link__000000_HEADER.SourceMultiplicity = models.MANY
	__Link__000000_HEADER.SourceMultiplicityOffsetX = 10.000000
	__Link__000000_HEADER.SourceMultiplicityOffsetY = -50.000000
	__Link__000000_HEADER.StartOrientation = models.ORIENTATION_HORIZONTAL
	__Link__000000_HEADER.StartRatio = 0.500000
	__Link__000000_HEADER.EndOrientation = models.ORIENTATION_HORIZONTAL
	__Link__000000_HEADER.EndRatio = 0.500000
	__Link__000000_HEADER.CornerOffsetRatio = 1.380000

	__Position__000000_Pos_Default_DATATYPEDEFINITIONXHTML.X = 1144.000061
	__Position__000000_Pos_Default_DATATYPEDEFINITIONXHTML.Y = 624.000000
	__Position__000000_Pos_Default_DATATYPEDEFINITIONXHTML.Name = `Pos-Default-DATATYPEDEFINITIONXHTML`

	__Position__000001_Pos_Default_DATATYPES.X = 19.000000
	__Position__000001_Pos_Default_DATATYPES.Y = 712.000000
	__Position__000001_Pos_Default_DATATYPES.Name = `Pos-Default-DATATYPES`

	__Position__000002_Pos_Default_DEFAULTVALUE.X = 75.000000
	__Position__000002_Pos_Default_DEFAULTVALUE.Y = 14.000000
	__Position__000002_Pos_Default_DEFAULTVALUE.Name = `Pos-Default-DEFAULTVALUE`

	__Position__000003_Pos_Default_DEFINITION.X = 117.000000
	__Position__000003_Pos_Default_DEFINITION.Y = 149.000000
	__Position__000003_Pos_Default_DEFINITION.Name = `Pos-Default-DEFINITION`

	__Position__000004_Pos_Default_EDITABLEATTS.X = 812.000000
	__Position__000004_Pos_Default_EDITABLEATTS.Y = 489.000000
	__Position__000004_Pos_Default_EDITABLEATTS.Name = `Pos-Default-EDITABLEATTS`

	__Position__000005_Pos_Default_EMBEDDEDVALUE.X = 919.000061
	__Position__000005_Pos_Default_EMBEDDEDVALUE.Y = 599.000000
	__Position__000005_Pos_Default_EMBEDDEDVALUE.Name = `Pos-Default-EMBEDDEDVALUE`

	__Position__000006_Pos_Default_ENUMVALUE.X = 1116.000061
	__Position__000006_Pos_Default_ENUMVALUE.Y = 823.000000
	__Position__000006_Pos_Default_ENUMVALUE.Name = `Pos-Default-ENUMVALUE`

	__Position__000007_Pos_Default_OBJECT.X = 662.000000
	__Position__000007_Pos_Default_OBJECT.Y = 820.000000
	__Position__000007_Pos_Default_OBJECT.Name = `Pos-Default-OBJECT`

	__Position__000008_Pos_Default_PROPERTIES.X = 76.000000
	__Position__000008_Pos_Default_PROPERTIES.Y = 563.000000
	__Position__000008_Pos_Default_PROPERTIES.Name = `Pos-Default-PROPERTIES`

	__Position__000009_Pos_Default_RELATIONGROUP.X = 319.000000
	__Position__000009_Pos_Default_RELATIONGROUP.Y = 330.000000
	__Position__000009_Pos_Default_RELATIONGROUP.Name = `Pos-Default-RELATIONGROUP`

	__Position__000010_Pos_Default_RELATIONGROUPTYPE.X = 39.000000
	__Position__000010_Pos_Default_RELATIONGROUPTYPE.Y = 86.000000
	__Position__000010_Pos_Default_RELATIONGROUPTYPE.Name = `Pos-Default-RELATIONGROUPTYPE`

	__Position__000011_Pos_Default_REQIF.X = 30.000000
	__Position__000011_Pos_Default_REQIF.Y = 20.000000
	__Position__000011_Pos_Default_REQIF.Name = `Pos-Default-REQIF`

	__Position__000012_Pos_Default_REQIFCONTENT.X = 374.000000
	__Position__000012_Pos_Default_REQIFCONTENT.Y = 330.000000
	__Position__000012_Pos_Default_REQIFCONTENT.Name = `Pos-Default-REQIFCONTENT`

	__Position__000013_Pos_Default_REQIFHEADER.X = 961.000061
	__Position__000013_Pos_Default_REQIFHEADER.Y = 37.000000
	__Position__000013_Pos_Default_REQIFHEADER.Name = `Pos-Default-REQIFHEADER`

	__Position__000014_Pos_Default_REQIFTOOLEXTENSION.X = 654.000000
	__Position__000014_Pos_Default_REQIFTOOLEXTENSION.Y = 201.000000
	__Position__000014_Pos_Default_REQIFTOOLEXTENSION.Name = `Pos-Default-REQIFTOOLEXTENSION`

	__Position__000015_Pos_Default_REQIFTYPE.X = 789.000000
	__Position__000015_Pos_Default_REQIFTYPE.Y = 368.000000
	__Position__000015_Pos_Default_REQIFTYPE.Name = `Pos-Default-REQIFTYPE`

	__Position__000016_Pos_Default_SOURCE.X = 653.000000
	__Position__000016_Pos_Default_SOURCE.Y = 519.000000
	__Position__000016_Pos_Default_SOURCE.Name = `Pos-Default-SOURCE`

	__Position__000017_Pos_Default_SOURCESPECIFICATION.X = 1031.000061
	__Position__000017_Pos_Default_SOURCESPECIFICATION.Y = 302.000000
	__Position__000017_Pos_Default_SOURCESPECIFICATION.Name = `Pos-Default-SOURCESPECIFICATION`

	__Position__000018_Pos_Default_SPECATTRIBUTES.X = 829.000000
	__Position__000018_Pos_Default_SPECATTRIBUTES.Y = 141.000000
	__Position__000018_Pos_Default_SPECATTRIBUTES.Name = `Pos-Default-SPECATTRIBUTES`

	__Position__000019_Pos_Default_SPECHIERARCHY.X = 1093.000061
	__Position__000019_Pos_Default_SPECHIERARCHY.Y = 525.000000
	__Position__000019_Pos_Default_SPECHIERARCHY.Name = `Pos-Default-SPECHIERARCHY`

	__Position__000020_Pos_Default_SPECIFICATION.X = 1018.000061
	__Position__000020_Pos_Default_SPECIFICATION.Y = 70.000000
	__Position__000020_Pos_Default_SPECIFICATION.Name = `Pos-Default-SPECIFICATION`

	__Position__000021_Pos_Default_SPECIFICATIONS.X = 278.000000
	__Position__000021_Pos_Default_SPECIFICATIONS.Y = 496.000000
	__Position__000021_Pos_Default_SPECIFICATIONS.Name = `Pos-Default-SPECIFICATIONS`

	__Position__000022_Pos_Default_SPECIFICATIONTYPE.X = 372.000000
	__Position__000022_Pos_Default_SPECIFICATIONTYPE.Y = 223.000000
	__Position__000022_Pos_Default_SPECIFICATIONTYPE.Name = `Pos-Default-SPECIFICATIONTYPE`

	__Position__000023_Pos_Default_SPECIFIEDVALUES.X = 333.000000
	__Position__000023_Pos_Default_SPECIFIEDVALUES.Y = 656.000000
	__Position__000023_Pos_Default_SPECIFIEDVALUES.Name = `Pos-Default-SPECIFIEDVALUES`

	__Position__000024_Pos_Default_SPECOBJECT.X = 628.000000
	__Position__000024_Pos_Default_SPECOBJECT.Y = 644.000000
	__Position__000024_Pos_Default_SPECOBJECT.Name = `Pos-Default-SPECOBJECT`

	__Position__000025_Pos_Default_SPECOBJECTS.X = 633.000000
	__Position__000025_Pos_Default_SPECOBJECTS.Y = 388.000000
	__Position__000025_Pos_Default_SPECOBJECTS.Name = `Pos-Default-SPECOBJECTS`

	__Position__000026_Pos_Default_SPECOBJECTTYPE.X = 61.000000
	__Position__000026_Pos_Default_SPECOBJECTTYPE.Y = 294.000000
	__Position__000026_Pos_Default_SPECOBJECTTYPE.Name = `Pos-Default-SPECOBJECTTYPE`

	__Position__000027_Pos_Default_SPECRELATION.X = 308.000000
	__Position__000027_Pos_Default_SPECRELATION.Y = 187.000000
	__Position__000027_Pos_Default_SPECRELATION.Name = `Pos-Default-SPECRELATION`

	__Position__000028_Pos_Default_SPECRELATIONGROUPS.X = 87.000000
	__Position__000028_Pos_Default_SPECRELATIONGROUPS.Y = 525.000000
	__Position__000028_Pos_Default_SPECRELATIONGROUPS.Name = `Pos-Default-SPECRELATIONGROUPS`

	__Position__000029_Pos_Default_SPECRELATIONS.X = 512.000000
	__Position__000029_Pos_Default_SPECRELATIONS.Y = 750.000000
	__Position__000029_Pos_Default_SPECRELATIONS.Name = `Pos-Default-SPECRELATIONS`

	__Position__000030_Pos_Default_SPECRELATIONTYPE.X = 31.000000
	__Position__000030_Pos_Default_SPECRELATIONTYPE.Y = 212.000000
	__Position__000030_Pos_Default_SPECRELATIONTYPE.Name = `Pos-Default-SPECRELATIONTYPE`

	__Position__000031_Pos_Default_SPECTYPES.X = 90.000000
	__Position__000031_Pos_Default_SPECTYPES.Y = 385.000000
	__Position__000031_Pos_Default_SPECTYPES.Name = `Pos-Default-SPECTYPES`

	__Position__000032_Pos_Default_TARGET.X = 91.000000
	__Position__000032_Pos_Default_TARGET.Y = 697.000000
	__Position__000032_Pos_Default_TARGET.Name = `Pos-Default-TARGET`

	__Position__000033_Pos_Default_TARGETSPECIFICATION.X = 323.000000
	__Position__000033_Pos_Default_TARGETSPECIFICATION.Y = 395.000000
	__Position__000033_Pos_Default_TARGETSPECIFICATION.Name = `Pos-Default-TARGETSPECIFICATION`

	__Position__000034_Pos_Default_THEHEADER.X = 644.000061
	__Position__000034_Pos_Default_THEHEADER.Y = 9.000000
	__Position__000034_Pos_Default_THEHEADER.Name = `Pos-Default-THEHEADER`

	__Position__000035_Pos_Default_TOOLEXTENSIONS.X = 818.000000
	__Position__000035_Pos_Default_TOOLEXTENSIONS.Y = 769.000000
	__Position__000035_Pos_Default_TOOLEXTENSIONS.Name = `Pos-Default-TOOLEXTENSIONS`

	__Position__000036_Pos_Default_VALUES.X = 192.000000
	__Position__000036_Pos_Default_VALUES.Y = 827.000000
	__Position__000036_Pos_Default_VALUES.Name = `Pos-Default-VALUES`

	__Position__000037_Pos_Default_XHTMLCONTENT.X = 210.000000
	__Position__000037_Pos_Default_XHTMLCONTENT.Y = 173.000000
	__Position__000037_Pos_Default_XHTMLCONTENT.Name = `Pos-Default-XHTMLCONTENT`

	__Vertice__000000_Verticle_in_class_diagram_Default_in_middle_between_Default_REQIF_and_Default_THEHEADER.X = 788.500031
	__Vertice__000000_Verticle_in_class_diagram_Default_in_middle_between_Default_REQIF_and_Default_THEHEADER.Y = 354.000000
	__Vertice__000000_Verticle_in_class_diagram_Default_in_middle_between_Default_REQIF_and_Default_THEHEADER.Name = `Verticle in class diagram Default in middle between Default-REQIF and Default-THEHEADER`

	// Setup of pointers
	__Classdiagram__000000_Default.GongStructShapes = append(__Classdiagram__000000_Default.GongStructShapes, __GongStructShape__000011_Default_REQIF)
	__Classdiagram__000000_Default.GongStructShapes = append(__Classdiagram__000000_Default.GongStructShapes, __GongStructShape__000034_Default_THEHEADER)
	__Classdiagram__000000_Default.GongStructShapes = append(__Classdiagram__000000_Default.GongStructShapes, __GongStructShape__000037_Default_XHTMLCONTENT)
	__Classdiagram__000000_Default.GongStructShapes = append(__Classdiagram__000000_Default.GongStructShapes, __GongStructShape__000036_Default_VALUES)
	__Classdiagram__000000_Default.GongStructShapes = append(__Classdiagram__000000_Default.GongStructShapes, __GongStructShape__000035_Default_TOOLEXTENSIONS)
	__Classdiagram__000000_Default.GongStructShapes = append(__Classdiagram__000000_Default.GongStructShapes, __GongStructShape__000033_Default_TARGETSPECIFICATION)
	__Classdiagram__000000_Default.GongStructShapes = append(__Classdiagram__000000_Default.GongStructShapes, __GongStructShape__000032_Default_TARGET)
	__Classdiagram__000000_Default.GongStructShapes = append(__Classdiagram__000000_Default.GongStructShapes, __GongStructShape__000031_Default_SPECTYPES)
	__Classdiagram__000000_Default.GongStructShapes = append(__Classdiagram__000000_Default.GongStructShapes, __GongStructShape__000030_Default_SPECRELATIONTYPE)
	__Classdiagram__000000_Default.GongStructShapes = append(__Classdiagram__000000_Default.GongStructShapes, __GongStructShape__000029_Default_SPECRELATIONS)
	__Classdiagram__000000_Default.GongStructShapes = append(__Classdiagram__000000_Default.GongStructShapes, __GongStructShape__000028_Default_SPECRELATIONGROUPS)
	__Classdiagram__000000_Default.GongStructShapes = append(__Classdiagram__000000_Default.GongStructShapes, __GongStructShape__000027_Default_SPECRELATION)
	__Classdiagram__000000_Default.GongStructShapes = append(__Classdiagram__000000_Default.GongStructShapes, __GongStructShape__000026_Default_SPECOBJECTTYPE)
	__Classdiagram__000000_Default.GongStructShapes = append(__Classdiagram__000000_Default.GongStructShapes, __GongStructShape__000025_Default_SPECOBJECTS)
	__Classdiagram__000000_Default.GongStructShapes = append(__Classdiagram__000000_Default.GongStructShapes, __GongStructShape__000024_Default_SPECOBJECT)
	__Classdiagram__000000_Default.GongStructShapes = append(__Classdiagram__000000_Default.GongStructShapes, __GongStructShape__000023_Default_SPECIFIEDVALUES)
	__Classdiagram__000000_Default.GongStructShapes = append(__Classdiagram__000000_Default.GongStructShapes, __GongStructShape__000022_Default_SPECIFICATIONTYPE)
	__Classdiagram__000000_Default.GongStructShapes = append(__Classdiagram__000000_Default.GongStructShapes, __GongStructShape__000021_Default_SPECIFICATIONS)
	__Classdiagram__000000_Default.GongStructShapes = append(__Classdiagram__000000_Default.GongStructShapes, __GongStructShape__000020_Default_SPECIFICATION)
	__Classdiagram__000000_Default.GongStructShapes = append(__Classdiagram__000000_Default.GongStructShapes, __GongStructShape__000019_Default_SPECHIERARCHY)
	__Classdiagram__000000_Default.GongStructShapes = append(__Classdiagram__000000_Default.GongStructShapes, __GongStructShape__000018_Default_SPECATTRIBUTES)
	__Classdiagram__000000_Default.GongStructShapes = append(__Classdiagram__000000_Default.GongStructShapes, __GongStructShape__000017_Default_SOURCESPECIFICATION)
	__Classdiagram__000000_Default.GongStructShapes = append(__Classdiagram__000000_Default.GongStructShapes, __GongStructShape__000016_Default_SOURCE)
	__Classdiagram__000000_Default.GongStructShapes = append(__Classdiagram__000000_Default.GongStructShapes, __GongStructShape__000015_Default_REQIFTYPE)
	__Classdiagram__000000_Default.GongStructShapes = append(__Classdiagram__000000_Default.GongStructShapes, __GongStructShape__000014_Default_REQIFTOOLEXTENSION)
	__Classdiagram__000000_Default.GongStructShapes = append(__Classdiagram__000000_Default.GongStructShapes, __GongStructShape__000013_Default_REQIFHEADER)
	__Classdiagram__000000_Default.GongStructShapes = append(__Classdiagram__000000_Default.GongStructShapes, __GongStructShape__000012_Default_REQIFCONTENT)
	__Classdiagram__000000_Default.GongStructShapes = append(__Classdiagram__000000_Default.GongStructShapes, __GongStructShape__000010_Default_RELATIONGROUPTYPE)
	__Classdiagram__000000_Default.GongStructShapes = append(__Classdiagram__000000_Default.GongStructShapes, __GongStructShape__000009_Default_RELATIONGROUP)
	__Classdiagram__000000_Default.GongStructShapes = append(__Classdiagram__000000_Default.GongStructShapes, __GongStructShape__000008_Default_PROPERTIES)
	__Classdiagram__000000_Default.GongStructShapes = append(__Classdiagram__000000_Default.GongStructShapes, __GongStructShape__000007_Default_OBJECT)
	__Classdiagram__000000_Default.GongStructShapes = append(__Classdiagram__000000_Default.GongStructShapes, __GongStructShape__000006_Default_ENUMVALUE)
	__Classdiagram__000000_Default.GongStructShapes = append(__Classdiagram__000000_Default.GongStructShapes, __GongStructShape__000005_Default_EMBEDDEDVALUE)
	__Classdiagram__000000_Default.GongStructShapes = append(__Classdiagram__000000_Default.GongStructShapes, __GongStructShape__000004_Default_EDITABLEATTS)
	__Classdiagram__000000_Default.GongStructShapes = append(__Classdiagram__000000_Default.GongStructShapes, __GongStructShape__000003_Default_DEFINITION)
	__Classdiagram__000000_Default.GongStructShapes = append(__Classdiagram__000000_Default.GongStructShapes, __GongStructShape__000002_Default_DEFAULTVALUE)
	__Classdiagram__000000_Default.GongStructShapes = append(__Classdiagram__000000_Default.GongStructShapes, __GongStructShape__000001_Default_DATATYPES)
	__Classdiagram__000000_Default.GongStructShapes = append(__Classdiagram__000000_Default.GongStructShapes, __GongStructShape__000000_Default_DATATYPEDEFINITIONXHTML)
	__GongStructShape__000000_Default_DATATYPEDEFINITIONXHTML.Position = __Position__000000_Pos_Default_DATATYPEDEFINITIONXHTML
	__GongStructShape__000001_Default_DATATYPES.Position = __Position__000001_Pos_Default_DATATYPES
	__GongStructShape__000002_Default_DEFAULTVALUE.Position = __Position__000002_Pos_Default_DEFAULTVALUE
	__GongStructShape__000003_Default_DEFINITION.Position = __Position__000003_Pos_Default_DEFINITION
	__GongStructShape__000004_Default_EDITABLEATTS.Position = __Position__000004_Pos_Default_EDITABLEATTS
	__GongStructShape__000005_Default_EMBEDDEDVALUE.Position = __Position__000005_Pos_Default_EMBEDDEDVALUE
	__GongStructShape__000006_Default_ENUMVALUE.Position = __Position__000006_Pos_Default_ENUMVALUE
	__GongStructShape__000007_Default_OBJECT.Position = __Position__000007_Pos_Default_OBJECT
	__GongStructShape__000008_Default_PROPERTIES.Position = __Position__000008_Pos_Default_PROPERTIES
	__GongStructShape__000009_Default_RELATIONGROUP.Position = __Position__000009_Pos_Default_RELATIONGROUP
	__GongStructShape__000010_Default_RELATIONGROUPTYPE.Position = __Position__000010_Pos_Default_RELATIONGROUPTYPE
	__GongStructShape__000011_Default_REQIF.Position = __Position__000011_Pos_Default_REQIF
	__GongStructShape__000011_Default_REQIF.Links = append(__GongStructShape__000011_Default_REQIF.Links, __Link__000000_HEADER)
	__GongStructShape__000012_Default_REQIFCONTENT.Position = __Position__000012_Pos_Default_REQIFCONTENT
	__GongStructShape__000013_Default_REQIFHEADER.Position = __Position__000013_Pos_Default_REQIFHEADER
	__GongStructShape__000014_Default_REQIFTOOLEXTENSION.Position = __Position__000014_Pos_Default_REQIFTOOLEXTENSION
	__GongStructShape__000015_Default_REQIFTYPE.Position = __Position__000015_Pos_Default_REQIFTYPE
	__GongStructShape__000016_Default_SOURCE.Position = __Position__000016_Pos_Default_SOURCE
	__GongStructShape__000017_Default_SOURCESPECIFICATION.Position = __Position__000017_Pos_Default_SOURCESPECIFICATION
	__GongStructShape__000018_Default_SPECATTRIBUTES.Position = __Position__000018_Pos_Default_SPECATTRIBUTES
	__GongStructShape__000019_Default_SPECHIERARCHY.Position = __Position__000019_Pos_Default_SPECHIERARCHY
	__GongStructShape__000020_Default_SPECIFICATION.Position = __Position__000020_Pos_Default_SPECIFICATION
	__GongStructShape__000021_Default_SPECIFICATIONS.Position = __Position__000021_Pos_Default_SPECIFICATIONS
	__GongStructShape__000022_Default_SPECIFICATIONTYPE.Position = __Position__000022_Pos_Default_SPECIFICATIONTYPE
	__GongStructShape__000023_Default_SPECIFIEDVALUES.Position = __Position__000023_Pos_Default_SPECIFIEDVALUES
	__GongStructShape__000024_Default_SPECOBJECT.Position = __Position__000024_Pos_Default_SPECOBJECT
	__GongStructShape__000025_Default_SPECOBJECTS.Position = __Position__000025_Pos_Default_SPECOBJECTS
	__GongStructShape__000026_Default_SPECOBJECTTYPE.Position = __Position__000026_Pos_Default_SPECOBJECTTYPE
	__GongStructShape__000027_Default_SPECRELATION.Position = __Position__000027_Pos_Default_SPECRELATION
	__GongStructShape__000028_Default_SPECRELATIONGROUPS.Position = __Position__000028_Pos_Default_SPECRELATIONGROUPS
	__GongStructShape__000029_Default_SPECRELATIONS.Position = __Position__000029_Pos_Default_SPECRELATIONS
	__GongStructShape__000030_Default_SPECRELATIONTYPE.Position = __Position__000030_Pos_Default_SPECRELATIONTYPE
	__GongStructShape__000031_Default_SPECTYPES.Position = __Position__000031_Pos_Default_SPECTYPES
	__GongStructShape__000032_Default_TARGET.Position = __Position__000032_Pos_Default_TARGET
	__GongStructShape__000033_Default_TARGETSPECIFICATION.Position = __Position__000033_Pos_Default_TARGETSPECIFICATION
	__GongStructShape__000034_Default_THEHEADER.Position = __Position__000034_Pos_Default_THEHEADER
	__GongStructShape__000035_Default_TOOLEXTENSIONS.Position = __Position__000035_Pos_Default_TOOLEXTENSIONS
	__GongStructShape__000036_Default_VALUES.Position = __Position__000036_Pos_Default_VALUES
	__GongStructShape__000037_Default_XHTMLCONTENT.Position = __Position__000037_Pos_Default_XHTMLCONTENT
	__Link__000000_HEADER.Middlevertice = __Vertice__000000_Verticle_in_class_diagram_Default_in_middle_between_Default_REQIF_and_Default_THEHEADER
}
